### ISSUE TITLE
Add click events on weekday headings in week view

### ISSUE THREAD

**Issue by kylecueters** [antoniandre/vue-cal-v4#100]
I'm trying to add click events on the weekday heading in week view. What I'm trying to do is when the user clicked or maybe dblclicked on a weekday heading it will then be redirected to a day view on that particular date the user clicked.

**Comment by antoniandre** [comment]
Hi @kylecueters, 
I just released that new feature in version 1.53.0.
It has the same behavior as the cells.
**Only on week view:** a click on a heading selects the cell, and it will react to the options `dblClickToNavigate` and `clickToNavigate` to go to narrower view if allowed to.

Hope it helps.

**Comment by kylecueters** [comment]
Oh, I see. Got it! Thank you for replying.

**Comment by antoniandre** [comment]
All good, closing the issue then. 👌
