### ISSUE TITLE
Event title error in version 1.52.

### ISSUE THREAD

**Issue by gavinchua** [antoniandre/vue-cal-v4#101]
Hi @antoniandre ,

https://codesandbox.io/s/0q7m7r026v
Vue 2.6.10
The above code is working in version 1.49 but is not working in version 1.52. 
```
<div class="vuecal__event-title" v-text="event.title"/>
```
vuecal__cell-events is empty.
The console is not logging any JS error.

Not sure if its due to slots.

Please advice. Thanks.

**Comment by antoniandre** [comment]
HI @gavinchua, 
Thank you for reporting this bug. 
This is fixed in version 1.52.2
