### ISSUE TITLE
Overlapping events

### ISSUE THREAD

**Issue by ptzremote** [antoniandre/vue-cal-v4#103]
Hi!
I have an issue with overlapping events feature.
First time (on page open) it's look like expected, but after switch on month\week\day the events move with animation. This is best explained on video.
https://youtu.be/tFOKkvRih9E

vue: 2.6.10
vue-cal: 1.50.1

**Comment by antoniandre** [comment]
Hi @ptzremoute,
I fixed something similar today, please try upgrading Vue Cal to version 1.55.1 and let me know.

If it doesn't solve the issue, I will need your code to see what's wrong, please fork and update this codepen: https://codepen.io/antoniandre/pen/rPzWOJ

**Comment by ptzremote** [comment]
Hi @antoniandre,
I will check and then give you a feedback.

**Comment by ptzremote** [comment]
It's look better, but such error appears in console randomly (while switching weeks on a week view):
Error in render: "TypeError: Cannot read property 'simultaneous' of undefined"

vue.runtime.esm.js:1887 TypeError: Cannot read property 'simultaneous' of undefined
    at eval (vuecal.common.js:6033)
    at Array.forEach (<anonymous>)
    at VueComponent.eventClasses (vuecal.common.js:6030)
    at Proxy.eventvue_type_template_id_374bc0a9_lang_pug_render (vuecal.common.js:5931)
    at VueComponent.Vue._render (vue.runtime.esm.js:3536)
    at VueComponent.updateComponent (vue.runtime.esm.js:4054)
    at Watcher.get (vue.runtime.esm.js:4467)
    at new Watcher (vue.runtime.esm.js:4456)
    at mountComponent (vue.runtime.esm.js:4061)
    at VueComponent.Vue.$mount (vue.runtime.esm.js:8399)

**Comment by ptzremote** [comment]
@antoniandre ,
I reproduce error in this codepen: https://codepen.io/leohim/pen/EJdaMy

Switch to week and error will appear.

**Comment by antoniandre** [comment]
Hi @ptzremoute, 
Thanks for your reproduction link, that's great.
I understand the issue and I will solve it ASAP.

**Comment by antoniandre** [comment]
Hi @ptzremoute, 
This is now fixed in version 1.55.2, thanks for reporting!
(In your Codepen example if the error is still here make sure you hit https://unpkg.com/vue-cal@1.55.2)
