### ISSUE TITLE
Change selected date & current view

### ISSUE THREAD

**Issue by ShockwaVee** [antoniandre/vue-cal-v4#106]
Hey,

I'm currently trying to implement the following:
A 'today button' on which you can click and it will take you to the month view and select the todays date. I'm guessing it would require changing the selected date and the view you're currently on, but programatically.

I've checked the docs and tried implementing this on my own, but I couldn't do it.
Is this even possible in the current version?

**Comment by antoniandre** [comment]
Hi @ShockwaVee, 

This is definitely possible.
Here is a Codepen that does this: https://codepen.io/antoniandre/pen/yrREOL?editors=1010, but basically you just need to do  this on click:

```js
$refs.vuecal.switchView('day', new Date())
```

As it might be useful for many others as well, I will put that in the documentation soon!

Hope it helps.

**Comment by ShockwaVee** [comment]
Hi @antoniandre 
Great, that's exactly what I need, thanks a lot!

**Comment by antoniandre** [comment]
Hi @ShockwaVee, 
I just released a new version that includes a Today button as an option.
You may be interested: https://antoniandre.github.io/vue-cal/#ex--adding-a-today-button
