### ISSUE TITLE
Horizontal scroll with defined minCellWidth

### ISSUE THREAD

**Issue by kylecueters** [antoniandre/vue-cal-v4#108]
Hi, I'm currently working on making a single cell in week view wider using the minCellWidth. But when I defined a huge number of pixels the other days becomes hidden. Is there a way i can make it to scroll horizontally not to hide the other days? Thanks.

**Comment by antoniandre** [comment]
Hi @kylecueters,

Great that you ask. As this was not possible until now, I just released version 1.56.0 that allows using `min-cell-width` independently of day splitting.

Hope it helps.

**Comment by kylecueters** [comment]
This seems to be working fine. But I have a problem with the weekdays' headings whenever I scroll horizontally the other weekday heading seems to become hidden. I'm not sure about this but I think weekday headings width seems to be in 100vw? I guess. 

![heading cut](https://user-images.githubusercontent.com/29885103/56930802-8bc36d00-6b10-11e9-9ee3-1be130f98093.png)

**Comment by antoniandre** [comment]
Hi @kylecueters,

Can you check this codepen https://codepen.io/antoniandre/pen/ROmwOQ and see if it works.
If your case is different please update the codepen and post it here.

Cheers.

**Comment by kylecueters** [comment]
That's exactly what I just did, I think it is in my custom CSS for the weekday-headings that has the problem. My bad. Thanks for the reply tho!

**Comment by kylecueters** [comment]
I think the problem was I have a custom background color for the weekdays-headings class and you won't see the cut when the background of it was completely white. 

```
.vuecal--view-with-time.vuecal--time-12-hour .vuecal__weekdays-headings {
  color: white;
  background: #0e47a1;
  width: 2450px;
}
```

To make it full width I set the width with (MIN-CELL-WIDTH * 7). Also, I have a new problem now where the weekdays-headings seems to not stick on top when I scroll down the calendar.

This is what it looks like when not scrolled;
![1](https://user-images.githubusercontent.com/29885103/57121261-e24ad880-6da8-11e9-8aab-08c9da6b9727.png)

But when I scrolled it becomes this;
![2](https://user-images.githubusercontent.com/29885103/57121264-e5de5f80-6da8-11e9-9702-c6b31ae76ccd.png)

I tried to make the weekdays-headings class with position: fixed; but when it will have problems with scrolling horizontally. It doesn't move.

```
.vuecal--view-with-time.vuecal--time-12-hour .vuecal__weekdays-headings {
  color: white;
  background: #0e47a1;
  width: 2450px;
  position: fixed;
  z-index: 10;
}
```

Is there a way I can make the weekdays-headings stick in the top while scrolling vertically but not stick when scrolling horizontally?

**Comment by antoniandre** [comment]
Hi @kylecueters,
Unfortunately this cannot be done via CSS.
That's why in my https://antoniandre.github.io/vue-cal/#ex--splitting-days example, you can see that:

- **as long as there is a `minCellWidth`** the header is scrollable horizontally and the timeline remains on the left, but the header disappears when you scroll down.
- **when the minCellWidth is 0**, the header remains at the top when you scroll down.

With a `minCellWidth`, the only way to preserve the header "sticky" at the top while scrolling down and still sync it horizontally with the cells, is to do a Javascript calculation on scroll (to apply the current scroll amount in cells onto the header). But I will not include this in vue-cal.

**Comment by kylecueters** [comment]
@antoniandre yeah you right. Can't be done in CSS. Thanks for responding! I'll close this issue again.

**Comment by antoniandre** [comment]
Hi @kylecueters, 
If you still use Vue Cal, and you haven't fixed this, you might be interested in this question #286.
Cheers!
