### ISSUE TITLE
Allow passing css styles to events

### ISSUE THREAD

**Issue by antoniandre** [antoniandre/vue-cal-v4#115]
As per the original request #114, 
The request is to allow custom styles defined in the event object, and rendered it from within Vue Cal.

@nicholaszuccarelli

**Comment by antoniandre** [comment]
Hi @nicholaszuccarelli, I have created an example as a solution to this issue, where you can pass styles to events independently.
https://codepen.io/antoniandre/pen/XwNdQz

As this request is against the Vue Cal philosophy and for performance and simplicity, Vue Cal won't allow passing custom styles to be rendered from Vue Cal. 
I hope you can see the benefit of the custom event rendering and that it will allow you to customize as wished.

Please let me know if there is something more I can do.

**Comment by nicholaszuccarelli** [comment]
Thanks for that.
I had read the docs about the event-renderer slot but didn't actually think I could use it in this way.

Perfect solution for me. Thanks for the help!

**Comment by antoniandre** [comment]
Awesome! Let's close this then.

PS: the custom event rendering will change a bit in Vue Cal 2.0 to use the new slots syntax since Vue.js@2.6.0 (already implemented in the v2 branch).

Keep an eye on the release notes when it's out!

Cheers.
