### ISSUE TITLE
vue-cal needs unique keys - to handle multiple calendars on page shows same content due

### ISSUE THREAD

**Issue by CarlosOnline** [antoniandre/vue-cal-v4#117]
**Scenario:** Have a page with multiple vue-cal instances on the page (all with month view).

**Problem:** Month cells are showing the same contents even though each instance has a different set of events.

**Cause:** vue-cal is using duplicate keys for the month cells - specifically the VuecalCell components.

**Can you provide a key prefix that can be added to each key to allow for unique keys?**

![vue-cal-keys](https://user-images.githubusercontent.com/3691895/57737058-1783e000-765f-11e9-88f1-b44acc0a68b8.PNG)

**Comment by CarlosOnline** [comment]
Tried an experiment of setting unique keys and it didn't help.

The 2 calendars are both showing the same events even though each calendar has its own unique set of events.

**Any ideas on what could be causing this?**

Is it a global variable thing?
Or shared event?

**Comment by antoniandre** [comment]
Hi @CarlosOnline, 
As the documentation page has more than 30 instances and the cells are all different, I suggest that the problem comes from sharing the same events array, if that is the case can you try to copy the array before using it? (something like `eventsCopy = [...events]`)

**Comment by CarlosOnline** [comment]
Nevermind - figured it out my fault, don't ask :)
