### ISSUE TITLE
Feature request : resize an event on the top of this event

### ISSUE THREAD

**Issue by HarunaIchinose** [antoniandre/vue-cal-v4#118]
Today, we can resize EndTime but not StartTime.

**Comment by HarunaIchinose** [comment]
Can resize StartTime

**Comment by antoniandre** [comment]
Hi @HarunaIchinose, 
That is something that I keep in mind for later. 
But once the drag and drop is done, this might become not so useful.
we will see then.

**Comment by antoniandre** [comment]
Hi @HarunaIchinose, I am dropping this feature request now that the drag and drop can easily be used instead.
