### ISSUE TITLE
Feature Request : Choose different "component" between different view

### ISSUE THREAD

**Issue by HarunaIchinose** [antoniandre/vue-cal-v4#119]
For example : I want to have a splitDay in the day view but not in the month view

**Comment by antoniandre** [comment]
Hi @HarunaIchinose, sorry I totally missed your question. :/

This is actually already possible, here is a demo: https://codepen.io/antoniandre/pen/qeNKJx?editors=1010

Hope it helps, let me know if you still need guidance.

**Comment by HarunaIchinose** [comment]
oh thanks !
