### ISSUE TITLE
Edit Title Bar

### ISSUE THREAD

**Issue by jardimfelipe** [antoniandre/vue-cal-v4#121]
@antoniandre we have some way to edit title-bar content? Like this
![image](https://user-images.githubusercontent.com/24942146/58352746-e8315800-7e42-11e9-83d4-5cdc3b9120fe.png)

**Comment by antoniandre** [comment]
Hi @jardimfelipe,

You can provide all these buttons in the title slot like in this example: https://antoniandre.github.io/vue-cal/#ex--custom-title-and-cells.

So use (`slot-scope="{ title, view }"`), the `title` variable is already formatted.
Then inside the same slot, after the title place your buttons.
The 'next' button will be displayed at the right.

Hope that helps.

**Comment by jardimfelipe** [comment]
"Prev" and "Next" arrow have to be placed inside the title slot? This is what a got here 
![image](https://user-images.githubusercontent.com/24942146/58422850-05943b00-806a-11e9-9cba-a6f5f0a259c9.png)

And this is what I've done
![image](https://user-images.githubusercontent.com/24942146/58422867-117ffd00-806a-11e9-83cf-5fa9bfe3ecf0.png)

I dont know what I'm missing here

**Comment by jardimfelipe** [comment]
Thanks, that was really helpful
