### ISSUE TITLE
Events not displayed on week view (only on month view)

### ISSUE THREAD

**Issue by netanelwebninja** [antoniandre/vue-cal-v4#124]
Hey,

From some reason Im fetching events from server and pass them to vue-cal, the events are displayed correctly in month view but on week view they not displayed.
On week view, the specific day that should display the events is just empty.

See images for more info:
![PixelSnap 2019-05-28 at 18 38 07](https://user-images.githubusercontent.com/33468899/58491598-fbf8f900-8177-11e9-96e2-bf5b758af138.png)
![PixelSnap 2019-05-28 at 18 38 29](https://user-images.githubusercontent.com/33468899/58491599-fbf8f900-8177-11e9-895d-48141de1c403.png)
![PixelSnap 2019-05-28 at 18 39 10](https://user-images.githubusercontent.com/33468899/58491600-fc918f80-8177-11e9-96e2-62d8cfc5326b.png)

**Comment by enzonotario** [comment]
Hey! I also have this problem. Have you found a solution?

**Comment by enzonotario** [comment]
sorry, I put the time and now it works :)

**Comment by antoniandre** [comment]
Hi @netanelwebninja, 
From your screenshot I can see you are using the time option, all the events must have a time defined in the `start` and `end` properties - like in your event in position `0`.
The event in position `1` does not. Also the first event has no duration, it might be there but with a height of `0`.

Let me know.

@enzonotario, yes that's correct time is needed if you have a timeline.
