### ISSUE TITLE
How to set calendar view programmatically?

### ISSUE THREAD

**Issue by BernardZhao** [antoniandre/vue-cal-v4#129]
I was wondering if there is an existing way to change the calendar's view, for example from `week` to `day`, externally. I am intending to change the view to day on mobile devices, or when the window simply becomes too narrow.

**Comment by jardimfelipe** [comment]
I did that creating a listener to resize window and create a method to change de default-view. It worked to me

**Comment by antoniandre** [comment]
Hi @BernardZhao,

Yes there is a simple way of doing so using Vue refs. Here is an example: https://codepen.io/antoniandre/pen/yrREOL?editors=1010

And the original discussion here: #106 

Hope it helps.

**Comment by BernardZhao** [comment]
Thanks a ton, this answered my question.
