### ISSUE TITLE
Calendar title doesn't show by default and after passing as a slot

### ISSUE THREAD

**Issue by AndriiKost** [antoniandre/vue-cal-v4#130]
Having an issue with calendar title not displaying at all, even if no slot passed to vue-cal. Arrows didn't display either, but I found a hacky way to display them through CSS.

Please take a look and let me know if that is an internal issue or just me, and possible way to fix my problem.

Code snippet:
![2019-06-19_11-17-36](https://user-images.githubusercontent.com/18060463/59782575-dac18f00-9283-11e9-82e4-3fc102864483.png)

title = "Hello World"

Styles: 
![2019-06-19_11-18-17](https://user-images.githubusercontent.com/18060463/59782617-f75dc700-9283-11e9-88df-63a5fd0db8d0.png)

Result:
![2019-06-19_08-44-31](https://user-images.githubusercontent.com/18060463/59782731-3e4bbc80-9284-11e9-825c-9ed49e8439a1.png)
![2019-06-19_11-22-12](https://user-images.githubusercontent.com/18060463/59782877-84088500-9284-11e9-9de4-aee58569f148.png)

Expected result: Calendar title displaying custom or default title on the calendar (Ex. if Week selected, the title should be September 11 - September 16, if a day is selected, the title should show ex: September 11).

Packages: 
		"vue": "2.4.2",
		"vue-cal": "^1.58.0",

**Comment by antoniandre** [comment]
Hi @AndriiKost, Thanks for your feedback.
Can you make sure you use Vue.js 2.5.18 or later (as per the documentation https://antoniandre.github.io/vue-cal/#installation), then rebuild and let me know if that solve your issue.

**Comment by AndriiKost** [comment]
It works, thank you! Sometimes people don't read a "required" section ...

Great job with a calendar btw

**Comment by bribar** [comment]
Hi @antoniandre 

I have the same issue. I'm on Vue 2.5.18 and updated to the latest vue-cal. The title doesn't appear if I use a slot. If I remove it the title is there.

`<div slot="title" slot-scope="{ title, view }">
                        {{ setTitle(title, view) }}
                    </div>`

`setTitle: function(title, view){
            console.log(title, view)
            if(this.activeButton == 'timesheet'){
                title += ' Timesheet'
            }
            return title
        }`

This worked on older vue-cal version.

Any thoughts?

**Comment by antoniandre** [comment]
Hi @bribar,
You should be able to get it working with Vue@2.5.18 by replacing the div tag by a template tag like in this example: https://codepen.io/antoniandre/pen/BXNoKr

Hope it helps.

**Comment by bribar** [comment]
@antoniandre it did work! Can you help me understand why this slot `<div slot="event-renderer" slot-scope="{ event }">` works, but `<div slot="title" slot-scope="{ title, view }">` doesn't? Wouldn't both not work if it doesn't like the div tag?

**Comment by antoniandre** [comment]
Good question @bribar,
You are supposed to be able to use a custom tag with slots, but this is due to the different implementation inside `vue-cal` (my Vue template is written in pug):

```pug
slot(slot="title" name="title" :title="viewTitle" :view="view") {{ viewTitle }}
```

and:

```pug
div(slot="event-renderer" slot-scope="{ event, view }" :view="view" :event="event")
    slot(name="event-renderer" :view="view" :event="event")
```

As I am going toward Vue 2.6+ there is no point changing the implementation of the title as you can bypass the limitation of a div tag by using template and a div inside (resulting in same markup).

Anyway in the V2 coming out this coming week, the implementation uses the new Vue slots syntax:
E.g.

```pug
template(v-slot:event-renderer="{ event, view }")
    slot(name="event-renderer" :view="view" :event="event")
```

__vue-cal 2.0 is limited to Vue 2.6+ due to this new syntax.__
