### ISSUE TITLE
Hide a particular day ( like hide-weekends but for others days )

### ISSUE THREAD

**Issue by 4vrel** [antoniandre/vue-cal-v4#132]
Hello !
Let's say my working weeks are from Wednesday to Sunday, how can I show only those day ? ( and hide Monday, Tuesday and Thursday )
Thanks

**Comment by antoniandre** [comment]
Hi @4vrel,
Thanks for your feedback, this is currently not an option in vue-cal, and already a feature request here #104, but until this option is added, you can hide days in CSS as explained in the same feature request.

Closing this issue, please continue discussion in #104.
