### ISSUE TITLE
Simplified Week View 

### ISSUE THREAD

**Issue by rogeliohoyos** [antoniandre/vue-cal-v4#133]
Greetings calendar master.
Your api is great, but I wonder if it is possible a special week view where there are no days. Of course with Events. I mean like this,
![image](https://user-images.githubusercontent.com/52336859/60377825-74eda980-99df-11e9-9697-d1309ca584aa.png)

**Comment by antoniandre** [comment]
Hi @rogeliohoyos, thanks for your feedback.

How do you expect the events to be displayed in this view? do you have in mind something like this https://antoniandre.github.io/vue-cal/#ex--timeless-events in day view?

I am not sure if it is a good thing to mix the events of a whole week in one cell, and you won't have the time information obviously. But if this is what you want here is what I suggest you could do:

1. get all the events from vue-cal current view on view change
2. display the events in a container outside of vue-cal and show it on top of vue-cal when current view is week
3. clicking an events goes to vue-cal day view (optional)

I created a demo for you here https://codepen.io/antoniandre/pen/gNeKmY.

Let me know if something is not clear or if you need more assistance.

**Comment by antoniandre** [comment]
Closed for inactivity.
