### ISSUE TITLE
Vue-call modal is unable to read javascript date object

### ISSUE THREAD

**Issue by eakenbor** [antoniandre/vue-cal-v4#135]
I have a problem passing the dates I received from my mongodb server onto the vue-cal modal as start and end dates. I passed the dates as new Date("2019-06-24T16:00:00.140Z"). 
I also passed the string just like this "2019-06-24T16:00:00.140Z" but it did not accept. Instead the calendar just disappeared completely from the DOM.
Please can anyone explain what I am doing wrong?

**Comment by antoniandre** [comment]
Hi @eakenbor,

Please share some code if problem is not solved after that.
As per the documentation in API > events (https://antoniandre.github.io/vue-cal/#api), and until V2 is out, the only way to set event dates is this format: `yyyy-mm-dd hh:mm`.

V2 will accept passing JavaScript Date objects.

Let me know if you need more help. If so please share your code.

**Comment by eakenbor** [comment]
Thanks antoniandre. I managed to concatenate the dates before passing them in. However, when are you expecting to release v2? The feature of event creation by clicking on a time in the calendar is a very important feature that I need now.

**Comment by antoniandre** [comment]
There's probably 2, 3 weeks of work before release.
