### ISSUE TITLE
class in xsmall tpl

### ISSUE THREAD

**Issue by jeffsta9** [antoniandre/vue-cal-v4#141]
I love this calendar. I actually ditched another really nice one for this one instead because of some small features (very worth it); thank you :) That being said, I am using vue-cal with the `xsmall` parameter and a `class` parameter in the event objects, like so...

    [
    ...
    {
        start: datetimeStart,
        end: datetimeEnd,
        ...
        class: 'reg-last-date'
    },
    ...
    ]

However, I do not see the class "reg-last-date" in the resulting HTML, which I'd like to use to color the dash indicator. Am I missing something? If not, is there a possibility of adding this to the xsmall version of the calendar?

**Comment by antoniandre** [comment]
Hi @jeffster9,
Thanks for your feedback, I appreciate it. :)
Regarding the issue, yes this is supposed to work, I don't see all your code, but here is a working example to see it in action and check how it is written. https://codepen.io/antoniandre/pen/ymLNWm?editors=1010
If it does not help please show me your code, and ideally a reproduction link.
Cheers.

**Comment by jeffsta9** [comment]
Perhaps I should have mentioned that I'm trying to change the color of the "dash indicator" for the **Month** view. In the example you provided, all of the circles around the numbers (which, as you know, are used to create the dash), indicating the count of events on a date, are blue; even the one on the 19th, which has the class parameter set to "green-event".  The code snippet below is directly from the resulting HTML (via "inspect") of the example you provided and, as you can see, there is no "green-event" class attribute:

    <div class="vuecal__cell vuecal__cell--has-events"><div data-split="0" column="" class="vuecal__flex vuecal__cell-content"><div><div class="vuecal__cell-date">19</div><div class="vuecal__cell-events-count">2</div></div></div></div>

However, while viewing the event in **Week** view and inspecting the resulting HTML for the event, the "green-event" class attribute does exist:

    <div class="vuecal__event green-event vuecal__event--focus" style="top: 23px; height: 37px;"><div><div view="week" event="[object Object]"><div class="vuecal__event-title">Doctor appointment</div><div class="vuecal__event-time">10:35<span>&nbsp;- 11:30</span></div></div></div></div>

So, the issue I am experiencing is only relevant to the Month view. Again, I should have mentioned that to begin with; my bad. 

I do realize the issue though. It is that the indicator on the month view is relative to all of the events on that day; so, we cannot adjust that via event params as there may be other events on that day that would have different classes. It would be nice, though, if we could have a separate indicator for each different class on a single day while in month view. However, I know that could prove difficult to manage if there were more than, say, 3 different classes associated with a day's events.

Anyway, I will work w/ the single color for event indicators in month view for now. Perhaps I will fork it some day and have a go at it :)

Thanks again for all your time & effort on this!

**Comment by antoniandre** [comment]
Ok, I understand the issue.
As per this example in documentation: https://antoniandre.github.io/vue-cal/#ex--custom-events-count
You can try the updated codepen here: https://codepen.io/antoniandre/pen/ymLNWm

Hope it helps. Otherwise let me know.

**Comment by jeffsta9** [comment]
And there we have it. Thanks for that :) Cheers!
