### ISSUE TITLE
Allowed formats for dateFormat string

### ISSUE THREAD

**Issue by risafj** [antoniandre/vue-cal-v4#142]
Hi @antoniandre , I'm planning to raise a pull request with a Japanese translation for vue-cal. I have a question - is it possible to use characters in the `dateFormat` string that aren't a part of the specified characters in the docs (`DDDD`, `yyyy`, `mmmm`, and `d`)?

> DDDD stands for the full-letter day of week, mmmm stands for full-letter month, d stands for the date of the month (0-31), yyyy stands for full year, {S} stands for st/nd/rd/th and only in English.

The relevant parts in my current `jp.json`are below, which means Wednesday, 24 July 2019 will look like this: `2019 7月 24 水`.

If possible, I'd like to make it look like this: `2019年 7月 24日 (水)`. Can this be achieved by specifying the `dateFormat` as `"yyyy年 mmmm d日 (DDDD)"`?

```json
{
    "weekDays": ["月", "火", "水", "木", "金", "土", "日"],
    "months": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    "dateFormat": "yyyy mmmm d DDDD"
  }
  
```

**Comment by antoniandre** [comment]
Hi @risafj, Thanks for your interest and contribution!
Yes this is definitely possible to use custom format with different characters as long as they are not in this mapping:

> DDDD stands for the full-letter day of week, mmmm stands for full-letter month, d stands for the date of the month (0-31), yyyy stands for full year, {S} stands for st/nd/rd/th and only in English.

So that `yyyy年 mmmm d日 (DDDD)` will work 🙂

Let me know if Japanese language require more changes.

Also take note that V2 will be out later today! The way to use a locale will change a bit, all explained in the new documentation.

**Comment by risafj** [comment]
Hi @antoniandre , thank you for your prompt response! In that case, is it better if I wait till your release to raise the pull request (the json is ready though)?
Also, great work on your repo and I respect your continuous effort to improve it - vue-cal is a joy to use 😄

**Comment by antoniandre** [comment]
Domo arigato. Thanks for your feedback, I appreciate it.
You can raise the PR anytime it's a breeze to merge and release.

**Comment by risafj** [comment]
Awesome, just raised the PR. Good luck with your V2 release 🚀

**Comment by antoniandre** [comment]
All done, thanks for your contribution. Just changed the locale code to `ja`. (iso 639-1)
Remember to check back for the V2 documentation before upgrading to V2!
Cheers.
