### ISSUE TITLE
emm...If I want to show the designated three days in the week view.But the three days in the different weeks.Cross two weeks.How  can I do this?For help

### ISSUE THREAD

**Issue by shouwangshe** [antoniandre/vue-cal-v4#145]
emm...If I want to show the designated three days in the week view.But the three days in the different weeks.Cross two weeks.How  can I do this?For help.
![image](https://hy-app.oss-cn-shanghai.aliyuncs.com/uploadFiles/newlife-MobilePhoto/525241668828397568/604340554199285760.jpg?Expires=4717727616&OSSAccessKeyId=LTAIiwpphf2oDONT&Signature=a%2Biye5DYIIb6TnJ1GqF9A5pCYPU%3D)
And  I did't found how to custom the part in red block in the picture above, also in the month view the 'weekday-label' content.
Thank you...

**Comment by antoniandre** [comment]
Hi @shouwangshe, I am not sure I understand the question:
Do you want to have 3 days displayed but days from different weeks? 
Like: Fri 26 July, Sat 27 July, Tue 30 July?
If so this is not possible, you can only have days from the same week at a time.

Regarding your second question, it is not possible to customize the weekdays headings neither.
They are displayed as written in the `zh-cn` json file. Why do you want to customize this, is the format incorrect in Chinese?

**Comment by shouwangshe** [comment]
@antoniandre Yes, Maybe 27 July, 28 July, 29 July. They are in turn.But not the same week.  The format is right. Just our design has a little different form the format.

**Comment by antoniandre** [comment]
Hi @shouwangshe,
It is not possible to pick different days from different weeks and put them in one view.
It will still not be possible in the future.
You can only put days of same week at the same time.
