### ISSUE TITLE
Exception at startup when locate='zh-cn'

### ISSUE THREAD

**Issue by louhuaidong** [antoniandre/vue-cal-v4#147]
The exception occurs at this line in vuecal.common.js:
              small: _this.weekDaysShort ? _this.weekDaysShort[i].label : cell.label.substr(0, 3),

I tried remove the weekDaysShort in zh-cn.js just like other langs and the error will go away but the weekDay description is not correct for zh-cn in small/x-small case as per lang character.

vue.esm.js:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'label' of undefined"

found in

---> <WeekdaysHeadings>
       <VuecalHeader>
         <VueCal>
           <ElMain>
             <ElContainer>
               <CalendarComponent> at src\cloudred\Calendar\calendarComp.vue
                 <CalendarPage> at src\cloudred\WebApp\calendarPage.vue
                   <AppMain> at src\views\layout\components\AppMain.vue
                     <Layout> at src\views\layout\Layout.vue
                       <App> at src\App.vue
                         <Root>

vue.esm.js:1897 TypeError: Cannot read property 'label' of undefined
    at vuecal.common.js:5642
    at Array.map (<anonymous>)
    at VueComponent.headings (vuecal.common.js:5634)
    at Watcher.get (vue.esm.js:4482)
    at Watcher.evaluate (vue.esm.js:4587)
    at Proxy.computedGetter (vue.esm.js:4839)
    at Proxy.weekdays_headingsvue_type_template_id_6cf588b7_lang_pug_render (vuecal.common.js:5509)
    at VueComponent.Vue._render (vue.esm.js:3551)
    at VueComponent.updateComponent (vue.esm.js:4069)
    at Watcher.get (vue.esm.js:4482)

**Comment by antoniandre** [comment]
Hi @louhuaidong, 
Thanks for reporting. I can't seem to reproduce this issue, so for next time please put at least your code, and preferably a reproduction link to Codepen or similar.

Anyway I Changed the way this variable is initialized in version 2.1.3 and this should help.
If not please provide some code.

Cheers.

**Comment by louhuaidong** [comment]
Hi @antoniandre ,

The code is just simpley use vue-cal with some parameters.  After some debugging, I found the key trigger of this issue is to set "hide-weekends".  I believe you should be able to reproduce it by set “hide-weekends" and locale="zh-cn".   

My analysis about the root cause: in case of “hide-weekends”， _this.weekDaysShort.length is 5 but the loop is still 7.  So _this.weekDaysShort[5/6].label triggers the exception.  _this.weekDaysShort.length should always be 7 regardless "hide-weekends".

Thanks
Huaidong

**Comment by louhuaidong** [comment]
Forgot the mention that v2.2.0 still has this issue.

**Comment by antoniandre** [comment]
Ok @louhuaidong, I'll have a look and will fix it today or tomorrow.

**Comment by antoniandre** [comment]
Now fixed in version 2.3.0.
