### ISSUE TITLE
All day events not showing up

### ISSUE THREAD

**Issue by bastianjoel** [antoniandre/vue-cal-v4#149]
All day events aren't displayed in the all day section on week and day view when using `show-all-day-events`.

After navigating to the week view via double click on a day cell inside the month view the all day events are also showing up on the week and day views.

Example:
https://codepen.io/bastianjoel/pen/xvRJgX

**Comment by antoniandre** [comment]
Hi @bastianjoel, Thanks for reporting. 
This is now fixed in version 2.1.4.
