### ISSUE TITLE
[Feature request] CSS transitions when switching view

### ISSUE THREAD

**Issue by tarreislam** [antoniandre/vue-cal-v4#15]
Hi, first off, great job with the calendar, just what I was looking for.

Anyway, here is some ideas for features you could add:

* A guide arrow which tells the date and time (MSPAINT concept art: https://i.imgur.com/GmAh2AQ.png)
* Css/Vue transitions when "zooming in" on the calendar.

**Comment by antoniandre** [comment]
Hi @tarreislam,

Happy new year!
Thanks for your great contribution and interest.
I'll merge your changes in shortly.

Regarding the guide arrow feature that's already in my todo list as Highlight current time, and it will look like just the same. I'll do that feature soon as it's fast and easy.

For the second feature you suggest I didn't quite get that, on zooming in?

Thanks

**Comment by tarreislam** [comment]
Hi, happy new year to you too.

Im glad you already have the guide arrow on your todo list. 
Sorry for being unclear with the zoom request. If you visits googles calendar and switch view, the transition betwen the views are smoothen out, thats what i meant.

**Comment by antoniandre** [comment]
It's definitely an improvement that I want to do too. Will come soon.

**Comment by antoniandre** [comment]
Hi @tarreislam,

The current today's time is now marked by a line, check out the **# Today's current time** example.
Hope that's doing what you had in mind too. :)

**Comment by tarreislam** [comment]
Hi @antoniandre, yeah I noticed, its perfect, thanks for the quick release. I'm also thankful for the `vuecal__now-line` helper class which came in handy!

**Comment by antoniandre** [comment]
Hi @tarreislam, 
It took me a while to get to this and sort it out but it is now released :)
As transitions are activated by default you can have a preview on any example in the documentation.
Hope you like it haha.

**Comment by antoniandre** [comment]
Closing the issue as this is now done.
