### ISSUE TITLE
Why is cs locale removed?

### ISSUE THREAD

**Issue by alexnguyen98** [antoniandre/vue-cal-v4#155]
According to the release version 1.59.0 the cs locale is added but currently its not avaibale in the newest release and main github repository.

**Comment by antoniandre** [comment]
Hi @alexxsexotic,
That's right, my mistake. 
I apparently lost this commit in one of the merges from master into the V2 branch back when the V2 was still in development.
Anyway, it is now reintegrated in version 2.3.1 👌
