### ISSUE TITLE
Clicking on month, week or day view and on the navigating arrows reloads the page

### ISSUE THREAD

**Issue by eakenbor** [antoniandre/vue-cal-v4#157]
My vue-cal started behaving strangely today as whenever I click on the month, week or day view and on the view navigation arrows, the page automatically reloads itself and then reverts back to the default view. This is happening in Chrome, Firefox and Edge (the only browsers) I tried it on.
EDIT: Here is the error I get on the console: "TypeError: event.startDate.getTime is not a function"

**Comment by antoniandre** [comment]
Hi @eakenbor,
Can I see your events array? even better if you give me the whole vue-cal markup with options.
It is probably related to the way the start and end of events are defined.

**Comment by eakenbor** [comment]
Hi @antoniandre,
Here is my events array: 
events: [
        {
          start: "2018-11-19 12:00",
          end: "2018-11-19 14:00",
          title: "LUNCH",
          class: "lunch",
          background: true
        },
        {
          start: "2018-11-20 12:00",
          end: "2018-11-20 14:00",
          title: "LUNCH",
          class: "lunch",
          background: true
        }
      ]
Now the error "TypeError: event.startDate.getTime is not a function" has disappeared as it was not related to the problem. The page still reloads on attempting to navigate the views and on clicking on the left and right arrows. There are no errors are the console. This problem started suddenly without any changes made to vue-cal modal or instance.

Here is also the vue-cal modal:

<vue-cal
          class="vue-cal vuecal--rounded-theme vuecal--blue-theme vuecal__event-time vuecal__cell-content"
          small
          selectedDate="2019-07-31"
          default-view="month"
          :disable-views="['years', 'year']"
          :time-step="30"
          :time-from="6 * 60"
          :time-to="18 * 60"
          :events="events"
          :on-event-click="onEventClick"
        ></vue-cal>

**Comment by antoniandre** [comment]
Hi @eakenbor,
Thanks for the array of events, I can see it's not the source of the issue.
We need more of your code to track the problem, please fork and complete this Codepen with your code so I can investigate what's going: https://codepen.io/antoniandre/pen/rPzWOJ

**Comment by eakenbor** [comment]
Hi @antoniandre,
Now I have resolved the issue. It was because the vue-cal was wrapped inside a form hence the constant reloading of the page.  Thanks for your effort.
