### ISSUE TITLE
Time Grid - Allow x-scrolling on day view if too many splits and it won't fit

### ISSUE THREAD

**Issue by NyxCode** [antoniandre/vue-cal-v4#159]
awesome project, great work!
Do you think it's possible to create a time grid similar to this ![image](https://i.imgur.com/22RAef7.png)?  
A problem i encountered while trying to replicate this was that the events take as much width as they can get - Is there an easy way of fixing their width?

**Comment by antoniandre** [comment]
Hi @NyxCode,
Thanks for your feedback :)
I think what you are looking for is to split a day in four, using the `split-days` option.
Have a look here: https://antoniandre.github.io/vue-cal/#ex--splitting-days and let me know.

**Comment by NyxCode** [comment]
Oh, that's exactly what i was looking for! i really don't know how i missed that while reading the doc..
thanks!

**Comment by NyxCode** [comment]
I'm afraid i ran into a problem. the documentation states that 

> On week view you can also overflow your content using a min-width on cells

with 10+ splits, the calendar quickly gets unreadable on mobile devices. Is there a workaround to get `min-cell-width` working in the day view?

**Comment by antoniandre** [comment]
Hi @NyxCode, 
Your request makes sense, I did not foresee one could have enough splits on a day that it would not fit.

I'll redo the implementation to allow that. Will only do it next week though.
In the meantime here is a quick solution using CSS: https://codepen.io/antoniandre/pen/PoYNGmr

**Comment by antoniandre** [comment]
Hi @NyxCode, 
I have released version 2.7.0 to allow horizontal scrolling on day view when there are a lot of splits.
This is possible through the new option `min-split-width`.
Please refer to the example https://antoniandre.github.io/vue-cal/#ex--splitting-days

Hope it helps!
Please close the issue if solved.

**Comment by NyxCode** [comment]
That's awesome, thank you! I really appreciate the effort you put into this!
One thing: would it be possible to have the horizontal scroll bar visible without having to scroll all the way down? Not a huge deal, would be nice though.

**Comment by antoniandre** [comment]
Great, I'm glad it helps. Closing the issue then.
Regarding the scrollbar, I could not find a better way, as the calendar body needs to scroll both ways and overflowing in both directions.

I will keep looking for an improvement for the scrollbar and will release if I find something better.
Cheers!

**Comment by antoniandre** [comment]
PS: @NyxCode, Thanks for supporting the project mate, I appreciate it. :)
