### ISSUE TITLE
Multiple day events are displayed incorrectly if end date is 00:00

### ISSUE THREAD

**Issue by Arminmsg** [antoniandre/vue-cal-v4#160]
Hi thanks for this project, really helped me. 

I'm currently trying to display multiple day events on the week view. But they're not displayed correctly if the events ends at 00:00. 
See:
https://codepen.io/Arminmsg/pen/BXrXLy

My workaround for now is to change the end time from 00:00 to 23:59 the previous day.

**Comment by Arminmsg** [comment]
Saw it's a duplicate of #139

**Comment by antoniandre** [comment]
Hi @Arminmsg, thanks for your feedback.
I was explaining in #139 that the way to tell **vue-cal** to end an event at 00:00 is to explicitly write `24:00`: this is internally converted, with the benefit of staying at the day you want it to end and not start a bit on the next morning.

But I understand the inconvenience so I'll have another look to see if I can handle ending at `00:00` as well.

**Comment by antoniandre** [comment]
It is now possible to end events at `00:00` in version 2.15
