### ISSUE TITLE
Css transition isn't disabled when you switch between weeks and days

### ISSUE THREAD

**Issue by alexnguyen98** [antoniandre/vue-cal-v4#161]
When I change the weeks the transition is off, but when I go to the day tabs the transition is not disabled. ( I needed it to be disabled, because I wanted the title text to be aligned on the left )

**Comment by antoniandre** [comment]
Hi @alexxsexotic, I created a pen with a left aligned title and no transitions: https://codepen.io/antoniandre/pen/NQOwKR

Transitions seem to be disabled everywhere except when changing from or to `years` view. I will have a closer look why soon.
But you should try to add the transitions back, as it displays well on that pen with the custom styles I've put.

**Comment by alexnguyen98** [comment]
Thank you very mucy

**Comment by antoniandre** [comment]
Hi @alexxsexotic, for information I have fixed the year view transition not being disabled.
Now `:transitions="false"` correctly removes all the transitions. (in version 2.13.1)
