### ISSUE TITLE
vue-cal 1.x: Month name and arrow doesn't show up

### ISSUE THREAD

**Issue by yogaprasss** [antoniandre/vue-cal-v4#163]
Hello everyone, I'm new here. I have some issues on month name and arrow to change between months on title bar doesn't show up.

Here is the code
` <vue-cal
        :disable-views="['years', 'year', 'weeks', 'week']"
        :time="false"
        selected-date="2019-09-01"
        xsmall
        click-to-navigate
        default-view="month"
        events-on-month-view="short"/>`

![vue-cal issue](https://user-images.githubusercontent.com/35928103/62918285-64479600-bdc9-11e9-91ef-f611c59bb06b.jpg)

Looking forward for the solution
Thank you!!

**Comment by antoniandre** [comment]
Hi @yogaprasss, the markup is correct.
do you have any JavaScript error?
And more important, do you have vue 2.6+ And latest vue-cal (2.0+)?

**Comment by yogaprasss** [comment]
Hi @antoniandre thank you for your reply
I just found out that my vue version is below 2.6 and my vue-cal version is below 2.0.
Unfortunately, for some reason, I just can't upgrade it to the latest version.
So I decided to make my version of that title bar.
Once again, thank you for your reply and have a good day :)

**Comment by antoniandre** [comment]
Ok good. Remember if you use vue-cal version 1.x you should refer to the v1 documentation (there's a link in the top bar of the v2 documentation)
