### ISSUE TITLE
[Duplicate of #139] Strange behavior with date objects

### ISSUE THREAD

**Issue by eakenbor** [antoniandre/vue-cal-v4#164]
Vue-cal is behaving strangely when fed with the following date objects.

events: [
      {
          startDate: new Date("2019-08-14T22:00:00.000Z"),
          endDate: new Date("2019-09-16T22:00:00.000Z"),
          title: "LUNCH",
          class: "lunch",
          background: true
        }
    ]
Instead of the event covering the entire span on the calendar, it instead covers only a tiny part of the calendar as shown in the first attached picture. However, when the time is changed, say, to 23:00:00 for both start and end, then it appears properly covering the entire span of the calendar. Please can someone explain this weird behavior?

![Vue Cal - events example   fully responsive calendar](https://user-images.githubusercontent.com/30095266/63131401-e13b6100-bfbd-11e9-80f9-ec91d6a1cf83.png)

![Vue Cal - events example   fully responsive calendar (1)](https://user-images.githubusercontent.com/30095266/63131630-b00f6080-bfbe-11e9-97b4-39a7a059996e.png)

**Comment by antoniandre** [comment]
Hi @eakenbor, this is because your event ends exactly at 00:00:00, it will be solved if you set 23:59:59 instead.

See more details in #139.
