### ISSUE TITLE
Hide the time range on multiple day events

### ISSUE THREAD

**Issue by eakenbor** [antoniandre/vue-cal-v4#165]
Hi @antoniandre 
I don't understand how to apply the css to hide the events, as I have tried all ways I could guess but failed. Please take a look at my modal and css and see if you can point out what I am doing wrong.
<vue-cal
          class="event-middle vuecal__event-time, event-end vuecal__event-time"
          small
          default-view="month"
          :disable-views="['years', 'year']"
          :time-step="30"
          :time-from="6 * 60"
          :time-to="18 * 60"
          :events="events"
          :on-event-click="onEventClick"
        ></vue-cal>

//My event

events: [
        {
          startDate: new Date("2019-08-14T23:00:00.000Z"),
          endDate: new Date("2019-09-16T23:00:00.000Z"),
          title: "LUNCH",
          class: "lunch",
          background: true
        }

//My css

.event-middle .vuecal__event-time,
.event-end .vuecal__event-time {
  display: none;
}

Thanks.

_Originally posted by @eakenbor in https://github.com/antoniandre/vue-cal/issues/152#issuecomment-522017979_

**Comment by antoniandre** [comment]
Exactly as I previously wrote it: 
```css
.event-middle .vuecal__event-time, .event-end .vuecal__event-time {display: none;}
```

https://codepen.io/antoniandre/pen/wvwzvQX?editors=0100

Original question: "prevent the time range from displaying on the events in the calendar" (#152)

**Comment by eakenbor** [comment]
Thanks @antoniandre ,
I put my events and your recommended css into the code pen and it worked. However, it still does not work in my template. I don't know if it should be applied differently when using vue-cli like in my case.
//Here is my vue-cal modal I wrapped in a div tag inside my vue template tag. For whatever reasons, github does not allow me add the <vue.cal> open and close tags. So the items below in the triple back ticks are the contents of the vue-cal modal.
´´´
          class="vue-cal event-middle vuecal__event-time event-end vuecal__event-time"
          small
          default-view="month"
          :disable-views="['years', 'year']"
          :time-step="30"
          :time-from="6 * 60"
          :time-to="18 * 60"
          :events="events"
          :on-event-click="onEventClick"
´´´


//My script
´
<script>
import VueCal from "vue-cal";
import "vue-cal/dist/vuecal.css";
export default {
  components: {
    VueCal
  },
data(){
 return {
  events: [
        {
          startDate: new Date("2019-08-14T23:00:00.000Z"),
          endDate: new Date("2019-09-16T23:00:00.000Z"),
          title: "LUNCH",
          background: true
        }
      ]
    }
  }
}
</script>
´


//My css, just exactly like yours 
<style scoped>

.vuecal {
  margin: auto;
  max-width: 1300px;
  max-height: 662px;
  height: 100%;
}
.vuecal__event {
  background-color: rgba(173, 216, 230, 0.5);
}
.event-middle .vuecal__event-time,
.event-end .vuecal__event-time {
  display: none;
}
</style>

Am I putting the classes in the wrong place or something? 
Please can you have a look at my code and see what I did wrong? I will be very grateful if you can edit what I did into the correct thing. Thanks.

For clarity, see attached the screen shots of the modal, the script and the css style:
![screenshot vuecal](https://user-images.githubusercontent.com/30095266/63303765-18bd4c80-c2e1-11e9-8134-04db4fbf1b7f.png)

![screenshot vuecal2](https://user-images.githubusercontent.com/30095266/63303774-1fe45a80-c2e1-11e9-9878-f2bf1057089f.png)
![screenshot vuecal3](https://user-images.githubusercontent.com/30095266/63303777-2541a500-c2e1-11e9-8935-b35f07e2b4b7.png)

**Comment by eakenbor** [comment]
@antoniandre ,

It is pretty clear this works only when vue-cal is imported with CDN and does not work with the Vue CLI. Is this problem what you plan to solve soon?

**Comment by antoniandre** [comment]
@eakenbor, The whole documentation is built on vue-cli. No problem with CSS. This is not a problem that comes from vue-cal.

You can get the source code and run it to see it working. But you have to explore in your code why the CSS does not take effect. The problem probably  comes from the order your CSS are loaded, or from an override somewhere in your CSS.
