### ISSUE TITLE
[Vue warn]: The computed property "locale" is already defined as a prop.

### ISSUE THREAD

**Issue by silencechow** [antoniandre/vue-cal-v4#166]
I am getting this warning when I using vue-i18n packages.
I have set the `props` to `en` but still get the warning and can't change the locale as I want.
```
<vue-cal
    locale="en"
></vue-cal>
```

**Comment by silencechow** [comment]
Sorry.
I found that, I have a global mixin including a computed variable called `locale`

**Comment by antoniandre** [comment]
Just in case others stumble on this (only for Vue 2):

<img width="740" alt="image" src="https://github.com/antoniandre/vue-cal/assets/22971289/cc4c613b-13ff-4cac-b03e-9d843e434a04">

One way to bypass the problem - and keep your variables defined in your mixin, is to prevent this mixin to load on the vue-cal component like this:

```
// First define the global mixin:
const globalMixin = { ... }

// Then only load the global mixin from other components than Vue Cal. 
Vue.mixin({
  created() {
    // Check if the component is not Vue Cal
    if (this.$options.name !== 'vue-cal') {
      // Apply your global mixin
      this.$options.mixins = [globalMixin, ...(this.$options.mixins || [])];
    }
  }
});
```
