### ISSUE TITLE
Trigger "previous" and "next" from another component

### ISSUE THREAD

**Issue by briangsmith42** [antoniandre/vue-cal-v4#167]
Maybe this already exists and I'm just missing it... but it would be great if we could have "prev" and "next" buttons on another component (a toolbar, in our use case) trigger vue-cal to move to the previous or next month or week or whatever. 

I was able to create external view-switching buttons with the switchView() function, just looking for similar capability to externally do prev and next.

**Comment by antoniandre** [comment]
Hi @briangsmith42, 
Yes your right, this was already possible for the view buttons, and now I have added the previous and next buttons in version 2.5.0. Refer to:  https://antoniandre.github.io/vue-cal/#ex--external-controls

Hope it helps.
