### ISSUE TITLE
Bug when displaying event spanning multiple days

### ISSUE THREAD

**Issue by richardkyk** [antoniandre/vue-cal-v4#169]
{
          start: "2019-11-06 09:45",
          end: "2019-11-06 16:05"
        }

If I have an event that crosses multiple days, and is being displayed on the previous month's view it will throw an error: 
`vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'isFirstDay' of undefined
    at fn (vuecal.common.js?7fa7:4699)
    at normalized (vue.runtime.esm.js?2b0e:2590)
    at Proxy.renderSlot (vue.runtime.esm.js?2b0e:2686)
    at fn (vuecal.common.js?7fa7:5879)
    at normalized (vue.runtime.esm.js?2b0e:2590)
    at Proxy.renderSlot (vue.runtime.esm.js?2b0e:2686)
    at Proxy.eventvue_type_template_id_a1c8b120_lang_pug_render (vuecal.common.js?7fa7:5886)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3542)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)`

In my example, the event was at the start of November, so it is also displayed in October's monthly view,  when I first scroll to that month Aug > Sep > Oct (it will throw the error here, and not render the event), if I keep scrolling to Nov, the event will be displayed, and if I scroll back to Oct, the event is now there.

Also, if I navigate directly to Nov (via the Year view) it will render the event in Nov, navigating to Oct will also show the event with no error being thrown.

**Comment by richardkyk** [comment]
After playing around a bit, it seems to have disappeared. I think maybe I had an issue with my code, possibly in regards to the classes for the events.

**Comment by zechariahs** [comment]
> ```
>     {
>       start: "2019-11-06 09:45",
>       end: "2019-11-06 16:05"
>     }
> ```
> 
> If I have an event that crosses multiple days, and is being displayed on the previous month's view it will throw an error:
> `vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'isFirstDay' of undefined at fn (vuecal.common.js?7fa7:4699) at normalized (vue.runtime.esm.js?2b0e:2590) at Proxy.renderSlot (vue.runtime.esm.js?2b0e:2686) at fn (vuecal.common.js?7fa7:5879) at normalized (vue.runtime.esm.js?2b0e:2590) at Proxy.renderSlot (vue.runtime.esm.js?2b0e:2686) at Proxy.eventvue_type_template_id_a1c8b120_lang_pug_render (vuecal.common.js?7fa7:5886) at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3542) at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060) at Watcher.get (vue.runtime.esm.js?2b0e:4473)`
> 
> In my example, the event was at the start of November, so it is also displayed in October's monthly view, when I first scroll to that month Aug > Sep > Oct (it will throw the error here, and not render the event), if I keep scrolling to Nov, the event will be displayed, and if I scroll back to Oct, the event is now there.
> 
> Also, if I navigate directly to Nov (via the Year view) it will render the event in Nov, navigating to Oct will also show the event with no error being thrown.

@richardkyk Any idea how you solved it?  I'm running into the same problem.
