### ISSUE TITLE
Military time format

### ISSUE THREAD

**Issue by tarreislam** [antoniandre/vue-cal-v4#17]
Hello!

The military time format (24 hour time) should always be 4 numbers and zerofilled on the lefthend side https://i.imgur.com/zjz0wHF.png

**8:00** should be **08:00**, **9:00** should be **09:00** and so on

Thanks in advance!

**Comment by antoniandre** [comment]
Hi @tarreislam,

Version 1.14.0 has this fixed. 
I also added a custom `timeFormat` option if you want to override the time format in time cell and events. 
Refer to `timeFormat` in the https://antoniandre.github.io/vue-cal/#api.

I've changed a couple of things, don't forget to always check the release notes at the bottom of documentation.

Hope it solves your issue!

**Comment by tarreislam** [comment]
Hi.

Thanks for the quick response, 1.14 solved my issue, thank you!
