### ISSUE TITLE
Can't seem to listen double click event in touch device / simulated chrome

### ISSUE THREAD

**Issue by dimassrio** [antoniandre/vue-cal-v4#171]
Dear @antoniandre 
Is there anything that I need to setup to make the event trigerred in touch based device? It's working fine on desktop chrome. The code that I've been using is the same in your documentation on event creation.

**Comment by antoniandre** [comment]
Hi @dimassrio, if you are using the same code as https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation > On cell single or double click, a double click should work on both desktop and mobile.

If you are emulating touch from desktop you should reload the page first.

Please try the documentation example itself on your device that you say does not work, then if it does not work on the documentation neither, please tell me the device details.

If it works on the documentation it means something has gone wrong in your code, please share if you need more assistance.

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if not solved.
