### ISSUE TITLE
How to add lib to project?

### ISSUE THREAD

**Issue by freenetwork** [antoniandre/vue-cal-v4#175]
How to add lib to project?
I get error: <vue-cal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

```
<template>
  <vue-cal style="height: 250px"></vue-cal>
</template>

<script>
import VueCal from 'vue-cal'
import 'vue-cal/dist/vuecal.css'

export default {
  components: { vueCal },
  data: () => ({
    //
  }),
  //
}
</script>
```

**Comment by antoniandre** [comment]
Hi @freenetwork, 
You have a letter case mismatch where you import `VueCal` and you use the component `vueCal`

**Comment by freenetwork** [comment]
Friends, on the territory of Russia IQ is blocked, and the platform does not allow to trade. Development got up a long time ago because of this
