### ISSUE TITLE
Date Navigation in Monthview is broken in IE

### ISSUE THREAD

**Issue by jfaquinojr** [antoniandre/vue-cal-v4#176]
1) use IE 11
2) goto sample website
https://antoniandre.github.io/vue-cal/#ex--basic
3) switch to Month view
4) click left or right arrows several times

actual:
![image](https://user-images.githubusercontent.com/8035580/65298880-c00ef700-db9f-11e9-8d3e-7c40a426c5f6.png)

**Comment by antoniandre** [comment]
Hi @jfaquinojr,

The documentation page is tested on IE 11.356 on windows and it works all fine, slow but fine (there are more than 35 instances of vue-cal on that page).

Please clear your browser cache, test the documentation page and if still broken let me know the version and OS.

Also please try to add a polyfill (with webpack or vue-cli) and let me know if it fixes it.

Also you can add a polyfill to your page
Cheers.

**Comment by jfaquinojr** [comment]
After clearing the browser cache, its now working fine.

Thanks for the quick response!
