### ISSUE TITLE
Make now-line reactive

### ISSUE THREAD

**Issue by iamgmd** [antoniandre/vue-cal-v4#177]
Is it possible to make the now-line automatically move with the current time and date? 

I can make it move if I rerender the whole calendar on a timer but it would be nice to have something built in which doesn't effect anything else in the view when changing.

**Comment by antoniandre** [comment]
Hi @iamgmd,
This is is doable and nice to have I agree. I'm adding it to my to do list.
But keep in mind that this has a cost as there will be a `setTimeout` or `setInterval` to check on current date seconds at least every minute.

**Comment by antoniandre** [comment]
Hi @iamgmd, 
I have released this feature in version 2.10.0, 
Please refer to the API section https://antoniandre.github.io/vue-cal/#api, and use the option `watchRealTime` (`watch-real-time` in template).

Let me know if does what you're after. 
Cheers.

**Comment by iamgmd** [comment]
Hi @antoniandre, thanks, this works perfectly as in the timeline does now move in relation to time. 

A small bug I think is that the timeline renders behind an event.

A small change if it can be done, can the component somehow keep track on the current date being rendered and rerender itself when the timeline moves beyond 23:59? This will allow the timeline to be in sync with the current date too, i.e. rerender vuecal__title to show new date, etc. Probably related to other views as well, i.e. week view.

**Comment by antoniandre** [comment]
Hi @iamgmd, I am doing some tests to see if I can have the whole calendar rely on the watched time and change today's date by itself.
this is still not guaranteed by I am making some progress.
Will let you know the outcome.

Also note that the timeline renders behind events intendedly, but you can increase its z-index if you want in your app with `.vuecal__now-line {z-index: 10}`.

**Comment by antoniandre** [comment]
Hi @iamgmd,

I have modified the code to update the entire calendar internal date time in the 1 minute timer.
Now the Today's date will always be accurate if you have watchRealTime option set to true.
If watchRealTime is false, and by default, the internal time gets updated when the cells are redrawn (on view change).

This is now released in version 2.12.2.
Hope it helps.

**Comment by iamgmd** [comment]
@antoniandre Excellent work my friend, I will give it a shot and let you know the outcome.

**Comment by iamgmd** [comment]
I am getting an error:

`TypeError: Cannot read property 'split' of undefined`

I think there is a problem at 7487 vuecal.common.js

`[(hoursStart, minutesStart)] = startTime.split(':');`

My Event collection is read from a database so it will be initially [] but when data is present, it is in the following format that worked with 2.10.2

```
0: {start: "2019-10-15 01:00", end: "2019-10-15 02:00", title: "<i class='fa fa-phone mr-2'></i>Call"}
1: {start: "2019-10-15 02:00", end: "2019-10-15 04:00", title: "<i class='fa fa-phone mr-2'></i>Call"}
2: {start: "2019-10-15 06:00", end: "2019-10-15 06:30", title: "<i class='fa fa-clock mr-2'></i>Task"}
3: {start: "2019-10-15 16:07", end: "2019-10-15 17:07", title: "<i class='fa fa-phone mr-2'></i>Call"}
4: {start: "2019-10-15 16:08", end: "2019-10-15 17:08", title: "<i class='fa fa-phone mr-2'></i>Call"}
5: {start: "2019-10-15 16:09", end: "2019-10-15 17:09", title: "<i class='fa fa-phone mr-2'></i>Call"}
6: {start: "2019-10-15 16:10", end: "2019-10-15 17:10", title: "<i class='fa fa-phone mr-2'></i>Call"}
7: {start: "2019-10-18 01:00", end: "2019-10-18 01:15", title: "<i class='fa fa-users mr-2'></i>Meeting"}
8: {start: "2019-10-24 08:00", end: "2019-10-24 09:00", title: "<i class='fa fa-phone mr-2'></i>Call"}
```

Please advise.

**Comment by antoniandre** [comment]
Oops that's me releasing my code cleanup too quickly. 😅
Now fixed in 2.12.3.

**Comment by iamgmd** [comment]
Yep, all working now... I will test the watchRealTime and let you know the outcome.

**Comment by antoniandre** [comment]
Should be working as expected, so I'm closing the issue. Please reopen if not solved.
