### ISSUE TITLE
Exclusion of some events from the counter on the month view.

### ISSUE THREAD

**Issue by DimaBDV** [antoniandre/vue-cal-v4#18]
Hi @antoniandre 

If i understand you correctly. I create new issue.

Can I hide certain events from the event counter in the month view? (for example, hide the same class - `"hideevent"` )

**Comment by antoniandre** [comment]
Hi @DimaBDV, 

This is now possible to override the month view events count! Check the **_Custom events count on Month view._** of the **# Month view with events indicators** example.

Hope it solves your issue!

**Comment by DimaBDV** [comment]
Thank you @antoniandre  . It solved my issue!

Sorry, amm... how can I filter out some classes?

`return events ? events.filter(e => e.class != 'lunch').length : 0`
i want hide 'lunch', 'class1' , 'class2'

I decided like this. 
`return events ? (
                    events.filter(e => e.class == 'lunch').length || 
                    events.filter(e => e.class == 'sport').length
                    ) : 0  `
Is it possible to make it easier?

**Comment by antoniandre** [comment]
Hi @DimaBDV, 
Glad it solves your issue, I will close it then.

for your question, this is es6 javascript syntax and array functions, you can simplify it like this:

```js
return events ? events.filter(e => e.class === 'lunch' || e.class === 'sport').length : 0
```

or like this:

```js
return events ? events.filter(e => ['lunch', 'sport'].indexOf(e.class) > -1).length : 0
```
