### ISSUE TITLE
Issue with overlapping events

### ISSUE THREAD

**Issue by davidhampson** [antoniandre/vue-cal-v4#180]
Hi, first of all thanks for this great tool! I am experiencing a javascript error in relation to overlapping events, using your example code.

I only get these errors when there are overlapping events. Any help is appreciated!
![image](https://user-images.githubusercontent.com/26553919/65719729-43768f80-e05b-11e9-9e9d-509abcda42bc.png)

**Comment by antoniandre** [comment]
Hi @davidhampson, thanks for the feedback.
Can you share your code and version of vue and vue-cal please?

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if not solved.
