### ISSUE TITLE
v-on:click in slot="arrow-prev" not working in IE

### ISSUE THREAD

**Issue by jfaquinojr** [antoniandre/vue-cal-v4#184]
The following works perfectly fine in chrome but not IE
```html
<div slot="arrow-prev" v-on:click="previous">
    <i class="angle"></i>
</div>
```

**Comment by antoniandre** [comment]
Hi @jfaquinojr, 
Can you share the whole vue-cal snippet please? is it a slot inside vue-cal?
Also what is the version of IE you are testing on?

Can you try this instead and let me know:

```vue
<template v-slot:arrow-prev>
    <div @click="previous">
        <i class="angle"></i>
    </div>
</template>
```

If it doesn't help on IE, please also try `@click.native="previous"` should work without but it's IE so we never know haha.

Cheers.

**Comment by jfaquinojr** [comment]
Hi @antoniandre ,

Here is the complete vue-cal snippet

```html
<vue-cal
    ref="vuecal"
    :selected-date="selectedDate"
    :transitions="false"
    :time="false"
	style="min-height:550px;height:auto !important;"
	default-view="month"
	:disable-views="['years', 'year']"
	events-on-month-view="short"
    :events="calendarItems"
    :on-event-click="onEventClick"
    :show-all-day-events="'short'"
    :hide-title-bar="false"
    :hide-view-selector="false"
    :hide-body="showLoading"
    :min-date="getStartDate()"
    :max-date="getEndDate()"
    >
	<template v-slot:event-renderer="scope" >
	    <div class="vuecal__event-title" data-toggle="tooltip" :title="scope.event.tooltip">
            <div class="inspector-name">{{scope.event.title}}</div>
            <small>{{scope.event.placeOfInspection}}</small>
	    </div>
	</template>
                            
        <div slot="arrow-prev" v-on:click="previous">
            <i class="angle"></i>
        </div>

        <div slot="arrow-next" v-on:click="next">
            <i class="angle"></i>
        </div>
</vue-cal>
```


Your suggestion above didn't work. Also, the `@click.native="previous"` didn't work both on IE as well as Chrome.

For now, my solution isn't pretty - I hid the title bar and draw my own buttons and title.

**Comment by antoniandre** [comment]
Hi @jfaquinojr, 
I tried on IE 11 and it worked. Then I noticed you placed `v-on:click` on the arrows slot which is wrong.
The `previous` and `next` functions are already injected on whatever you put in this slot, this is the purpose of the slot so you can't have another click event within or on it, it's not how it works.

Here is an example of a valid use of the arrows slots:
https://codepen.io/antoniandre/pen/abbVQLy?editors=1010

    <template v-slot:arrow-prev>◀</template>
    <template v-slot:arrow-next>▶</template>

If you want to trigger a custom function on arrow prev and next click, you should call your function from the `view-change` emitted event.

Hope it helps.

**Comment by antoniandre** [comment]
Closed due to inactivity, please reopen if not solved.

**Comment by AhmedNourJamalElDin** [comment]
Hello,

I think due to this restriction we can't add our custom on-click handlng. right?

example:

if mobile, navigate two days by two days by manipulating hideWeekday
