### ISSUE TITLE
Next 7 days View

### ISSUE THREAD

**Issue by keithn** [antoniandre/vue-cal-v4#185]
Rather than a week view, how easy is it to create a "Next 7 days" or "Next X days" view as the thing I'm interested in is things in the future.   

So when it's currently a day late in the week, you can't really see the upcoming events over the next 7 days ( or some other number of days)

Is it possible to customize the component to do this?

**Comment by antoniandre** [comment]
Hi @keithn,
Showing 2 weeks at the same time is not possible within the same **vue-cal** calendar. Only the month view will do what you want and here is how to show events on month view: https://antoniandre.github.io/vue-cal/#ex--events-on-month-view.

However, it is possible to use 2 vue-cal instances to show 2 weeks. So here are 2 other ways: 
- you could have two **vue-cal** instances synced together to show 2 weeks, I created an example for you here: https://codepen.io/antoniandre/pen/MWWbZgK
- alternatively you could also fetch the events of the current week plus one on `view-change` for instance (https://antoniandre.github.io/vue-cal/#ex--emitted-events) and display them outside of **vue-cal**.

Hope it helps.

**Comment by antoniandre** [comment]
Closed for inactivity.
