### ISSUE TITLE
Events from axios not showing

### ISSUE THREAD

**Issue by catmal** [antoniandre/vue-cal-v4#188]
I am fetching from axios a reservations array and pass it to data in the component. I can see the array filled on mutableEvents, but view/events array is empty.
To render the calendar in component I just use:
```
<vue-cal 
    style="height: 500px"
    :events="reservations"
    ></vue-cal>
```
Where should I look to fix it?

**Comment by antoniandre** [comment]
Hi @Catmal,
That's interesting, can you show the format of the events you pass to vue-cal? 
What you have in reservations array might not be formatted like the events `vue-cal` expects: (https://antoniandre.github.io/vue-cal/#ex--events-with-time).

You can console.log the events that **vue-cal** receive on `view-change` for instance (https://antoniandre.github.io/vue-cal/#ex--emitted-events):

```vue
<vue-cal 
    style="height: 500px"
    :events="reservations"
    @view-change="logEvents"
    ></vue-cal>
```

```js
// In your vue component:
methods: {
    logEvents({ events }) {
        console.log(events)
    }
}
```

Also have a look at this example: https://codepen.io/antoniandre/pen/rbpPab?editors=1010

Cheers.

**Comment by catmal** [comment]
If I log events as you suggested I get this. Also by using @view-change I was getting nothing so I used @ready instead.
![Screenshot from 2019-10-21 12-41-49](https://user-images.githubusercontent.com/7369240/67177297-89c3d200-f400-11e9-80ee-f3f3be2ec715.png)


This is data section:
![Screenshot from 2019-10-21 12-55-15](https://user-images.githubusercontent.com/7369240/67177655-1327d400-f402-11e9-84aa-fa3e862ef53a.png)



This is how reservations are formatted. Title and content are strings and start and end are datetime (generated in RoR  with PosgreSQL).
![Screenshot from 2019-10-21 12-47-03](https://user-images.githubusercontent.com/7369240/67177411-fb038500-f400-11e9-9d74-1c1396efa457.png)

This is the whole component:

```
<template>
<div>
    <h1>RESERVATIONS</h1>
    <vue-cal 
    style="height: 500px"
    :events="reservations"
    ></vue-cal>
    </div>
</template>

<script>
import axios from 'axios';
import VueCal from 'vue-cal'
import 'vue-cal/dist/vuecal.css'

export default {
    data() {
        return {
            reservations: [],
        }
    },
    computed: {
       
    },
    methods: {
    },
    async mounted() {
        let response = await axios
       axios
        .get('/reservations.json')
        .then((response) => {
            this.reservations = response.data
        })
    },
    components: {
        VueCal
    }
}
</script>
```

**Comment by antoniandre** [comment]
HI @Catmal, 
I can't find out which is the actual events array of your reservation from your screenshots.
Please just paste here one of the event **as it is passed to vue-cal**.

I am convinced that you don't respect the expected format of the event.
Please read the documentation again and try in this example to put your extracted events.
https://codepen.io/antoniandre/pen/rPzWOJ

**Comment by catmal** [comment]
The problem was indeed the format of start and end fields. Once I changed their format in the json the events showed up. Thanks for the help.

**Comment by antoniandre** [comment]
That's great, all good then!
Glad it's solved.
