### ISSUE TITLE
min-split-width breaks month view

### ISSUE THREAD

**Issue by NyxCode** [antoniandre/vue-cal-v4#189]
When using `min-split-width`, the days in the month-view are too large. I came up with this minimal example:
```
<template>
    <div style="height: 800px; width: 500px;">
        <vue-cal :disable-views="['years', 'year', 'week']"
                 :split-days="[
                    { label: 'a' },
                    { label: 'b' },
                    { label: 'c' },
                    { label: 'd' },
                    { label: 'e' }
                 ]"
                 :min-split-width="200"/>
    </div>
</template>
<script>
    import VueCal from 'vue-cal'
    import 'vue-cal/dist/vuecal.css'

    export default {
        components: {VueCal},
    }
</script>
```
While the day-view works fine, the month view looks like this: ![image](https://i.imgur.com/VzDWgRK.png)  
In the DOM tree, I found this element with `min-width: 7000px`. Removing the `min-width` solves the problem.
![image](https://i.imgur.com/UxSVwEw.png)

**Comment by antoniandre** [comment]
Hi @NyxCode,
I am not sure if this is the same problem in your code and in the isolated example you gave me, but in this code snippets, it seems that **vue-cal** cannot find a default view as the default  view is `week` but you have disabled it. So you need to specify another default view: `default-view="month"`. Here is a Codepen of this working snippet: https://codepen.io/antoniandre/pen/YzzpLyj?editors=1010
Switching to `month` view with a set `min-split-width` seem to work fine as well on the documentation example: https://antoniandre.github.io/vue-cal/#ex--splitting-days

If this does not solve your issue, can you check you have the latest vue-cal?

Also for your information, the `min-width: 7000px` that you can see is calculated dynamically from: `5 splits * 200 min-split-width * 7 days`.

Let me know if adding the default view resolved your issue!

Cheers.

**Comment by NyxCode** [comment]
Hm, no, that doesn't seem to solve the issue. Really strange.
I put together an minimal example [here](https://github.com/NyxCode/vuecal-test). If I run it with `npm run serve`, I get the behaviour I described.

**Comment by antoniandre** [comment]
As I said you are not using the latest vue-cal, you are using v 2.7.0 from your packages.json.
If you go back to this example: https://codepen.io/antoniandre/pen/YzzpLyj?editors=1010 and put the vue-cal 2.7.0 in dependencies you will also get the same issue.

Let me know if not solved after upgrading **vue-cal**.

**Comment by NyxCode** [comment]
now that's embarrassing :man_facepalming: 
thanks & sorry for bothering you

**Comment by antoniandre** [comment]
Haha, no worries mate. glad it's solved.
