### ISSUE TITLE
Year view and timezone

### ISSUE THREAD

**Issue by jacksonsilvadev** [antoniandre/vue-cal-v4#192]
Hey guys, all right?

I have some issues here and haven't found anything in the documentation so far, could you help me?

You would need the year view to look like google:

![image](https://user-images.githubusercontent.com/43053055/67425688-df3de180-f5ae-11e9-8d3d-4f1b45a025a3.png)

What about timezone as I can change the calendar timezone to integrate with google calendar?

**Comment by Mike-Taiki** [comment]
I have the same problem. Someone can help?

**Comment by antoniandre** [comment]
Hi @JackFront and @Mike-Taiki, 
This is 2 features that vue-cal does not do out of the box.

One way to reproduce that view though is to have 12 vue-cal instances one per month.
I have created an example here for you: https://codepen.io/antoniandre/pen/jOOmxzo

The `year` view you can display within a single instance of **Vue Cal** does not include days: you need to click on month to drill down to month view with all the days of the month.

Adding so much details in the year view will double the complexity of rendering nested cells and filtering events and obviously slows down the rendering - as you can see in the codepen I created.

If you need, you could also have a 13th instance of **Vue Cal** that would show you a drilldown view of the date you select. For that you would need to listen for the `cell-focus` event.

Regarding the timezone feature, you will have to handle it from outside **Vue Cal** by just converting event dates to UTC for instance or to one of the timezones you handle.

Hope it helps ;)

**Comment by antoniandre** [comment]
Closed for inactivity.
