### ISSUE TITLE
AllDay event on 27th October causing unresponsive browser

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#194]
Hi,
This calendar is awesome but I came across a very strange issue.

When it tries to load an allDay event with start: "2019-10-27 00:00" and end: "2019-10-28 00:00" the browser's tab becomes unresponsive and its CPU jumps to 100. I thought it could be because 27th is Sunday - the end of the week. But if I change start and end to "2019-10-20 00:00" and "2019-10-21 00:00", it renders fine and the CPU is ok.
In fact I changed start and end to the same event to different dates and the only date that is causing this problem is 27th.

Here is my code to reproduce:

        <div class="calendar-container">
            <vue-cal
                ref="vuecal"
                :events="calendarEvents"
                default-view="month"
                events-on-month-view="short"
                :disable-views="['years', 'year', 'week', 'day']"
                :showAllDayEvents="true"
            >
                <template v-slot:event-renderer="{ event, view }">
                    <div class="vuecal__event">
                        <div class="event-container">
                            <div class="vuecal__event-title" v-html="event.title" />
                        </div>
                        
                    </div>
                </template>
            </vue-cal>
        </div>

       import VueCal from "vue-cal";
       import "vue-cal/dist/vuecal.css";

       export default {
           components: { VueCal },
               data: function() {
                    return {
                        calendarEvents: [
                        {
                            title: "Test",
                            start: "2019-10-27 00:00",
                            end: "2019-10-28 00:00",
                            allDay: true,
                       }
                 ]
            }
        }
    }

I am working on Linux Mint 19.2 Tina with vue 2.6.10 and vue-cal 2.12.3. This happens on both Chrome and Firefox latest versions. I haven't tried other browsers.

Thanks,
Anna

**Comment by kstankov** [comment]
Could it be, because on the 27th, many countries are going from summer DST to winter time?

**Comment by antoniandre** [comment]
Hi @green-pigeon, @kstankov, 

Thanks @green-pigeon for the feedback - and for a clear question with plenty of informations! :) 
I will investigate why it happens on that date in particular, but in any case you should not end an event at `00:00` for Vue Cal you need to use an explicit `24:00` so it does not create another segment on the next day. You can also set time at `23:59` that's fine too.
Here is the discussion about it: #139

**Comment by green-pigeon** [comment]
Hi @antoniandre 

Thanks for your reply.
Actually @kstankov is right and the issue is related to DST changes. 
My time zone is Europe/Sofia and we switch to winter time on 27th October. I changed my time zone to America/New_York and the above event is no more causing problems. I changed start to "2019-11-03 00:00" and end to "2019-11-04 00:00" and tried to load November in the calendar and the browser became unresponsive again.
Changing end to "2019-11-03 23:59" fixes the problem.

Thanks,
Anna

**Comment by antoniandre** [comment]
Hi @green-pigeon, @kstankov,

This Codepen https://codepen.io/antoniandre/pen/QWWgROW?editors=1010, shows that an event on the 27th of October does not cause any problem by itself.
The problem came from an event ending at `00:00` as written in #139.
Please continue reporting problems related to events ending at 00:00 in #139.

Thanks, closing this issue now.
