### ISSUE TITLE
Customizing the end time of a programmatically created event

### ISSUE THREAD

**Issue by Demers94** [antoniandre/vue-cal-v4#199]
On the click of a button, a modal pops up allowing the user to specify the starting and ending time of the event they are creating. However, when I try to programmatically add the event to the calendar, I can't seem to customize the ending time. It will always end 2 hours after the specified starting time

Here is a simplified version of the code I'm using : 

```
this.$refs.vuecal.createEvent(
	  '2019-11-01 10:00',
		{
			end: '2019-11-01 15:00',
			classes: ['availability'],
		}
)
```

The event will be created starting at 10:00 correctly but it will end at 12:00, ignoring the specified datetime in the customization object.

[Here is a Codepen reproducing this "issue"](https://codepen.io/Marxtai/pen/PooEzzy)

Am I using the API wrong? I looked through the code and docs but can't figure out what I'm supposed to do to customize the ending date/time.

Thanks for the help!

**Comment by antoniandre** [comment]
Hi @Demers94,

Thanks for your reproduction link.
The reason why it does not change the end date is that you also have to provide an `endTimeMinutes`. 
I reckon it was not obvious from the documentation so I have updated it: https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation (2nd case).

So in your case, just add the property: `endTimeMinutes: 15 * 60`.

Hope it solves your problem!
Cheers.

**Comment by Demers94** [comment]
Thank you @antoniandre , it is working perfectly!
