### ISSUE TITLE
Multiple-day events crossing daylight saving time crash the browser

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/vue-cal-v4#200]
Not sure exactly what the cause is, but it has something to do with the date range.

**Reproduction:**

* https://jsfiddle.net/wp39kL7u/3/

**Example:**
This works
```js
start: '2019-11-03 10:00',
end: '2019-11-04 14:00'
```
This crashes the browser
```js
start: '2019-11-02 10:00',
end: '2019-11-04 14:00'
```

**Comment by TheJaredWilcurt** [comment]
It seems to be if it crosses 12-1am. and it crosses the end of a week/month

**Comment by Spanching** [comment]
@TheJaredWilcurt  I had the same issue, In my case I think it was about the time change in germany. After splitting my event on 26.10 24:00/27.10 00:00 the issue was gone. 

In your example it crashes on 27.10 too (at least when I tried), so maybe that could be helpful.

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt,
Mmm that's weird. And it does not crash for me - or even slow down - when I try both end dates on your fiddle and go to month view 🤔
But it's been reported before that browser was hanging like in your case: #194.
In that case the event was ending at 00:00 which you should not as per this issue #139. 

I'm keen to find the cause but for now I can't reproduce, so I will leave this open and let's continue tracking this down.

**Comment by TheJaredWilcurt** [comment]
In Firefox it freezes the entire tab. In Chrome it freezes the iframe (in JSFiddle).

I'm in USA Eastern time. Though my team in USA Central time also can reproduce it. Doesn't seem to be OS dependent (happens on Win/Lin/OSX), but perhaps it is the US locale of the system defaulting things in `vue-cal` differently.

**Comment by kstankov** [comment]
I can also confirm that it happened at the local DST change date. In North America DST changed last weekend...

**Comment by TheJaredWilcurt** [comment]
## Cause found

Yep! That's what's causing it to crash (Day Light Savings/DLS). There is an hour of the day that it crashes during.

On March 10, 2019 we skip an hour (2:00 AM - 2:59 AM does not happen, it goes straight from 1:59 AM, then one minute later it is 3:00 AM).

On November 3, 2019 we repeat an hour (2AM-3AM happens, but then we go back to 2AM and repeat the same hour).

This is incredibly stupid and should be banned, but "we live in a society". So.

* * *

## Impact

Interestingly, `vue-cal` has no problem *skipping* the hour (Events crossing March 10th do not crash).

Problem solved! Just handle a special case for this exact hour of dates after `2019-11-02 23:59` and before `2019-11-03 01:00`.

Except... *no*. Because DLS happens on "The first Sunday of November" 🙄 .... but that's only in USA. And only in some cases. 💀 

So you really just need to pull in a library like Moment or something. to detect if a date range passes over the repeated hour for the current user in whatever their timezone/locale is, and if so, *then* fix the bug for that event's date range.

**Comment by kstankov** [comment]
Fix how? Change the end time of the event? In my case it was an event that spanned the DST night, not finishing or ending at the 'extra' hour.

**Comment by TheJaredWilcurt** [comment]
I meant fix internally in `vue-cal`. It's the code that is crashing in this scenario, so it should be detecting the scenario and preventing the crashing.

**Comment by antoniandre** [comment]
I hear you guys - does not seems like an easy fix.
Thanks for your explanation @TheJaredWilcurt and @kstankov, I could reproduce the browser hang in Australia/Melbourne timezone only happening on DLS change, only when turning to winter, and only if it is a multiple-day event.
That's a good step already.
Detecting a timezone change is fairly easy with pure JS, but fixing the code is another story.

I will investigate what causes that in the code and let you know.

**Comment by antoniandre** [comment]
@TheJaredWilcurt, @kstankov,
Good news here, I found the problem and fixed it, I need a couple more tests and cleanup. Will release a patch soon.

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt, @kstankov,
I have released the patch in version 2.13.2, please try to add your breaking event in this codepen https://codepen.io/antoniandre/pen/mddLEeO?editors=1010 and let me know if this is fixed in your timezone too.
(Make sure there is no cache in the codepen hitting the right version of vue-cal@2.13.2)

Thanks!

**Comment by kstankov** [comment]
Thanks a lot, and thanks for this great component!

**Comment by TheJaredWilcurt** [comment]
Yep that seems to have fixed it. Great work!
