### ISSUE TITLE
NPM Install and testing failing with peer dependencies not found

### ISSUE THREAD

**Issue by Twoody** [antoniandre/vue-cal-v4#207]
Looks like the current package is unable to be built. I would make a pull request for this, but I think this falls under "eslint errors" which one of my previous pull requests had been commented as "more work". So, I just have the diff here.

Test plan:
1. For each item in my diff appended to this post, run unix command (or equivalent) `which FOO`. i.e. `which eslint`
2. Remove all the global instances of items (i.e. `rm -rf /usr/local/bin/eslint`)
3. `rm -rf vue-cal/node-modules/
4. `rm -rf vue-cal/package-lock.json`
5. `npm install`
6. `npm run serve`

With out running `npm install --save-dev` on each of the items below in my diff, the package will not build. Thus,
7. Run `npm install --save-dev` on each item
8. `npm install`
9. `npm run serve`

** You might need to delete node_modules and package-lock.json again before step 8.

My Diff:
```
[15:54][tannerleewoody:vue-cal]$ npm -v
6.13.0
[15:55][tannerleewoody:vue-cal]$ gd package.json 
diff --git a/package.json b/package.json
index 637c999..37d81ae 100644
--- a/package.json
+++ b/package.json
@@ -33,10 +33,16 @@
     "@vue/cli-plugin-router": "^4.0.5",
     "@vue/cli-service": "^4.0.5",
     "@vue/eslint-config-standard": "^4.0.0",
+    "babel-eslint": "^10.0.3",
     "core-js": "^3.4.0",
+    "eslint": "^6.6.0",
+    "eslint-loader": "^3.0.2",
+    "eslint-plugin-vue": "^6.0.1",
+    "fibers": "^4.0.2",
     "node-sass": "^4.13.0",
     "pug": "^2.0.4",
     "pug-plain-loader": "^1.0.0",
+    "sass": "^1.23.6",
     "sass-loader": "^8.0.0",
     "simple-syntax-highlighter": "^1.0.6",
     "vue": "^2.6.10",
[15:55][tannerleewoody:vue-cal]$ 
```

**Comment by antoniandre** [comment]
This is not an issue on vue-cal. Let's talk about that through email - will email you later today.

**Comment by Twoody** [comment]
Okay. Thanks Antoni :) I'll be working on another bug that I believe I found too. Hope to have a PR for that over soon.
