### ISSUE TITLE
Multiple-day events /  All Day events

### ISSUE THREAD

**Issue by ArjenSwBase** [antoniandre/vue-cal-v4#21]
I love this calendar. It looks clean and has no dependencies. The one key feature I am missing is Multiple-day events, I've seen that you have this point already on the todo list. What do you think your timeline is for this? I would love to use this in my vue project.

I've tried to implement this myself. But haven't really managed yet.My attempt looked a bit like this [https://puu.sh/Ct1zX/9a54f61f90.png](https://puu.sh/Ct1zX/9a54f61f90.png) (Work in progress) But couldn't get it to work quite nicely with your existing code.

What are your idea's on this? Mine works by just adding "allDay: true" to the event data.

**Comment by antoniandre** [comment]
Hi @ArjenSwBase,

Thank you for your feedback. 
You are right this is in my to do list, I will give it a higher priority if you need it.
But there is quite a bit of work for that (for multiple day events). 
I will create a dedicated branch for that so you can check my progress there.

For now, you can create a full day event setting a start time and end time that fills up your timeline length.

And to pretend multiple day events, you can duplicate an event on multiple days.

PS: Your link is not working I can't check your work.

**Comment by ArjenSwBase** [comment]
Thank you for your reply! I'll keep an eye on it.

Here is the same link fixed:
[https://puu.sh/Ct1zX/9a54f61f90.png](https://puu.sh/Ct1zX/9a54f61f90.png)

**Comment by ArjenSwBase** [comment]
Hi @antoniandre ,

How is it going with this? Have you thought about how to deal with this?
Thanks!

**Comment by antoniandre** [comment]
Hi @ArjenSwBase,

Yes I've been busy lately. I have an idea and will start coding it this week. 😄

**Comment by ryanmkdir** [comment]
I'm also in love with this calendar, great job! This feature would be super helpful to me as well. Thanks for your hard work so far.

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, (& @ryanmkdir),

I have released 1 of your 2 requests: support multiple days.
Please have a look here https://antoniandre.github.io/vue-cal/#ex--multiple-day-events

For the other request I created a separated issue: #40.

This feature, involving a lot of refactoring, is a requirement for the "all day events" bar and it is also unlocking other future features like recurring events.

Hope it helps.
