### ISSUE TITLE
Truncate weekday labels to 2 letters

### ISSUE THREAD

**Issue by ChiefRed** [antoniandre/vue-cal-v4#213]
Hello! Great Component!
But my customer wants to see only two symbols in weekday names. And not first two for some days.

### Is there any way to change / reload i18n texts from parent app?

Then I can pass just two symbols weekdays names inside and all be fine.

**Comment by antoniandre** [comment]
Hi @ChiefRed,
Thanks for the feedback.
Have you seen these options: 
- `small` will show only the first 3 letters of the week days
- `xsmall` will show only the first letter of the week days

If 1 or 3 letters won't match your customer expectancy then you can also use the `weekday-heading` slot, and format up to your needs:

```vue
<vue-cal class="vuecal--blue-theme" hide-weekends="hide-weekends">
    <template v-slot:weekday-heading="{ heading }">{{ heading.label.substring(0, 2) }}</template>
</vue-cal>
```

Here is a demo: https://codepen.io/antoniandre/pen/yLyzGNr?editors=1000

There is also a way to reload the i18n texts, but that's not what you should do. Also the full day should be displayed in single day view for instance.

Hope it helps.

**Comment by ChiefRed** [comment]
Hi @antoniandre,
Thanks for answer!

I have seen that options and know about single day full names usage. But I need only month view.
v-slot:weekday-heading looks better then "clone project and cut jsons", but I steel need inconsecutive symbols and v-slot-way may look more messy then i18n reload I suppose.

So, how to reload?

**Comment by antoniandre** [comment]
Here is how: https://codepen.io/antoniandre/pen/yLyzwPq?editors=1010
But this is still not something you should do, instead you should use the provided custom renderer as per my last message.

It would be less messy and it's the way Vue works to allow customisation of a component.

**Comment by ChiefRed** [comment]
@antoniandre, you was right!

I found the way to use CMS i18n service through v-slot with locale locked on "en" like this:
```vue
<vue-cal locale="en">
    <template v-slot:weekday-heading="{ heading }">{{ getMessage('CT_EVENTS_WEEKDAYS_' + heading.label.toUpperCase()) }}</template>
</vue-cal>
```
Where getMessage is my function interacting with CMS. Same with months.

Thanks for help!
Best regards!
