### ISSUE TITLE
Can't change default start and end dates during event creation

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#216]
Hi. When I click on a calendar cell  - the :on-event-create function is calling and  I receive event as parameter. But I want create event using custom dialog box. In this dialog box I added datepickers and want to change start and end dates , but when I close this dialog, calendar displays this event with old start and end dates. I can't understand why? Of course, I can make additional call to server, and fetch all events, but I think that this is wrong approach. Could you help me please?

**Comment by antoniandre** [comment]
Hi @Iguana59,
I will need your code to help you. 

But just in case this is what you are looking for:
If you try to set the `start` and `end`, or `startDate` and `endDate`, you also need to set the `startTimeMinutes` and `endTimeMinutes` properties.

As per the note written in the "Programmatically & externally" example of the [More advanced event creation](https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation) section:
> Note that you can also override the default end date (2 hours duration), by setting the property end, but for internal Vue Cal calculations you will also need to set the property endTimeMinutes.
E.g. { end: '2018-11-20 14:00', endTimeMinutes: 14 * 60 }.

Cheers.

**Comment by Iguana59** [comment]
Hi @antoniandre. Thank you for quick answer. I already found this note, and as I understood I should calculate startTimeMinutes and endMinutes every time, when I will change start or end dates?

**Comment by antoniandre** [comment]
Yes that's correct. It may become easier later, but for now this is the way to go.
`startTimeMinutes` and `endTimeMinutes` are easy to calculate from a Date: 

```js
event.startTimeMinutes = startDate.getHours() * 60 + startDate.getMinutes()
```

And from a string:
```js
let [hours, minutes] = start.substring(11).split(':')
event.startTimeMinutes = hours * 60 + parseInt(minutes)
```

**Comment by Iguana59** [comment]
Thanks a lot.

**Comment by antoniandre** [comment]
Please close the issue if solved.
