### ISSUE TITLE
Out of scope events are not showing

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#217]
Hi @antoniandre,
I am pretty sure this was working some months ago but now the out of scope events (in the cells before and after the current month) are not showing.
Events-on-month-view is set to "short" but I tried set it to true too.
I'm using vue-cal 2.18.1

Thanks,
Anna

**Comment by antoniandre** [comment]
Hi @green-pigeon, thanks for reporting.
Indeed that's a regression, will let you know when I release a fix.

**Comment by antoniandre** [comment]
Hi @green-pigeon, this is now fixed in version 2.19.1
Demo: https://codepen.io/antoniandre/pen/jJbygw
