### ISSUE TITLE
How to rearrange time cells?

### ISSUE THREAD

**Issue by WisdomSky** [antoniandre/vue-cal-v4#218]
This is a bit related to #195, but mine involves same time of the same day, not time of the next day.

So what I wanted is to start the day with 9:00am and then the 01:00 to 08:00 will be at the end of the day. What I mean is like this:

9:00
10:00
...
21:00
22:00
23:00
00:00
01:00
02:00
...
07:00
08:00

Is this possible with the current APIs?

**Comment by antoniandre** [comment]
Hi @WisdomSky,
This is not possible in a single instance of vue-cal but you could put 2 instances of vue-cal like in this example:
https://codepen.io/antoniandre/pen/KYXjQq?editors=1010

I am not sure putting the morning at the end of the day would be a much intuitive UI though, what is your use case?

**Comment by WisdomSky** [comment]
Hi @antoniandre,

Thanks for the suggestion, but I'm not sure if that works seamlessly specially for scrolling and auto focus/scroll on the current time.

As for the use case, I'm currently developing an app for a client(broadcasting company).

I'm creating a calendar with a timeline of all of their programs, but what they also wanted is that the time should start at 9:00AM at the top and then ends at 8:00AM.

This could make sense for their part as their programs might start in the morning.

**Comment by antoniandre** [comment]
I understand the use case, for that I would use 2 instances and tweak it to what you want.
Please give a try and I will help you if you face difficulties or limitation.

But I will not add a feature to cut the time ranges and reorder them in a near future: a lot of features and rendering depend on the logical order of the time range, like resizing. 

Cheers.

**Comment by antoniandre** [comment]
Closing the issue due to inactivity.
