### ISSUE TITLE
The selected-date prop doesn't apply the CSS class .selected to the date in month view

### ISSUE THREAD

**Issue by Kawemi** [antoniandre/vue-cal-v4#219]
When using the `selected-date` prop, passing a date only selects the date inside the component's JS, and doesn't apply the `.selected` CSS class unless the time of `selected-date` is 00:00:00. I had some issue trying to automatically highlight today's date by default using `selected-date` and only discovered this requirement when I delved into the code base. 

If it's intentional, then it would be nice to document it and if it's not I think it would be a good fix to apply `.selected` disregarding the `selected-date`'s time.

**Comment by Andrdandr** [comment]
Hi guys.
Me too stuck with this problem . 
What i have discovered:
1. https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars is working well.
2. Setting Vue.data.selectedDate by new Date() does not highlights today cell.

I think that is because the time.

**Comment by antoniandre** [comment]
Hi @Kawemi, @Andrdandr,
Thanks for reporting.
If it does not highlight the cell when setting the date through `selected-date` this is unintentional and I will have a look to fix this soon.

Just to better target the problem, are you setting `selected-date` with a Date object or a string with time?

**Comment by antoniandre** [comment]
Actually now that I look into it I remember why I did it this way: You can select a date by user action and that highlights the cell, 
and you can programatically pick a date to view, and that does not highlight the cell because it's not a user action.

The purpose of the `selected-date` is just to navigate to that date automatically.

If that's a problem in your use case, please explain your use case @Kawemi and @Andrdandr so if I understand and can probably add an option. ;)

**Comment by Andrdandr** [comment]
@antoniandre , So i cant understand why in your example here https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars selected date in one calendar highlights cell in second calendar. User action is only for first calendar^ not for second

**Comment by Andrdandr** [comment]
@antoniandre , btw default action for "today" button highlights cell when view is year or years.

**Comment by antoniandre** [comment]
That's right @Andrdandr, there's an inconsistency. 
I will look into that.

**Comment by antoniandre** [comment]
Hi @Kawemi, @Andrdandr,
This should now be fixed in version 2.22.1

Demo: https://codepen.io/antoniandre/pen/jOPOVgm

Let me know if there's still a problem.

**Comment by Kawemi** [comment]
Exactly what I needed. Thanks for the quick fix!

**Comment by antoniandre** [comment]
Great, closing the issue then! 
Please reopen if a problem remains.
