### ISSUE TITLE
cell-click event shows wrong time

### ISSUE THREAD

**Issue by nestormauro** [antoniandre/vue-cal-v4#220]
Hi @antoniandre,
I try to get time when user click on a non-event cell through cell-click event, but, I obtain a time five hours or six hour later. Could you said  me if this time-shift is because time zone or time-from parameter?

**Comment by antoniandre** [comment]
Hi @nestormauro,
If you are clicking on a cell in week and day view it should work as expected. Please give your code if it doesn't.
If you are clicking on a month cell, it does not make much sense to assign a time with hours and minutes, you should cut the time info out of the date you receive and decide to create a full day event or assign an arbitrary time of your choice.
I will probably remove the time information that is returned when you click on a cell in month view.

**Comment by nestormauro** [comment]
When I run example "Communicating with Vue Cal" in Vue Cal documentation. I make click in event "Brunch with Jane" and I get start at "2018-11-21 11:00" in GMT/UTC -5 time zone (my country time zone, see attachment image ID 1) but if I make click in non-event area near to above event (see attachment image ID 2) get date-time response in GMT/UTC +0

I fixed this time-shift using getTimezoneOffset() javascript function but I want know if is a VueCal issue or maybe only is necessary explain this issue in documentation.
![time_issue_vuecal_cell-click](https://user-images.githubusercontent.com/23141981/73031869-52076480-3e0b-11ea-9f13-cd5f46a45971.jpg)

**Comment by antoniandre** [comment]
Hi @nestormauro,
I understand what you mean now, I just checked on the example as you did and have the same behaviour as you point out, but I don't think it matters in the display of the Date object in the logs box: the Date goes through a toString method to display which is not what you get from the returned date.
If you put a console log of the date returned, don't you get the same timezone on both click on your end? I do:

<img width="2147" alt="Screen Shot 2020-02-03 at 4 45 04 pm" src="https://user-images.githubusercontent.com/22971289/73628811-6702b400-46a5-11ea-80d4-002f80a83fbf.png">

So if you get the same timezone returned in the Date object, you can disregard the timezone offset.

The only case I think that could create a different timezone would be if you explicitly set the event start and/or end through a Javascript Date containing a timezone information which is not your timezone when you click.
In this case you should remove the timezone offset like you did.

Hope it helps, let me know.

**Comment by nestormauro** [comment]
Thank you @antoniandre, I wanted to know the origin of this behavior.

**Comment by antoniandre** [comment]
No problem @nestormauro.
In the end I am not sure if you had to use `getTimezoneOffset()` or not, but if you had to because it did not work without for you, then that would be nice if you can just paste the piece of code that did the trick here for the next reader of this issue!
Cheers!

**Comment by nestormauro** [comment]
I share this code if anyone needs to made timezone fix on cell-click event.
`
// Obtain time zone in minutes
var d = new Date();

var tzone_diff = d.getTimezoneOffset();

tzone_diff = tzone_diff * -1;

// Add timezone difference through moment library 

var fix_dtime = moment(sdate, 'YYYY-MM-DD HH:mm:ss').add(tzone_diff, 'minutes').format('YYYY-MM-DD HH:mm:ss');

alert(fix_dtime);

`
I use momentjs (https://momentjs.com/) to easy datetime operations, but you cold use other library.

**Comment by antoniandre** [comment]
Great @nestormauro, thanks for sharing!
Closing the issue now.

Just for information, Vue Cal also has Date formatting and add/subtract days, hours and minutes methods out of the box. 
Check out: https://antoniandre.github.io/vue-cal/#date-prototypes
You may not need an extra library 😄
