### ISSUE TITLE
Week number shown incorectly

### ISSUE THREAD

**Issue by crist1nel93** [antoniandre/vue-cal-v4#223]
This instance occurs when using showWeekOnSunday as true, while in Week view the number of the week on top is off by -1

**Comment by antoniandre** [comment]
Thanks for reporting @crist1nel93, that's a bug. I will release a fix soon.

**Comment by antoniandre** [comment]
Hi @crist1nel93, this is now fixed in version 2.20.1.
Let me know if you notice a remaining problem.
Cheers!
