### ISSUE TITLE
Cannot see cells in week view

### ISSUE THREAD

**Issue by benacler** [antoniandre/vue-cal-v4#225]
I'm not able to see cells in the week view mode, I've tried with the latest version and removing any attributes to vue-cal but no hints. Screenshot shows it. I've inspected the HTML and only the container and the left hours DIV are rendered. Nothing inside , even I can render events successfully.
![Screenshot 2020-02-10 at 13 37 39](https://user-images.githubusercontent.com/10783526/74150666-afbcee80-4c0a-11ea-880e-a09a2d623a4e.png)

**Comment by antoniandre** [comment]
Hi @benacler,

First off, I've noticed you've overridden the noEvent Italian translation through the slot.
As I provided the Italian translation myself - at the beginning of the project - I might have mistranslated some bits.
As you look more Italian than me, I corrected the `noEvent` translation 😅 in version 2.23.1, please let me know if you see other wrong translations in this json:

```json
{
  "weekDays": ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica"],
  "months": ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
  "years": "Anni",
  "year": "Anno",
  "month": "Mese",
  "week": "Settimana",
  "day": "Giorno",
  "today": "Oggi",
  "noEvent": "Nessun evento",
  "allDay": "Tutto giorno",
  "deleteEvent": "Cancellare",
  "createEvent": "Creare un evento",
  "dateFormat": "dddd D MMMM YYYY"
}
```

____

Now regarding the issue at stake, I need to see you code to help you (including the CSS if you have).
Also as a good start, do you see the cells correctly in the documentation and in Codepen examples?
If not what is your browser and OS?

**Comment by benacler** [comment]
Hi Antoni,
Thanks for getting back, I would change the following:

"allDay": "Tutto il giorno",
"deleteEvent": "Cancella",
"createEvent": "Crea evento",

About my issue, yes I can see everything correct in CodePen and in the examples. The weird thing is that there are no cells elements in the DOM in my view. The cal is embedded in a more complex application but if you tell me a way to reach you privately, I can send you a test login/pwd to access the online installation so you can see the whole application and then I can send you further information.
Thanks a lot !

**Comment by antoniandre** [comment]
Hi @benacler, thanks for the translations, I updated them.
For this issue, send me the details via email then, you can find my email in the package.json file.

**Comment by benacler** [comment]
If was our fault, we set the cell width component-wide using this in the CSS:

```
.vuecal__cell { 
  height: 40px; 
  }
```
