### ISSUE TITLE
Weekday headlines doesn't display

### ISSUE THREAD

**Issue by adinai** [antoniandre/vue-cal-v4#227]
Hello, 
I was using this library to create a scheduler, however the weekday headlines doesn't at all. 
I`m using vuejs to achieve this. I would be really appreciated if you could direct me why it happpens. Thank you in advance!
 ` <vue-cal style="height: 80vh"
                     selected-date="2020-02-17"
                     default-view="month"
                     events-on-month-view="short"
                     :events="events"
                     :eventsCountOnYearView="true"
                     :on-event-click="onEventClick"
                     :disable-views="['day', 'years']"
                     @ready="fetchEvents"
                     @view-change="fetchEvents"
                     @cell-dblclick="getClickedCell">
 </vue-cal>`
@antoniandre @cristoper @ionutm87 @benjaminc @dysk0 @devNoiseConsulting 
![dev tool](https://user-images.githubusercontent.com/19287202/74625953-6c75f900-5191-11ea-8139-9a0b37260a8b.PNG)
![weekdays](https://user-images.githubusercontent.com/19287202/74625958-6d0e8f80-5191-11ea-8a03-a503fbe7cdac.PNG)

**Comment by antoniandre** [comment]
Hi @adinai,
Can you see the weekdays headings in this Codepen and in the documentation? 
https://codepen.io/antoniandre/pen/jJbygw

- If yes, which version of Vue Cal and Vue.js are you using? upgrading to the latest will likely fix it.
  By the way Vue Cal needs a version of Vue that is greater than 2.6.1.
- If no which browser and OS are you using?

**Comment by antoniandre** [comment]
Please also provide your full code if not solved (CSS and your javascript functions)!

**Comment by adinai** [comment]
@antoniandre Thank you a lot for your quick response! 
Updating Vue  version solved this problem! :)
