### ISSUE TITLE
Remember the last selected-date in vuex

### ISSUE THREAD

**Issue by kkojot** [antoniandre/vue-cal-v4#229]
Hi,

in my application users often switch between the calendar and other pages, and when they come back to the calendar I want to display them the last selected week.

```
<vue-cal
	default-view="week"
	:disable-views="['years', 'year', 'month']"
	:selected-date="selectedDate"
	@view-change="viewChange($event)"
	@cell-focus="selectedDate = $event"
 ></vue-cal>
 
export default {
  components: { VueCal },
  computed: {
    selectedDate: {
      get() {
        return this.$store.getters["calendar/selectedDate"];
      },
      set(value) {
        this.$store.commit("calendar/setSelectedDate", value);
      }
    }
  },
  methods: {    
    selectToday() {
      this.selectedDate = new Date();
    },
    viewChange(event) {
      if (event.startDate != this.selectedDate) {
	// this cause the infinite loop
         this.selectedDate = event.startDate;
      }
    }
  }
};
```

Changing the `selectedDate` with the `@view-change` event causes the infinite loop. The `@cell-focus` works fine, but this event is only fired when the user clicks the cell, which is not enough for me. 

How can I set the `selectedDate` with the` @view-change` event?

**Comment by antoniandre** [comment]
Hi @kkojot,

I created a working demo of what you want: 
https://codesandbox.io/embed/dreamy-shaw-3yurh?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fviews%2Fcalendar.vue&theme=dark

Hope it helps.

**Comment by kkojot** [comment]
Thanks @antoniandre, your demo works fine. It seems that the problem is somehow related to the nuxtjs. I reproduced the issue here:

https://github.com/kkojot/nuxt-vue-cal

**Comment by antoniandre** [comment]
Please fork the Codesandbox I did for you and add Nuxt, I will have a look there @kkojot.
(I am sorry but I can't clone the repo and install deps on my machine for every issue users create on all my libs. 😅 )

**Comment by kkojot** [comment]
@antoniandre, sure, I didn't know I can run a nuxt application in Codesandbox :) 

https://codesandbox.io/s/eager-bush-97dcz

Please go to the `/pages/calendar.vue` and uncomment the line in the `viewChange()` method. After this, switching to the calendar page will freeze your browser.

**Comment by antoniandre** [comment]
Hi @kkojot,
thanks for the reproduction link.
You end up with an infinite loop, independently of Nuxt or Vue Cal because we rewrite the selectedDate as soon as it loads and so on.

To prevent that, just check the date you saved is different than the one you are going to save.
For that, your store does not change, but in the calendar component's computed this is what should change:

```js
  computed: {
    savedDate () {
      return this.$store.state.calendar.selectedDate
    },
    selectedDate: {
      get () {
        return this.savedDate
      },
      set (date) {
        if (this.savedDate && this.savedDate.getTime() !== date.getTime()) {
          this.$store.commit('calendar/setSelectedDate', date)
        }
      }
    }
  }
```

Then in the template you can do 
```
    @ready="selectedDate = $event.startDate"
    @view-change="selectedDate = $event.startDate"
```

Hope that makes sense, let me know.

**Comment by kkojot** [comment]
@antoniandre, of course, it makes sense ;) As you can see in my first post here I've tried to compare the dates in the `viewChange` method, but I just did it in the wrong way.

Everything works fine now, thank you a lot for your help!
