### ISSUE TITLE
Prevent click-to-navigate for 'out-of-scope' cell option 

### ISSUE THREAD

**Issue by fadziljusri** [antoniandre/vue-cal-v4#23]
Hi @antoniandre ,

Happy new year! Thanks for your great work in this vue-cal, really loved it!

Regarding this matter, I've trying to display specific month only in the calendar, able to prevent the `arrowPrev` and `arrowNext` from clicked but `out-of-scope` cell is still able to be clicked thus change the month of the calendar

**Comment by fadziljusri** [comment]
> Hi @antoniandre ,
> 
> Happy new year! Thanks for your great work in this vue-cal, really loved it!
> 
> Regarding this matter, I've trying to display specific month only in the calendar, able to prevent the `arrowPrev` and `arrowNext` from clicked but `out-of-scope` cell is still able to be clicked thus change the month of the calendar

Hi, I solved it using jquery. I've read your code (https://github.com/antoniandre/vue-cal/blob/master/src/components/vue-cal/cell.vue#L14) and realized that u are using `touchstart` instead of `click` event lol. ^_^

My solution:
```js
 $(document).ready(() => {
      let $outOfScopeCell = $(".vuecal__cell.out-of-scope");

      $outOfScopeCell.on("touchstart", function(e) {
        e.preventDefault();
      });
 });
```

**Comment by antoniandre** [comment]
Happy new year @fadziljusri!
I understand the issue here and awesome that you could find a way out.
vue-cal will become more and more flexible in the future, allowing to implement custom behaviors easily.
Cheers!
