### ISSUE TITLE
Bug with special hours when show-all-day-events is enabled

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#230]
Hi @antoniandre 
Special hours are great but there is a bug when show-all-day-events is set to true. Then a second colored area appears fixed at the bottom of the calendar. This is a link to a codepen project that reprodices the issue: https://codepen.io/green-pigeon/pen/KKwrGLa

**Comment by antoniandre** [comment]
@green-pigeon,
That's right, I have to disable it from the all-day bar.
Thanks for reporting!

**Comment by antoniandre** [comment]
Fixed in version 2.24.3.
(Also realigned the all-day cell right border with the time cells).
