### ISSUE TITLE
Clicking on event emits @cell-click but without Date object; @event-focus emitting twice

### ISSUE THREAD

**Issue by risafj** [antoniandre/vue-cal-v4#232]
Hi @antoniandre , I recently updated vue-cal from version 1 to 2 in my project, and I have a few questions/issues.

__1) `@cell-click` inside events__
In v1, I recall that `@cell-click` was emitted with a JS Date object when you clicked inside a cell, regardless of whether it was inside a calendar event or not (my app depended on this).

> cell-click - returns a JS native Date object

Now, clicking inside an event seems to be emitting `@cell-click` but with no Date object inside. Is this expected behaviour/documented somewhere?
I found the below on event creation, but I couldn't find anything on this particular behaviour of `@cell-click`:
> Event creation will not trigger with a single/double click or click & hold **if your cursor is on an event**.

__2) `@event-focus` firing twice?__
I noticed that clicking on an event seemed to be firing off `@event-focus` twice. This was the case for both my app and the demo in the docs. Is this to be expected?
https://antoniandre.github.io/vue-cal/#ex--emitted-events

<img width="874" alt="Screen Shot 2020-02-25 at 16 58 04" src="https://user-images.githubusercontent.com/43341670/75227113-edb43800-57f0-11ea-81d6-7af6e52c3c05.png">
(The screenshot above is from clicking on an event once)

Thank you for your time in advance!

**Comment by antoniandre** [comment]
Hi @risafj,
You are right, that's a regressions that I haven't noticed and you're the first to report it.
I will release a patch for that soon.
Thanks for reporting!

**Comment by antoniandre** [comment]
Fixed in version 2.24.4, visible in the documentation.
Thanks for reporting again, let me know if it fixes the issue!

**Comment by risafj** [comment]
@antoniandre Oh wow! Amazed that you released a patch so quickly. Thank you! 👏 
I'll test it out and let you know if I notice anything else.

**Comment by risafj** [comment]
@antoniandre Just upgraded to `2.24.4` and tested it in my app, and everything seems to be working. Thank you so much again!

**Comment by antoniandre** [comment]
Awesome, 2 less bugs in the wild!
