### ISSUE TITLE
v-model for events

### ISSUE THREAD

**Issue by imers** [antoniandre/vue-cal-v4#234]
How to get the changed events from vue-cal? Is there a v-model for that?

**Comment by antoniandre** [comment]
Hi @imers,
You have to listen to the appropriate event: https://antoniandre.github.io/vue-cal/#ex--emitted-events.
You should use `event-change` like `@event-change="eventChange"`.
The `eventChange` method will receive the newly modified event.

You might want to have a look at this typical example as well: how to fetch events from a back end https://codepen.io/antoniandre/pen/rbpPab?editors=1010.

**Comment by imers** [comment]
Got it. Thanks!!!

**Comment by antoniandre** [comment]
Cheers, closing the issue then!
