### ISSUE TITLE
unable to display custom event slot

### ISSUE THREAD

**Issue by peachykeeen** [antoniandre/vue-cal-v4#238]
Hi,
nice job on the calendar and the documentation. I have set up everything I needed in no time! There is just one thing that I just cant figure out how to do - I can't figure out how to render my own html in inside an event (and access the event's object properties). It seems to me it is possible from the documentation, but I guess I am doing something wrong...

I am using the "3.0.0-alpha.4".
```
<vue-cal default-view="day"
         id="vuecal"
         @ready="scrollToEarliestTimeslot"
         :selected-date="selectedDate"
         :events="calendarEvents"
         :timeCellHeight="timeCellHeight"
         :time-step="minTimeslotLength"
         hide-title-bar
         :split-days="calendarResourceObjects"
         :on-event-click="onTimeslotSelect">
  <template v-slot:event="{ event, view }">
    zaza
    {{ event }}
  </template>
</vue-cal>
```

Neither 'zaza' or event are rendered in the day view (or any other view), and the event or view variables are not available inside the template component. It just renders the events as if the template wasnt even there.

![Screenshot from 2020-03-07 14-32-30](https://user-images.githubusercontent.com/13189452/76144440-c1b27580-6080-11ea-9cf0-3746aa290e98.png)

I have tried v-slot:event and v-slot:event-renderer, but no luck.

**Comment by peachykeeen** [comment]
aaaaand I figured it out thanks to writing this issue :). I was using an old version of vue, so the scope syntax didn't work. after upgrading it works perfectly...

**Comment by antoniandre** [comment]
Hi @peachykeeen,
Sorry I missed your question. 
Yes at the moment the documentation is up to date with the alpha version which should be released as stable soon. So this is temporary and should not last too long.

Anyway, I'm glad you found out it was a Vue version mismatch.
