### ISSUE TITLE
editable-events without inline title editing?

### ISSUE THREAD

**Issue by fvaasen** [antoniandre/vue-cal-v4#239]
Hi, 

is there a way to have have drag and drop + resizing active, but disable the title editing?

Thanks!

**Comment by antoniandre** [comment]
Hi @fvaasen,
Not at the moment. But I will add a way to allow that in the V3.
will let you know.

**Comment by antoniandre** [comment]
Hi @fvaasen,
This is now an option in the V3, you can test it with `npm i --S vue-cal@alpha`.
And it should be released stable at the end of the week.

Refer to the updated `editableEvents` from the API section: https://antoniandre.github.io/vue-cal/#api
