### ISSUE TITLE
Dropping an event automatically narrows the view from month to week

### ISSUE THREAD

**Issue by max888** [antoniandre/vue-cal-v4#240]
Hello @antoniandre 

I have 2 available views on my `vue-cal` instance - 'month' and 'week' view.

When I drag and drop an event while in month view it automatically narrows the view to 'week'.

Is there a way to prevent this and keep the calendar in month view while drag and dropping events?

I noticed for the `@on-event-click` listener it is possible to use `e.stopPropagation()`. Would it be something similar for `@event-drop`

Many thanks in advance and apologies if it's already possible!

**Comment by antoniandre** [comment]
Hi @max888, 
Actually it depends what you are talking about precisely: in the early version of the new alpha, once you drop an event in month view it would still take you to week view after drop.
I have corrected that in a later version of the alpha, so when you drop it will not navigate. But if you hold the event over the cell for long enough it will still navigate, which I believe is an intuitive UI. 
You might want to drop the event precisely on a timeline?

let me know what is your scenario, I will see if we can do something.

**Comment by max888** [comment]
Hi @antoniandre thank you for such a fast response. Yes you're correct, I was using `3.0.0-alpha.3` which was using the old behaviour. I have upgraded to `3.0.0-alpha.5` and it is as you described, it doesn't navigate unless you hold the hover for some time.

This is exactly how I imagined it should work, super intuitive!

Thanks again for such a great calendar.
