### ISSUE TITLE
Splitting days & split events - How split new created event (change css class)

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#244]
Hello. I used the Splitting days & split events functionality - it works well when I loaded events from server. But when I create new event, the color of event is default color (gray)  (On create modal popup I have some selector, that contains event types - for example, with names box1 and box2), I want that in real time when I select event type, the color of event would change according appropriate css property (Of cause, I have handler that fires on on-change selector event and I set to current selectedEvent.class)  For example, in css I have next properties: 
.vuecal__event._1 {background-color: rgba(253, 156, 66, 0.9);border: 1px solid rgb(233, 136, 46);color: #fff;} 
  .vuecal__event._2 {background-color: rgba(164, 230, 210, 0.9);border: 1px solid rgb(144, 210, 190);}
And when I set box1 from event type selector, I respectively set selectedEvent.class = "_1", when box2 - selectedEvent.class = "_2". When I reload page - the event that I just saved is drawn with the correct color. Do you have ideas how I can change the color of saved event in real time OR maybe some method that I can use to "refresh" calendar, but without making request to server. Thanks.

**Comment by antoniandre** [comment]
Hi @Iguana59,
Have you looked at this example: https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation? In the 3rd section (Adding a dialog box to the default cell click & hold behavior), a dialog box changes the class and it's reflected straight away. 

- If that's what you want you can use the event class property from Vue Cal 3.0.0.
If you are using another version, you have to provide an array of classes, and the property is called `classes` not class.
The documentation is up to date with the V3, which will be released end of the week.
Refer to #233 

- If it's not what you're talking about, please share your code that will be simpler for me to help you from there.

**Comment by Iguana59** [comment]
@antoniandre Thanks a lot. this is exactly what i need. I had a previous version that did not support this
