### ISSUE TITLE
Background events with no date, only time

### ISSUE THREAD

**Issue by koas** [antoniandre/vue-cal-v4#246]
Hi Antoni, I'm amazed at how good this calendar is, so first of all congratulations for such a great job!! 

I'd like to request a feature: sometimes the background events (for example, lunch) repeat everyday, so it would be nice to have a way to add them to the event list with just the time interval and an extra `everyday` parameter to tell VueCal that this event repeats everyday:

```
data: () => ({
  events: [
    {
      start: '12:00',
      end: '14:00',
      title: 'LUNCH',
      class: 'lunch',
      background: true,
      everyday: true
    },
    ...
  ]
})
```

Thanks for creating this amazing component!

**Comment by antoniandre** [comment]
Hi @koas, 
Thanks for your feedback, I appreciate it :)
Regarding your feature request, this is already in the scope and started #55 but paused for the moment.
The documentation presents the API already: https://antoniandre.github.io/vue-cal/#ex--recurring-events

Please follow the conversation in #55!

BTW, in your case you may find this useful in the meantime: https://antoniandre.github.io/vue-cal/#ex--special-hours
