### ISSUE TITLE
Draggable event & external event change not working

### ISSUE THREAD

**Issue by pzeinlinger** [antoniandre/vue-cal-v4#247]
Hey @antoniandre 
I've just come across the following issue:  
When I load new events from an API on view-change and want to drop in an event from the old date range (e.g. change weeks by dragging the event on one of the change arrows), I get "Cannot read property 'allDay' of undefined". I guess vuecal is trying to access the appointment with the corresponding _eid, but since there was a change of events, it's not there anymore.
Any ideas on how to fix that? I'm happy to help!

![2020-03-18-19-50-02](https://user-images.githubusercontent.com/26354635/76996525-f6acab00-6951-11ea-8a00-51d7c6d6e049.gif)

Paul

**Comment by antoniandre** [comment]
Hi @pzeinlinger,
Thanks for your PR, I replied in it. 
Can you tell me what is the browser, OS and version of Vue.js and if you're using other framework like Nuxt please?

**Comment by pzeinlinger** [comment]
I tested it with Firefox 73.0.1 on Arch Linux (64-bit) and with Chromium 80.0.3987.122 (Official Build) using Nuxt.
