### ISSUE TITLE
Handle resize change

### ISSUE THREAD

**Issue by AndriyYushko** [antoniandre/vue-cal-v4#249]
I need handle change resize end date value, because I want that when resize event next event not move right side, I wount that next event became smaller and smaller and then disappeared altogether as soon as its end date matched the end date of the next event.
How can I do that?

**Comment by antoniandre** [comment]
Hi @AndriyYushko,

I am not sure I fully understand what you want, but I guess this will help you:

From this example https://antoniandre.github.io/vue-cal/#ex--emitted-events, clear the log box, then resize an event. You will see the returned information in the log box on `event-duration-change`. It has the final event and the old end date. You can use that new endDate inside the event if you want.

Let me know if you need more assistance.

**Comment by AndriyYushko** [comment]
Hi @antoniandre thank you for answer.
I saw ` event-duration-change` it call at the end of resize, but I need triger move mouse down and get new time on move

**Comment by antoniandre** [comment]
If you need a callback firing multiple times while you are resizing, what is the purpose?
And please share your code so I can help.

**Comment by AndriyYushko** [comment]
@antoniandre Purpose possibillity customize resize method. For example your resize method move next event in rigth side 
![image](https://user-images.githubusercontent.com/35810665/77739799-d39d8d80-701a-11ea-928d-699feaadaeb1.png)
, but I need that when event end time >= next event start time substract time start time from next event and add that substracted time to first event. So next will not move in the right but become smaller and smaller. Finally when event end time will equal end time of next event, next event will removed.
My code:
```
onResize(event, nextEvent) {
      if (event.end >= nextEvent.start) {
        nextEvent.start = event.end;
        if (event.end === nextEvent.end) {
         for (let i = 0; i < this.events.length; i++) {
           if (this.events[i].id === nextEvent.id) {
             this.events.splice(i, 1);
           }
         }
        }
      }
    },
```
Finally events should looks like this:
![image](https://user-images.githubusercontent.com/35810665/77739972-1ceddd00-701b-11ea-84c3-9ecab6229761.png)

**Comment by AndriyYushko** [comment]
@antoniandre I think can add `this.$emit('event-resize', { event: cleanEvent, oldDate: resizeAnEvent.originalEndDate })` in `onMouseMove` method.
And it will be enough

**Comment by antoniandre** [comment]
@AndriyYushko, I understand. 
I am not sure it's logical behavior, but I will fire this event from `onMouseMove` in the next release.
Will let you know when ready.

**Comment by AndriyYushko** [comment]
@antoniandre Thank you

**Comment by antoniandre** [comment]
Hi @AndriyYushko, 
In version 3.1, the `event-resizing` event is now emitted while resizing.
Refer to https://antoniandre.github.io/vue-cal/#ex--emitted-events

Hope it helps.
