### ISSUE TITLE
Highlight Today's current time visible in Month view

### ISSUE THREAD

**Issue by cristoper** [antoniandre/vue-cal-v4#25]
It looks like ever since the highlight today's current time feature was implemented in 1.16, the highlight line is also shown on the Month view, but I believe it should only be visible in the Week and Day views. In Firefox (60.3) this causes the view to be too tall and becomes vertically scrollable.

This issue is reproduced for me (again Firefox 60.3) in the demo here: https://unpkg.com/vue-cal@1.17.0/dist/demo.html

**Comment by antoniandre** [comment]
@cristoper, hahaha you are right let me have a look!

**Comment by antoniandre** [comment]
Hi @cristoper, 
This should be fixed - apart from the demo inside the dist/ folder which still acts weird.
Let me know if that fixes the issue.

**Comment by cristoper** [comment]
Looks good, thanks for fixing that so quickly!
