### ISSUE TITLE
Wrong date on cell clicked on month view

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#250]
Hi, @antoniandre 
I started seeing this bug since version 2.24.3, now I'm using 3.0.0. It is very inconsistent but very unpleasant because I'm showing a sidebar with events on cell clicked.
I started to get wrong date for the first half of the next month. E.g. I click on 04 April, the date I receive on cell-clicked is "2020-04-03T22:54:00.000Z".
I guessed as it's in UTC I have to convert it to local time (timezone +2). This seemed to fix it but now there is a problem with the second half of the month. 23 March is clicked, the received date is "2020-03-24T08:31:00.000Z".
As I said it is inconsistent, so I can't show you how to reproduce but do you have any idea what could be causing it?

Thanks,
Anna

**Comment by green-pigeon** [comment]
This also happens when I click on allDay bar cells. I click on 26 March, I get "2020-03-25T21:43:00.000Z"

**Comment by antoniandre** [comment]
Yes this is due to the timezone, but it should be ok when you look inside the Date object that Vue Cal returns, no? The printed date can appear differently.

Please see this issue #220

**Comment by antoniandre** [comment]
If you need more assistance, please give me a Codepen link of the isolated issue.

**Comment by antoniandre** [comment]
Please let me know if this is solved @green-pigeon.

**Comment by antoniandre** [comment]
You can also close your issues @green-pigeon, like others do.

**Comment by green-pigeon** [comment]
I fixed this in my code by adding a div in the cell-content slot with click event that sends cell.startDate to my handler. I don't know how you generate the random hour on cell click in month view and why you're not sending cell.startDate too?

I can't give you a codepen link because as I said it is very inconsistent an finally it was happening on one of our dev machines only.
