### ISSUE TITLE
Settings MinSplitWidth without defining splitDays causing header to collapse

### ISSUE THREAD

**Issue by Duncank** [antoniandre/vue-cal-v4#251]
I'm using a Vue Cal instance with remote data for different purposes, and sometimes I want to show split days. That's why I've set the `minSplitWidth` option to `150`.  
While that works great if there are `splitDays` configured, it breaks the day-headers and all day events-bar, by displaying them as columns instead of a row in css.

See [this JSFiddle](https://jsfiddle.net/Duncankrebbers/ev4abjfm/4/), which contains the same calendar twice. The bottom one has minSplitWidth set, the top one does not.

**Comment by antoniandre** [comment]
Hi @Duncank,
Thanks for reporting and taking the time to analyse and giving a reproduction link.
This is all very helpful! 👍 
I obviously forget some scenarii sometimes with all the options in Vue Cal.
Will fix this soon.

**Comment by Duncank** [comment]
Great! Thanks for your feedback; we're only just getting started with Vue Cal and are really amazed by all the possibilities. We're very happy to help ironing these things out!

**Comment by antoniandre** [comment]
Hi @Duncank,
This is now fixed in version 3.0.2.
But at the moment there is an incompatibility with the all day bar and the `minSplitWidth` when `splitDays` are set.

If you need that too, please open a new issue!
