### ISSUE TITLE
cellWidth of allDayEvents is incorrect with hiddenWeekdays

### ISSUE THREAD

**Issue by Duncank** [antoniandre/vue-cal-v4#253]
Regular calendar cells get a new width assigned via the cellWidth if weekdays are hidden, but that does not apply to cells in the allDayEvents-header. They are always 14% wide; making room for seven cells in the week view.

[JSFiddle](https://jsfiddle.net/Duncankrebbers/tqocu5hf/2/)

**Comment by antoniandre** [comment]
Hi @Duncank, thanks for reporting, I omitted that.
Fixed in version 3.0.1
