### ISSUE TITLE
Invalid prop: type check failed for prop "cellWidth".

### ISSUE THREAD

**Issue by jpkontreras** [antoniandre/vue-cal-v4#255]
This happened to our team when we were trying our app in IE11 

<img width="751" alt="Captura de Pantalla 2020-03-26 a la(s) 19 28 20" src="https://user-images.githubusercontent.com/7862089/77702769-018dbe00-6f98-11ea-9cd6-db41474b736e.png">
This error logs 25 times
<img width="95" alt="Captura de Pantalla 2020-03-26 a la(s) 19 29 08" src="https://user-images.githubusercontent.com/7862089/77702853-2d10a880-6f98-11ea-9cb0-65a479ea8da6.png">

view.blade.php

We use inline template components for rendering 

```
<calendar-page inline-template>
      <vue-cal
        ref="calendar_ref"
        v-bind="calendar"
        :events="events"
        :on-event-click="onEventClick"
        @view-change="handleViewChange">
        <div slot="no-event">Sin horas</div>
      </vue-cal>
</app>

```

data: {}
```
calendar: {
   timeFrom: 6 * 60,
   timeTo: 16 * 60,
   timeStep: 30,
   class: "mb-2",
   locale: "es",
   hideWeekends: false,
   disableViews: ['month', 'years', 'year'],
   eventsCountOnYearView: "events-count-on-year-view",
   eventsOnMonthView: "short",
   dblclickToNavigate: false,
      }
```

**Comment by antoniandre** [comment]
Hi @jpkontreras,

- Which version of Vue Cal and Vue.js is it? 
- Is it happening only on IE11? 
- Do you use Nuxt?

In the latest code it accepts a number and boolean it's weird if that happens.

**Comment by antoniandre** [comment]
I released 3.0.1 for a related fix, can you please check if it is still happening? thanks.

**Comment by jpkontreras** [comment]
yesterday i was using 3.0.0
updated to 3.0.1 and error persisted
Only happening in ie11. Tested in webkit browsers and gecko browsers
Not using Nuxt

**Comment by Twoody** [comment]
@jpkontreras  Any followups on this? Did you discover why?

**Comment by Csandori** [comment]
Hello @jpkontreras!

I tried to recreate your problem, but couldn't. Can you provide us a jsfiddle or codepen example?

Thanks!

**Comment by antoniandre** [comment]
Thanks @Csandori for trying to reproduce the issue.
I'll close this then if you can't.
If the problem persists, please reopen giving a reproduction link.
