### ISSUE TITLE
Is vue-cal hardcoded to expect 'start' and 'end' properties on an event object?

### ISSUE THREAD

**Issue by milost1982** [antoniandre/vue-cal-v4#256]
It seems that binding 'events' prop to an array of objects that represent events, vue-cal is hardcoded to use 'start' and 'end' properties to get date and time of the start. 

Is it possible to instruct vue-cal to use some other properties for this? For example in my objects I have "from" and "to" that indicate when the event starts and ends, so I'd like to use these instead of default 'start' and 'end'.

**Comment by UnKnoWn-Consortium** [comment]
I think it can be done with two props (say `event-start-prop` and `event-end-prop`) that dictate which two properties are used for the start and the end in an event object.

**Comment by antoniandre** [comment]
Hi @milost1982,

The expected event start and end props are named `start` and `end` (`startDate` and `endDate` will be merged into `start` and `end` in the next release).

Sorry but complexity should not be added in the codebase to accomodate passing a different field name. Vue Cal could not do that on all the props and stay lean and performant.

Now the codebase is big enough to worry adding only features that are useful and satisfy most scenarii.
