### ISSUE TITLE
[Feature Request] Add a prop that two-way binds to the currently active calendar view

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [antoniandre/vue-cal-v4#257]
I understand there are two events (`ready` and `view-change`) that are emitted with the active calendar view and a function `switchView` exposed as component instance method for changing view outside of the `vue-cal` component. 

I just wonder why dun we also add a prop (say `activeView`) with two-way binding capability.  It is more straightforward and imho more conventional too.

**Comment by antoniandre** [comment]
Hi @UnKnoWn-Consortium,
Thanks for your PR, your request makes sense and I agree with you, just didn't think about it when I added external access to switchView.
I will merge your PR after I release the v3.1 as I pre-announced the startDate and endDate will be merged into start and end.

**Comment by antoniandre** [comment]
Hi @UnKnoWn-Consortium, this is now released in version 3.2.
I will probably do the same with the selected date soon.

Refer to https://antoniandre.github.io/vue-cal/#ex--external-controls
