### ISSUE TITLE
Wrong start date in week view when dragging events from month view

### ISSUE THREAD

**Issue by pedroprieto** [antoniandre/vue-cal-v4#261]
Hi @antoniandre ,

I've detected a bug. I have submitted a pull request to address it.

Bug description:
1. Drag an event from any view (i.e. week)
2. Drag it to month view
3. Drag the event over a day different than monday
4. Calendar switches to week view with the selected day on monday (wrong).

Glad to help!!

**Comment by antoniandre** [comment]
Thanks @pedroprieto for reporting and fixing that! 
Awesome, I'll merge in soon.
