### ISSUE TITLE
Hide the 6th (week) row on month view if days are out of month scope

### ISSUE THREAD

**Issue by mikeladon** [antoniandre/vue-cal-v4#267]
Hi there!

We have a view-change event here which is working just great, but I was wondering whether it's possible to interact with the data after the view has been changed?

For instance, in the month view I need to show only the first 5 rows; I'm basically collecting all the cells and checking whether the index of the current cell is more than 35 and if so, I want to hide it. The problem is when I'm executing the following code on the change-view event, it picks up the wrong data ( from the previous month), hence showing me the incorrect data next month.

Is there any other way to do it?

Thanks for your great job, btw!

**Comment by antoniandre** [comment]
Hi @MikhailLadonkin,
Thanks for the feedback.

I am not sure what you want to do, but if you try to hide the 6th row, which is the 6th showing week of the month view, this is not meant to be hidden as in some months there are days of the same month showing there (E.g. August 2021).

If you still want to hide them, you will have months with 5 rows and sometimes 6 rows which creates a misalignment of the cells when you change the month.

If you still want to hide them, please share your code so I can help.
Cheers.

**Comment by mikeladon** [comment]
@antoniandre Thanks for your reply!

What I want to do:

I need to hide the 6th row unless it has some 'this-month' days, like the 31st or etc. 

So if I don't have any days of this month on the 6th row, I want to hide this row, but if I have some, I want to show it (basically just scroll down to this line so that the size is not changed, but it's not the point here)

Is there any way to do that?

So far I have the following method

```
changeMonthsView() {
                let monthCells = [];
                let monthBlocks = document.querySelectorAll('.calendar-full.vuecal--month-view .month-view>.vuecal__flex>.vuecal__cell');
                monthBlocks.forEach(function (cell) {
                    monthCells.push(cell)
                });
                monthCells.forEach(function (cell) {
                    if (monthCells.indexOf(cell) >= 35) {
                        if(cell.classList.contains('vuecal__cell--out-of-scope')) {
                            cell.style.display = 'none';
                        }
                    }
                })
            },
```
Which is being activated on change-view, but it's not working properly

**Comment by Twoody** [comment]
@MikhailLadonkin I want to ask some questions to provide clarity on this task. Please confirm or fix my understanding as I see the request:

The request is to start the calendar on the first day of the month, and end it on the last day of the month. Furthermore, we want to hide any additional days such that, if a month is 31 days, we will show 6 additional days of the next month to complete that row.

I am guessing this is an extension of the `startWeekOnSunday` and would then hide the `weekday-heading` slot.

**Comment by mikeladon** [comment]
@Twoody it basically would be great to have the following:

The calendar starts with the week of the first day of the month - it doesn't have to start with the first day of the month, so it's ok the way it is right now.

The problem is with the last rows - basically, it would be nice to make the last row the one which has the last day of the month, and to not have any extra weeks included. I guess it is sort of making the calendar flexible, as for some months the last date might appear on the 6th row, and sometimes it might be the 7th.

For instance, we might have the following dates in the last row:

29 30 31 1 2 3 4

And what we don't need here (at least for the project that I'm working on), is the next line(s):

5 6 7 ....

Hope I was able to explain it properly :)

**Comment by antoniandre** [comment]
Hi @MikhailLadonkin,

you should be good with this function:

```js
const daysPerWeek = 7 // Number of days per week displayed in your vue-cal.

onViewChange({ view }) {
  if (view === 'month') {
    const cellsCount = daysPerWeek * 6 // 6 rows of weeks.
    // Give it some time to be in the DOM.
    setTimeout(() => {
      // Get all the cells in month view.
      let cells = Array.from(document.querySelectorAll('.vuecal__cell'))
      // Keep only the last row.
      cells = cells.slice(cellsCount - daysPerWeek)

      // Hide out of scope cells. Also unhide cells if needed on next view change.
      cells.forEach(day => day.style.display = day.className.includes('out-of-scope') ? 'none' : 'block')
    }, 400)
  }
}
```

And add this on `vue-cal` tag in template `@view-change="onViewChange"`.
You should also do it on`@ready`.

But as I said earlier you will have an ugly jump when switching from 6 to 5 rows and vice versa.

Let me know if you need more assistance.

Thanks @Twoody for your support ;)

**Comment by mikeladon** [comment]
@antoniandre @Twoody now it seems to be working just fine, a few minor changes and it will be just what I want! Thanks a lot for your help!

**Comment by antoniandre** [comment]
Great @MikhailLadonkin!
Please close the issue if solved.

**Comment by antoniandre** [comment]
Closing the issue now, please reopen if not solved.
