### ISSUE TITLE
How to get  the event x and y coordinates  on cell-click or cell-dblclick?

### ISSUE THREAD

**Issue by xiyu1992** [antoniandre/vue-cal-v4#268]
Hi @antoniandre 
I can use cell-contextmenu get the event x and y coordinates, but I hope cell-click or cell-dblclick is OK or  at least return domEvent. Or why it's not recommended

Thanks

**Comment by antoniandre** [comment]
Hi @xiyu1992,
That's right, in most scenarii, on click or double click we need to know the exact time, so that's returned.
I added the raw X and Y coordinates in right click to allow placing a contextual menu.

What do you need the coordinates for? I'll see if I can help.

**Comment by xiyu1992** [comment]
@antoniandre Thanks for your reply!
 I hope that clicking or double clicking can also place a contextual menu.
But I convinced myself to use right-click instead.
Thanks for your great job!

**Comment by antoniandre** [comment]
@xiyu1992, great all good then! Closing the issue now.
If in the end you need the coordinates let me know.
