### ISSUE TITLE
Can't find vue-cal/dist/drag-and-drop.js 

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#269]
Hello. I install the last version of vue-cal by perform npm i --S vue-cal@alpha, but the file drag-and-drop.js  doesn't exist in vue-cal/dist folder. What I should to do to receive drag-and-drop functionality?

**Comment by antoniandre** [comment]
Hi @Iguana59,
the latest version is 3.2: https://antoniandre.github.io/vue-cal/#release-notes
There is no alpha anymore (and the drag and drop became a module after the alpha version).
 https://antoniandre.github.io/vue-cal/#ex--drag-and-drop-in-details, so you have to import it first.

1. `npm i --S vue-cal`
2. `import 'vue-cal/dist/drag-and-drop.js'`

You should be good with that.

**Comment by Iguana59** [comment]
Thanks.
