### ISSUE TITLE
How scroll horizontally to current date (week view) when using splitting-days

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#270]
Hello. I ran into a problem when I implemented splitting days feature and set min cell width 400px. As a result of this, a horizontal scroll appeared, since all days do not fit. And if I have events on Friday, Saturday or Sunday, then I do not see them when downloading the calendar. Is there a way to scroll to current date when loading a calendar, just as I did with calendar.scrollTo(...) to scroll vertically

**Comment by antoniandre** [comment]
HI @Iguana59,

Like for `scollTop`, you can change the `scrollLeft` value:

```js
scrollToRight () {
  const calendar = document.querySelector('#vuecal .vuecal__bg')
  calendar.scrollTo({ left: 6000, behavior: 'smooth' }) // how many pixels you want.
}

// For IE11. Adds this to your page once (in `created` hook for instance).
if (!HTMLElement.prototype.scrollTo) HTMLElement.prototype.scrollTo = function ({ left }) { this.scrollLeft = left }
```

**Comment by Iguana59** [comment]
Thanks a lot. This is what you need

**Comment by Iguana59** [comment]
Hello. I checked your approach and it doesn't work. Also I checked scroll to top using  calendar.scrollTo({ top: xxx, behavior: 'smooth' }) - and it doesn't work also. What can be a root cause?

**Comment by antoniandre** [comment]
Hi @Iguana59,
If it does not work and it does not work on documentation example, this is due to your browser.
https://caniuse.com/#search=scrollTo

Otherwise you don't use it correctly, check the documentation: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
