### ISSUE TITLE
Prevent past events creation

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#271]
Hello. If vue cal has option to prevent past events creation? Of course, I can check if start date < current time, but also I want the past tense to be visually visible (by css)

**Comment by antoniandre** [comment]
Hi @Iguana59,

As per the documentation https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation (3rd example), there is a `on-event-create` option accepting a function triggered on event creation. From inside you can add your logic and return false to prevent the event creation.

You could also use a `min-date` as per the documentation: https://antoniandre.github.io/vue-cal/#ex--min-max-dates to prevent creation on the past days.

Hope it helps.
Please read the documentation carefully.

**Comment by Iguana59** [comment]
Thanks a lot
