### ISSUE TITLE
Drag and drop functionality doesn't redraw color of the events when using splitting events functionality 

### ISSUE THREAD

**Issue by Iguana59** [antoniandre/vue-cal-v4#273]
Hello. I am splitting event by three resources (containers) and use for this different colors for events. When dragging event from one resource to another, the color of event doesn't change (I use on-even-change callback for this purpose and change class property to the necessary, but the color of the event remains the same. Only after you reload the page - the colors of the events change)

**Comment by micbra** [comment]
Can you show your `onEventChange` callback function?

**Comment by Iguana59** [comment]
This is @event-change callback function
`onEventChange(data) {
        if (data.originalEvent) {
          this.beforeSave(data.event)
          this.saveEvent(data.event)
        }
      },`
The beforeSave function -> 
`beforeSave(event) {
      if (event) {
        event.startDate = formatDate(event.start, this.format)
        event.endDate = formatDate(event.end, this.format)
        event.serviceBox = this.boxes.find(box => box.innerId === event.split)
        event.class = getClass(event.split)
        return
      }
....
}
`
getClass -> 
`export function getClass(innerId) {
  return innerId ? '_' + innerId : ''
}`
So if event.split = 2, then class will be equal '_2'

**Comment by micbra** [comment]
Hi @Iguana59,

the problem is, that you are only setting the `class` on the event emitted from the calendar, but instead you have to set it on the actual event-item in the calendar.

In your `beforeSave` function you could do something like this:
```javascript
<template>
  <vue-cal ref="vueCal" :events="events" />
</template>

<script>
export default {
  methods: {
    beforeSave ({_eid, split, start, end}) {
      // ...
      const event = this.$refs.vueCal.view.events.find(event => event._eid === _eid)
      event.class = `_${split}`
    }
  }
}
</script>
```

**Comment by Iguana59** [comment]
Thanks a lot. That helped
