### ISSUE TITLE
all-day lines mis-aligned if view not scroll

### ISSUE THREAD

**Issue by ray007** [antoniandre/vue-cal-v4#274]
The all-day line has a `padding-right: 17px` which is nice when the main view is scrolled.
But it's not nice when the main area doesn't need a scrollbar:

![image](https://user-images.githubusercontent.com/126712/80355046-da1c6080-8877-11ea-897e-f1006400deb0.png)

**Comment by antoniandre** [comment]
Hi @ray007,

The 17px padding right comes from the calculation of a detected scrollbar width on mounted.
This means on mounted it was scrollable. (please read #221)

Unfortunately this piece of code responsible of detecting a scrollbar is not costless and should therefore not be added in the `view-change` hook for constant re-detection. It would slow down Vue Cal for other cases where this detection is not needed more than once.

In your case, you can probably detect if there is a scrollbar from your component's data from the `vue-cal height -  (time cells count * time cell height)` either when you change one of these variables or in the`view-change` hook.

once you know there is no scrollbar, you need to remove the padding from CSS:
```css
.vuecal__weekdays-headings,.vuecal__all-day {padding-right: 0;}
```

Hope it helps.

**Comment by ray007** [comment]
I didn't think it was such an expensive operation, since `view-change` shouldn't happen that often, but I can work with this.

**Comment by antoniandre** [comment]
Did you manage to get it working?
I added the scrollbar width calculation to help out and this is done once so it is really acceptable in the codebase.
This calculation is is not very expensive but it adds up with all the small things and not including it as less frequent scenario is a tradeoff to keep the best performances.

Let me know if you still have difficulties.

**Comment by ray007** [comment]
Since I already have a window `resize` handler to calculate new time rows, I've put it there.
