### ISSUE TITLE
Prefix all classes or allow custom class prefix

### ISSUE THREAD

**Issue by andrewgioia** [antoniandre/vue-cal-v4#275]
Almost all class names are correctly prefixed with `vuecal__`, but the few that are not are causing some style conflicts for me. The 2 in particular are the spans within a `vuecal__time-cell`:

    <div class="vuecal__time-cell" style="height: 40px;">
        <span class="line"></span>
        <span class="label">06:00</span>
    </div>

Unfortunately `.label` is particularly common and it's inheriting a lot of unnecessary styles. 

It would be fantastic if these were also prefixed (e.g., `.vuecal__label`), or if a custom prefix on all classes was supported.

**Comment by antoniandre** [comment]
Hi @andrewgioia, 
That makes sense I will add prefixes on these classes and will let you know when I release!

**Comment by antoniandre** [comment]
Hi @andrewgioia, it is now published in version 3.2.3.

The new classes are `.vuecal__time-cell-line` & `.vuecal__time-cell-label`.

Hope it helps.

**Comment by andrewgioia** [comment]
Thank you @antoniandre! I really appreciate it.
