### ISSUE TITLE
@view-change does not work on the first day of the week.

### ISSUE THREAD

**Issue by davnavarro** [antoniandre/vue-cal-v4#279]
Hi,

From week view, if Monday is accessed, @ view-change does not change the value of "view" to "day".
If from that day we move to another if it changes, and when it returns to Monday it remains.
Going from Monday to week view does not work either. With the rest of the days, or if we go to the month or year view, it works correctly.

It only happens with Monday, I have tried to change the first day of the week with 0 and 1, and it happens the same.

Thanks and best regards

**Comment by antoniandre** [comment]
Hi @davnavarro , thanks for reporting.
This should be fixed in version 3.2.5, documentation example works fine.
Let me know if you still see a problem.

**Comment by davnavarro** [comment]
Thank you very much, it is already solved :)
