### ISSUE TITLE
Support displaying more than 3 simultaneous events, in chronologic order.

### ISSUE THREAD

**Issue by tarreislam** [antoniandre/vue-cal-v4#28]
Hi,

I noticied this and I cannot wrap my head around it, you might have some useful insight on this:

Here is a gif showing the problem I have: https://i.imgur.com/c9SlrZO.gif
As you can see, its not possible to reach the event 2. The only way to reach it is to set `:time="false"`

here is the events I used in the example
```javascript
[
        {
          start: '2019-01-10 10:00:00',
          end: '2018-01-10 10:30:00',
          title: '1',
          content: '1',
          class: 'primary'
        },
        {
          start: '2019-01-10 10:00:00',
          end: '2018-01-10 10:45:00',
          title: '2',
          content: '2',
          class: 'info'
        },
        {
          start: '2019-01-10 10:00:00',
          end: '2018-01-10 11:00:00',
          title: '3',
          content: '3',
          class: 'warning'
        },
        {
          start: '2019-01-10 09:59:59',
          end: '2018-01-10 11:00:01',
          title: '4',
          content: '4',
          class: 'danger'
        }
      ]
```

And the last thing is that when I use `:time="false"` the events are showing on different days, as you also can see in the gif.

**Comment by antoniandre** [comment]
Hi @tarreislam,

Unfortunately vue-cal is only capable to display up to 3 overlapping events currently.
Displaying 4 or more simultaneous events will stack in the middle all the other events. So this is a feature request.

Regarding events displayed on other days, that is probably bug. But can you double check that your events are not ending before they start in case it comes from this? 😅 

```js
    start: '2019-01-10 10:00:00',
    end: '2018-01-10 10:30:00'
```

If that is not the source of issue do mind sharing a testable demo?

Thank you!

**Comment by tarreislam** [comment]
Hi,

sorry for the late reply.
 
I see, yeah that would be a nice addition to stack more than three events on a single timeslot. Today I have solved it by having a filter method for the array, so this is not super critical for me.

But an alternative (for me at least) could be if you added a new prop that:
1.  Removes the time (just like `:time`)
2. Stacks all events ontop on each other and sorts them by time. (Like this: https://i.imgur.com/YNamPeG.png)

Now when I think about it, that is a feature I would like more than having more stacks on timeslots.

**Regarding the potential bug:**
Whops! my bad. But the result is still the same when using correct dates.

```
[
        {
          start: '2019-01-10 10:00:00',
          end: '2019-01-10 10:30:00',
          title: '1',
          content: '1',
          class: 'primary'
        },
        {
          start: '2019-01-10 10:00:00',
          end: '2019-01-10 10:45:00',
          title: '2',
          content: '2',
          class: 'info'
        },
        {
          start: '2019-01-10 10:00:00',
          end: '2019-01-10 11:00:00',
          title: '3',
          content: '3',
          class: 'warning'
        },
        {
          start: '2019-01-10 09:59:59',
          end: '2019-01-10 11:00:01',
          title: '4',
          content: '4',
          class: 'danger'
        }
      ]
```

Cheers /Tarre

**Comment by antoniandre** [comment]
Hi @tarreislam,
I have tried your events and they all appear on the same day. Stacked and not very readable, I confess, but same day. So let me rename this issue.

Displaying more than 3 simultaneous events is not the top priority for now but I will work on that in a handful of releases. I will still have a glimpse soon to see if there's a quick solution.

Regarding the events displaying in a chronologic order, this is more important to me.
Not sure I understand your screenshot though, are you suggesting to stack vertically? or grouping 2 events in same box?

I will keep you updated here.

**Comment by tarreislam** [comment]
Hi again.

**Regarding the bug:**
Okay tahts weird, I will double check to see if my css is poop.

**Regarding displaying more than 3 simultaneous**
No worries, if you figure it out, you do, if you dont, its not the end of the world.

**Regarding events displaying in chronological order**
Sorry for my bad excel example, I did not mean to make them grouped 😄. What I meant was: each event stacked vertically, sorted by startDate, endDate.

**Comment by tarreislam** [comment]
Just like you show events in the month-view I would like to do but in the Day view.

This is pretty accurate:

https://i.imgur.com/MVFetnD.png

**Comment by antoniandre** [comment]
Ok I understand you want to stack up events like timeless events (https://antoniandre.github.io/vue-cal/#ex--timeless-events) but with time information.
\+ chronologic sorting.

For now you can achieve this with CSS by forcing events height to auto and position to relative.
I will think about it but I am still not sure I will add an option for stacking events with time.

**Comment by ivanmercado9** [comment]
Do you have a solution to the problem? I need to be able to have more than 3 events at the same time for a reservation calendar that I am working on.

**Comment by antoniandre** [comment]
Hi @ivanmercado9, 
this is not yet available, I will start it next week.

**Comment by nandi95** [comment]
Hi @antoniandre 
I'm not creating a new issue as this might be connected but when I'm displaying 2 simultaneous events I have this warning (the functionality still works fine at this point):
```
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <VuecalCell>
       <VueCal>
         <Calendar> at resources/js/components/Calendar.vue
           <Root> vue.common.dev.js:630
[Vue warn]: Error in updated hook: "TypeError: children is undefined"

found in

---> <TransitionGroup>
       <VuecalCell>
         <VueCal>
           <Calendar> at resources/js/components/Calendar.vue
             <Root> vue.common.dev.js:630
TypeError: "children is undefined"
    VueJS 7
vue.common.dev.js:1892
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vue.common.dev.js:9022
 vue-devtools  Detected Vue v2.6.8 backend.js:1:27776
```
However if I have 3 overlapping events I have an error and no event displays:

```
[Vue warn]: Error in render: "TypeError: _this.cellEvents.find(...) is undefined"

found in

---> <Event>
       <TransitionGroup>
         <VuecalCell>
           <VueCal>
             <Calendar> at resources/js/components/Calendar.vue
               <Root> vue.common.dev.js:630
TypeError: "_this.cellEvents.find(...) is undefined"
    eventClasses vuecal.common.js:4798
    eventClasses vuecal.common.js:4797
    eventvue_type_template_id_1a6e39ce_lang_pug_render vuecal.common.js:4696
    VueJS 104
    js app.js:37
    Webpack 5
vue.common.dev.js:1892
[Vue warn]: Error in render: "TypeError: _this.cellEvents.find(...) is undefined"

found in

---> <Event>
       <TransitionGroup>
         <VuecalCell>
           <VueCal>
             <Calendar> at resources/js/components/Calendar.vue
               <Root> vue.common.dev.js:630
TypeError: "_this.cellEvents.find(...) is undefined"
    eventClasses vuecal.common.js:4798
    eventClasses vuecal.common.js:4797
    eventvue_type_template_id_1a6e39ce_lang_pug_render vuecal.common.js:4696
    VueJS 104
    js app.js:37
    Webpack 5
vue.common.dev.js:1892
[Vue warn]: Error in render: "TypeError: _this.cellEvents.find(...) is undefined"

found in

---> <Event>
       <TransitionGroup>
         <VuecalCell>
           <VueCal>
             <Calendar> at resources/js/components/Calendar.vue
               <Root> vue.common.dev.js:630
TypeError: "_this.cellEvents.find(...) is undefined"
    eventClasses vuecal.common.js:4798
    eventClasses vuecal.common.js:4797
    eventvue_type_template_id_1a6e39ce_lang_pug_render vuecal.common.js:4696
    VueJS 104
    js app.js:37
    Webpack 5
vue.common.dev.js:1892
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <VuecalCell>
       <VueCal>
         <Calendar> at resources/js/components/Calendar.vue
           <Root> vue.common.dev.js:630
[Vue warn]: Error in updated hook: "TypeError: children is undefined"

found in

---> <TransitionGroup>
       <VuecalCell>
         <VueCal>
           <Calendar> at resources/js/components/Calendar.vue
             <Root> vue.common.dev.js:630
TypeError: "children is undefined"
    VueJS 7
vue.common.dev.js:1892
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vue.common.dev.js:9022
 vue-devtools  Detected Vue v2.6.8 backend.js:1:27776
```

**Comment by antoniandre** [comment]
Hi @nandi95, sorry I missed your comment here. Do you mind giving me your code using vue-cal or a reproduction link please?

**Comment by nandi95** [comment]
Hi @antoniandre,
sample of what I'm passing to the component:
https://imgur.com/lO6nvCb

I wrappped the component in mine because I'll be adding features. The component: 
https://pastebin.com/bpy8e8EY

**Comment by KacperPucek** [comment]
Hi @antoniandre, first of all - REALLY cool lib! Thanks a lot ❤️ 

I'm struggling with the same issue as @nandi95, it seems that
it crashes when we have overlapping events and `id` in event.
When I remove `id` key from data, it runs alright so it's not
a big problem to work around it.

I don't have a fix but I thought I'd mention that anyway as it might
point you in the right direction if you decide to tackle this :)

**Comment by antoniandre** [comment]
Hi @nandi95, @KacperPucek, 
First off, thanks for your feedback @KacperPucek I appreciate it.
And thanks for giving me a track. I can't seem to reproduce the issue, but I will refactor the events overlapping system to handle more simultaneous events anyway as the error comes from this.
The logic will change and it should solve the current issue.

I am starting this ASAP.

**Comment by tarreislam** [comment]
Youre doing a Great job!

**Comment by antoniandre** [comment]
Hi @nandi95, @KacperPucek, I have started the refactoring of event overlaps but it's not going to be released soon as it's a very complex problem to calculate width and left offset of all simultaneous events.

So I am more concerned about fixing the issue at stake for now.
As pointed by @KacperPucek the issue might be related to the use of the `id` key which is reserved for internal identification. I am freeing this key for vue-cal users and will internally use `eid`.
See more here: #70.

@nandi95, can you confirm if you were setting or modifying event `id` in your case too? Thanks.

@tarreislam, sorry mate it's going to take longer than I thought. I have tried different approaches but still unsuccessful, most attempts end up in infinite loops. 🔫 I still need to think it over and find a genius idea.

**Comment by nandi95** [comment]
@antoniandre yes, when not passing an id it works without a warning or error.
Perhaps it would be a good idea to make a note in the docs that the eid is a reserved word or use some obscure string like "r8xfQOBsWf".
Keep up the good work, it's an awesome library.

**Comment by antoniandre** [comment]
@nandi95 glad to know it came from that too, it is now fixed (#70). 
you're right, I will update the documentation to warn that the `eid` key is taken.

**Comment by KacperPucek** [comment]
Thanks for a lot for the hard work and fixing the issue @antoniandre 🏆

**Comment by abrudane** [comment]
@antoniandre Hello, I really love your lib. I've just managed to integrate it in my project. 
One question: Do you have a timeline, when can it be possible to add and manipulate multiple events on single day?
Our client needs this really soon and I was wondering, if there is a timeline from you. Thanks a lot.

**Comment by antoniandre** [comment]
Hi @abrudane, thank you for your feedback.

> when can it be possible to add and manipulate multiple events on single day?

I am not sure what you mean,
**If your request is to handle more than 3 simultaneous events**, then there is no timeline for this as it is not the top priority for now and also very complex to calculate some event overlaps layout cases. 
But until I find a way there is always the possibility to force display as you want from CSS, you can also tweak the cell (https://antoniandre.github.io/vue-cal/#ex--custom-title-and-cells) to add an event count for css styling for instance.

**If your request is to create as many events as you want on a single day view**, this is already possible, check out these examples and navigate to day view to create events: 
- https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events
- https://antoniandre.github.io/vue-cal/#ex--more-advanced-event-creation

**Comment by abrudane** [comment]
@antoniandre yes, that would be the idea. Now that I look into the examples you've given me, I see that is clear and easy. Sorry to bother you with this question. Thank you.

**Comment by antoniandre** [comment]
Hi @tarreislam, @ivanmercado9, @nandi95, @KacperPucek,
The V2 is out and it now supports more simultaneous events! Check the release notes before using.

Hope you like it!

**Comment by tarreislam** [comment]
I just implemented V2 and I am very pleased how you solved the 3 cell stack issue!
