### ISSUE TITLE
Splits show/hide "no-event" slot per day

### ISSUE THREAD

**Issue by micbra** [antoniandre/vue-cal-v4#280]
Hi @antoniandre,
first of all massive thanks for this awesome package! 🥳

I think there is a bug when one uses split days.
When there are no events, the text from the `no-event` slot is displayed in every split.
When I create a new event, the text **disappears for every split** of that day the event was added to.

I would expect that the text only disappears from the split where I created the event.

**Comment by antoniandre** [comment]
Hi @micbra, 
Thanks for your feedback, I appreciate it.

I was originally thinking that duplicating the no event text in all the splits would be looking too cluttered,
 then I left it and forgot it.

Now that you point it out again, it makes sense. Users have the choice to have it or remove it anyway.
Will let you know when ready.

**Comment by antoniandre** [comment]
Hi @micbra, 
In version 3.2.6, the `no-event` slot is now handled per split if there are splits.
https://antoniandre.github.io/vue-cal/#ex--splitting-days

Hope it helps!

**Comment by micbra** [comment]
Thanks man, really appreciate your efforts!
