### ISSUE TITLE
Events trigger click when being resized

### ISSUE THREAD

**Issue by micbra** [antoniandre/vue-cal-v4#281]
When I turn on `editable-events` and also have set a handler for `:on-event-click` the click handler is sometimes called when I resize a event.

Here is a live example: https://codesandbox.io/s/sharp-kowalevski-qm2yj?file=/src/App.vue
Try to resize the event slowly, so the cursor is still slightly over the event item, when the `mouseup` event fires.

**Comment by antoniandre** [comment]
Hi @micbra, thanks for reporting.
This happens if you release the mouse dragging ON the event, that will constitute an event click from mousedown + mouseup on event.

But you are right this should not happen and you are the first to report it, so I'll fix it.
Will let you know when I release it.

**Comment by antoniandre** [comment]
Hi @micbra, this is now fixed in version 3.2.4.
