### ISSUE TITLE
Cell-content slot reach split value

### ISSUE THREAD

**Issue by Csandori** [antoniandre/vue-cal-v4#283]
Hi @antoniandre !

Is it possible to get the split value in cell-content? It would be a really big help if I could reach this value.

Thanks!

**Comment by antoniandre** [comment]
Hi @Csandori, 
Can you be more specific in "split value"? is it the split id?
And for cell content is it the cell component or the cell renderer in slot?

If you can put a little bit of context around that it will help me understand and help on this.
Cheers.

**Comment by antoniandre** [comment]
Closing the issue now, please reopen if not solved.

**Comment by Csandori** [comment]
I solved it with a workaround. 
The problem was that I couldn't get any data in
`v-slot:cell-content="{ cell, view, split, events, goNarrower }"`
from split.
