### ISSUE TITLE
View-change not emitted on switching between day & week view

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#285]
I don't receive view-change event when switching between week and day view. 
If I switch from month view to day or week or the opposite, the event is emitted but not when switching between day and week.
It is the same in the events example calendar in the documentation: https://antoniandre.github.io/vue-cal/#ex--emitted-events

**Comment by davnavarro** [comment]
I think it is related to open issue #279

**Comment by antoniandre** [comment]
Hi @green-pigeon, thanks for reporting.
This should be fixed in version 3.2.5, documentation example works fine.
