### ISSUE TITLE
Hold click on event trigger on-event-click

### ISSUE THREAD

**Issue by txinando** [antoniandre/vue-cal-v4#287]
Hi,

first of all thx for the plugin, works great! 

I have an :on-event-click method, but when i hold click to remove an event shows me the dialog in the method on event click.

How can i fix it ?

Regards

**Comment by xiyu1992** [comment]
Yes, I'm here, too. The e.stopPropagation of the :on-event-click is invalid. It may be caused by this commit [https://github.com/antoniandre/vue-cal/commit/2034c99a82570edcf5e07688fec402ffa8094d77]

**Comment by xiyu1992** [comment]
Yes, I'm here, too. The e.stopPropagation of the :on-event-click is invalid. It may be caused by the [commit](https://github.com/antoniandre/vue-cal/commit/2034c99a82570edcf5e07688fec402ffa8094d77) to fix this problem [#281](https://github.com/antoniandre/vue-cal/issues/281)

**Comment by antoniandre** [comment]
Thanks for reporting and for the feedback @txinando, I will push a fix soon.

**Comment by antoniandre** [comment]
@txinando, @xiyu1992, this should now be fixed in version 3.2.7

**Comment by messiahUA** [comment]
Hello, on-event-click stopped working for me after this change. Nothing happens on click at all.

**Comment by antoniandre** [comment]
Thanks for reporting @messiahUA, I'll release a patch soon.

**Comment by antoniandre** [comment]
@messiahUA, this should now be fixed in version 3.2.8.

@txinando Please close the issue when it is solved for you. Thanks

**Comment by txinando** [comment]
Tested and works great! Thx a lot.
