### ISSUE TITLE
:on-event-click not working anymore 3.2.7

### ISSUE THREAD

**Issue by cooljet84** [antoniandre/vue-cal-v4#288]
The on-click-event is not longer working in v3.2.7 (confirmed working in 3.2.6)
See https://codepen.io/psasburg/pen/NWGZmMo

**Comment by antoniandre** [comment]
Thanks for reporting, I'm on it.

**Comment by antoniandre** [comment]
Hi @cooljet84, @pamatz, @messiahUA, 
This should now be fixed in version 3.2.8.
Thanks for your support

**Comment by antoniandre** [comment]
Closing the issue now, please reopen if not solved.
