### ISSUE TITLE
Splitted week view: Header not fixed

### ISSUE THREAD

**Issue by paul-gaspar** [antoniandre/vue-cal-v4#289]
When splitting is active, and horizontal scrolling is enabled, the header (with day label and split label) scrolls out of view, when scrolling vertical.

This makes the split view completely unusable. You can not use a calender when you can't see the days.

**Comment by antoniandre** [comment]
Hi @paul-gaspar, 
Well, I am sorry if this calendar is completely unusable because of this.
I will not add Javascript to perform the sync as it's overkill. There is a CSS3 way if you are interested it's called `position: sticky`, but it does not work on IE. 
Read on in #286

**Comment by paul-gaspar** [comment]
Hi @antoniandre,

hmm, I did not write that the whole calendar is unusable. Just the split view is unusable in that use case, which is true.

But thank you for the hint with position sticky. I will try this.
