### ISSUE TITLE
Misplaced all day events bar with day splitting on week view

### ISSUE THREAD

**Issue by paul-gaspar** [antoniandre/vue-cal-v4#290]
With activated splitted view and horizontal scrolling, all-day events are a mess. They do not scroll with the rest and are in a strange, totally wrong position on the x axis.

Also they are positioned above the header instead of below.

**Comment by antoniandre** [comment]
Please provide code, screenshot and reproduction link.
Please also learn to be nice with people creating free libraries for others. This is the second issue where you criticize not constructively.

**Comment by paul-gaspar** [comment]
Hi @antoniandre,

so I think here are some fundamental misunderstandings. I don't want to bother you. I even sent you a not so small donation 3 days ago with a nice comment, because I like your work very much.

Still, there are a few bugs and I need to communicate them to you. Constructive communication is a 2-way thing.

It is not efficient for both of us to create a huge issue with everything in there first, when perhaps this is a know issue or there is a simple answer for it.

Now that I know what you need, I will provide all the details you mentioned.

**Comment by paul-gaspar** [comment]
<img width="637" alt="allday-split" src="https://user-images.githubusercontent.com/7533446/83537744-43d1ff00-a4f5-11ea-83c2-4f1a5a3ab70b.png">

Here is the screenshot. As you can see, the allday event has a wrong x-position (should be alinged to the user 2 column). Also the width seems to be wrong.

I will post the code in a few minutes.

**Comment by paul-gaspar** [comment]
This is the event data:
```
{
          start: "2020-06-01 12:30",
          end: "2020-06-01 13:30",
          title: "Allday",
          allDay: true,
          split: "u2"
}
```

Here are the splitDays:

```
      splitDays: [
        { id: "u1", class: "class 1", label: "User 1" },
        { id: "u2", class: "class 2", label: "User 2"},
        { id: "u3", class: "class3", label: "User 3" }
      ]
```

The configuration:

```
locale: "de",
      activeView: "week",
      selectedDate: "",
      minCellWidth: 400,
      minSplitWidth: 150,
      editableEvents: {
        title: false,
        drag: true,
        resize: true,
        delete: false,
        create: true
       }
```

And the template code:
```
<vue-cal
      ref="vuecal"
      :active-view.sync="activeView"
      events-on-month-view="short"
      :events="events"
      todayButton
      showWeekNumbers
      showAllDayEvents
      hide-view-selector
      overlapsPerTimeStep
      :disable-views="['year', 'years']"
      :locale="locale"
      :special-hours="specialHours"
      @ready="scrollToCurrentTime"
      :editableEvents="editableEvents"
      :snapToTime="15"
      :time-step="60"
      :selected-date="selectedDate"
      :time-from="9 * 60"
      :time-to="20 * 60"
      hideWeekends
      watchRealTime
      resize-x
      stickySplitLabels
      :split-days="splitDays"
      :minCellWidth="minCellWidth"
      :minSplitWidth="minSplitWidth"
      ><!-- hide-title-bar -->
       <!-- showAllDayEvents -->
      <template v-slot:event="{ event }">
        <div class="event" style="background-color">
          <span class="calendar-event-time">{{
            event.start.formatTime("hh:mm")
          }}</span>
          <div class="vuecal__event-title" v-html="event.title" />
          <div class="calendar-event-client">{{ event.client }}</div>
          <div class="calendar-event-project">{{ event.project }}</div>
        </div>
      </template>
    </vue-cal>
```

**Comment by paul-gaspar** [comment]
Please tell me, if you need deeper information. I can also set up a reproduction link if needed.

So again, it was not my intention to be harsh. I am sorry if it sounded like that.

**Comment by antoniandre** [comment]
Hi @paul-gaspar,
It's all good, getting back on a good communication. Thanks for your support on Vue Cal.

This is enough information thanks, I will try that locally and see what I can do.
Indeed the all day events bar is obviously misplaced, it was never used before in conjunction with day splits and min-split-width.

**Comment by antoniandre** [comment]
Hi @paul-gaspar,
This should now be fixed in version 3.3.0.
In your case (splitDays + minSplitWidth + all-day bar), you will need to provide a fixed height through the new [`allDayBarHeight`option](https://antoniandre.github.io/vue-cal/#api).

Hope it helps, my apologies too for the misunderstanding.

**Comment by paul-gaspar** [comment]
Hi @antoniandre,
Thanks a lot! This is an amazingly fast fix. Works perfectly here.

**Comment by antoniandre** [comment]
Great! Closing the issue then.
You can reopen if you find a bug.
