### ISSUE TITLE
Splitted week view: Slot for split label

### ISSUE THREAD

**Issue by paul-gaspar** [antoniandre/vue-cal-v4#291]
Would be great to habe a slot for the split label (with stickySplitLabels true), e.g. to render a user avatar picture.

**Comment by antoniandre** [comment]
Hi @paul-gaspar,
This is now available in version 3.4.0.
You can refer to this example: https://antoniandre.github.io/vue-cal/#ex--custom-day-split-labels

Hope it helps.

**Comment by paul-gaspar** [comment]
Thanks a lot, @antoniandre! Works like charm. I will post a screenshot here soon.

**Comment by antoniandre** [comment]
Great, closing the issue then.

**Comment by paul-gaspar** [comment]
So here is the screenshot as promised:

<img width="451" alt="split-header" src="https://user-images.githubusercontent.com/7533446/84263511-e60a6c00-ab1f-11ea-85a7-94d81ab94dca.png">
