### ISSUE TITLE
Event template is not applied for all day events (ver. 3.3.0)

### ISSUE THREAD

**Issue by green-pigeon** [antoniandre/vue-cal-v4#292]
I have defined an event template: <template v-slot:event="{ event, view }">
It adds some additional content and css to events. It was working well with 3.2.8 but after updating to 3.3.0, the template is not applied for the events in the all day bar. It is applied for other events in month and week view.

**Comment by antoniandre** [comment]
Thanks for reporting @green-pigeon.
Please provide the `<vue-cal>` code that you use.

**Comment by antoniandre** [comment]
I figured out, now fixed in version 3.3.1.
Demo: https://codepen.io/antoniandre/pen/xxZbKrO?editors=1010

**Comment by green-pigeon** [comment]
Thanks.
I confirm it is fixed.
