### ISSUE TITLE
Clicking an empty cell and swipe up or down creates new event

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#297]
Hey @antoniandre,

I am again with a little issue here. I am using the vue-cal: 3.4.1.
I am creating new events by double clicking the cell, then a modal open up and everything works.

On my logic code (controller), I am setting up the `resizable`, `draggable`, and `titleEditable` to false. Since I want only the deletable property to be true.

On my vue-cal instance I have set `editable-events`.

Before the version 3.4.1, I was unable to click and resize an event, since I set up the properties when creating an event.

So, when I click an empty cell and then move mouse up or down (resize), it creates an event (only on my UI, of course). I want to disable that, because my way to create events is double clicking the empty cell.

Next you can see a gif of the issue:
![github-vuecal](https://user-images.githubusercontent.com/12451362/84334700-61dcd680-ab69-11ea-850f-2a87cdbc3910.gif)

I want to disable the way gray events (default) are created and keep only the yellow event way (modal).

So, is there an option to disable it?

Thank you.

**Comment by antoniandre** [comment]
Hi @giulianimartini,
Yes. This is a new feature of version 3.5.0: https://antoniandre.github.io/vue-cal/#release-notes
This updated example is explaining how to disable it: https://antoniandre.github.io/vue-cal/#ex--other-event-creation-methods

So `:drag-to-create-event="false"` will do.

Remember to always check the release notes when you upgrade!
Hope it helps.

**Comment by giulianimartini** [comment]
Hey @antoniandre,

thank you very much.

Sorry for this issue. I am always with the documentation page opened and I just forgot to refresh it 😞 

Thanks for your time.
The calendar is working as expected.

**Comment by antoniandre** [comment]
No problem @giulianimartini. Your detailed questions with screencast are sparing me some time and wondering :) 👍
