### ISSUE TITLE
JS tests

### ISSUE THREAD

**Issue by doutatsu** [antoniandre/vue-cal-v4#30]
I was wondering if there are plans to add tests, say with Jest, for this library? That would make it me a lot more confident in using this library, as it looks fantastic and documentation is very well written.

**Comment by antoniandre** [comment]
Hi @doutatsu,
Thanks for your interest and feedback.
Sorry, there is currently no plan to add tests, as I am not familiar enough with unit testing to make it a priority.
I would rather spare time to work on my to do list and all the feature requests! haha 😅 

Well if ever you feel like contributing on that bit you are more than welcome! But I suspect it requires a more in depth knowledge of vue-cal code.

**Comment by doutatsu** [comment]
That's understandable. I am happy to contribute at least some of the basic setup and some component tests should be easy to do even without a full grasp of the codebase. And hopefully will give you a foundation to built on. I'll find some time and make a PR in the future

**Comment by antoniandre** [comment]
Thanks @doutatsu, if ever you have some spare time that would be well appreciated!
