### ISSUE TITLE
Stick split labels centered when having different length

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#301]
Hey @antoniandre,

Is there a way to set the header (split labels) to be centered independent of the length of the label?

I have tried different ways according to the CSS customization and everything on the vue-cal documention (I think), but no success. Have I missed something?

If you give a look at this screenshot of your documentation:

<img width="943" alt="Screen Shot 2020-06-16 at 19 02 47" src="https://user-images.githubusercontent.com/12451362/84833310-6be95400-b005-11ea-80f4-37db4043a858.png">

You can confirm that the labels Mom, Dad (3 characters) are almost aligned with the letter "o" of the "No event" indication, right? But Kid 1, Kid 2 and Kid 3 are not aligned with the letter "o", but almost with the letter "N".

So, the more the label has characters, the more it is aligned to the left, until the label is outside the split (lane). My labels are dynamic, so I need them to be centered.

Thanks.

**Comment by antoniandre** [comment]
Hi @giulianimartini,
Alright that's an easy one, just add:

```css
.vuecal__split-days-headers .day-split-header {flex-basis: 0;}
```

I'll see if it's not harmful for all the other cases, if not I will add it directly in the library.

**Comment by antoniandre** [comment]
I added it in the codebase and released it. You should be good with that ;)

**Comment by giulianimartini** [comment]
I just checked that! Thanks for this!
It's working like a charm :D

**Comment by antoniandre** [comment]
Great. Closing the issue then.
