### ISSUE TITLE
Cannot scroll when clicking an event

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#302]
Hi @antoniandre,

as mentioned in other thread, I opened this new issue to deal only with this one here.

My scenario:

1) I am developing a web app (tennis booking) where I have the vue-cal instance inside a webview;
2) Probably the calendar will be full of events every day.

The problem comes when I try to scroll down or up the calendar by clicking in an event (note that clicking in an empty cell, it works).

It just doesn't scroll. I am not trying to create, edit or delete an event, I just need to scroll down or up when not clicking empty cells or outside the calendar :)

Here's a gif to explain the issue:

![SVID_20200617_104456_1](https://user-images.githubusercontent.com/12451362/84906313-21f58200-b088-11ea-8722-db40ce977234.gif)

My vue-cal instance is like:

```
<vue-cal style="height: 100%"
    ref="vuecal"
    id="vuecal"
    :time-from="horarioAbertura === '' ? 6*60 : horarioAbertura"
    :time-to="horarioEncerramento === '' ? 24*60 : horarioEncerramento"
    :time-step="30"
    :disable-views="['years', 'year', 'month']"
    active-view="day"
    locale="pt-br"
    class="vuecal--full-height-delete"
    editable-events
    :events="res"
    :split-days="splitDays"
    :sticky-split-labels="stickySplitLabels"
    :min-cell-width="minCellWidth"
    :min-split-width="minSplitWidth"
    :time-cell-height="timeCellHeight"
    :selected-date="selectedDate"
    @ready="scrollToCurrentTime"
    :cell-click-hold="false"
    :drag-to-create-event="false"
    :on-event-dblclick="onEventClick"
    @event-delete="removeReserva($event)"
    @cell-dblclick="abreModalNovaReservaViaCalendario($event)">
</vue-cal>
```

Note that `:drag-to-create-event` is `false`. So that's not the problem.
It seems like `editable-events` is throwing this issue, since if I disable it, the scroll works, but then I can't delete events.

Is there a fix for this?

The create, edit and delete actions are working as expected. I am just having this scroll issue.

Thanks in advance.

**Comment by giulianimartini** [comment]
Hey @antoniandre,

have you checked this issue?

Thank you.

**Comment by antoniandre** [comment]
Hi @giulianimartini, it should now be possible to touch-scroll through events.
Released in version 3.6.6.

Let me know if this helps.

**Comment by giulianimartini** [comment]
Hi @antoniandre,

thanks for the reply.

I can't update to v3.6.6. NPM says  "No matching version found for vue-cal@^3.6.6.".

**Comment by antoniandre** [comment]
I forgot to push it to NPM, done now! 😅

**Comment by giulianimartini** [comment]
Hi @antoniandre,

All is working as expected. Thanks for this =)

I don't know if you were aware about the click event issue (at least it happened to me).
With this new release, the click on event, even on the body, is working.

I open a modal to update the booking when double clicking an event and before this new release (v3.6.6), the click was working only over the title of the event, not the rest (body).

I'm closing this issue right now!

Thank you again!
