### ISSUE TITLE
Only first day is shown for multiple day events when `time: false`

### ISSUE THREAD

**Issue by Duncank** [antoniandre/vue-cal-v4#303]
I've just updated from version 3.0.2 and found that for events that span multiple days only the first day is shown in the calendar when `time: false`. Previously, an event-block was shown every single day during the span of the event.

I've went back through all the releases since 3.0.2 and found that the change that breaks this was made in 3.1.0, the first version released after 3.0.2.

[JSFiddle on version 3.0.2](https://jsfiddle.net/Duncankrebbers/tqocu5hf/6/)
[JSFiddle on version 3.1.0](https://jsfiddle.net/Duncankrebbers/tqocu5hf/7/)

**Comment by antoniandre** [comment]
Thanks for reporting @Duncank, and for precisely finding the breaking change.
This is now fixed in version 3.5.6.

Let me know if there is still an issue!
