### ISSUE TITLE
Custom start day of the week

### ISSUE THREAD

**Issue by ghost** [antoniandre/vue-cal-v4#304]
Hi, thanks for this great library will all those features,
I have a small question or request :
I see we can start week on Monday or Sunday, can we start the week in any day of the week or to have a current day as a first day of week?

I see the feature to start on Sunday was added recently, but I was thinking if we can customise that.

All the best
Besartt

**Comment by antoniandre** [comment]
Hi @Besartt, thanks for the feedback.
At the moment you can't start the week from any other day than Sunday or Monday.
It's not the same but if that can help, you can hide any weekday (as this does not require internal refactoring) https://antoniandre.github.io/vue-cal/#ex--hiding-particular-week-days.

**Comment by ghost** [comment]
Hmm, this is not useful for our case, anyway thank you for response :)
