### ISSUE TITLE
Alternating Row colors 

### ISSUE THREAD

**Issue by Falken1998** [antoniandre/vue-cal-v4#306]
I might be blanking on some super easy way to do this, but is there a way to highlight alternating time-step rows when on week or day view?

**Comment by antoniandre** [comment]
HI @Falken1998,

The time cells don't have a particular css class for alternated color pattern. But it's easy to customize to add what you want.
https://antoniandre.github.io/vue-cal/#ex--timeline-tweaking

Using `<template v-slot:time-cell="{ hours, minutes }">` you can add a different class on minutes or hours.
Then in your css have 2 different colors for the 2 different classes.
