### ISSUE TITLE
Click on event outside of the current month

### ISSUE THREAD

**Issue by messiahUA** [antoniandre/vue-cal-v4#307]
I have "on-event-click" set and event titles displayed on the month view, but clicking on the event outside of the current month returns "undefined" event in the function. Is it intended or maybe a bug? Any workaround to make it work?

_Using vue-cal version 3.5.6_

**Comment by antoniandre** [comment]
Hi @messiahUA,
Please share your code so I can help. Ideally a Codepen.
Thanks

**Comment by messiahUA** [comment]
@antoniandre 
https://codepen.io/eugenepolyanichko/pen/NWxaXpV

you get undefined clicking on the event outside of the current month

**Comment by antoniandre** [comment]
Hi @messiahUA,

Thanks for your Codepen, but it it looks like it's broken so I created another one based on your code:
https://codepen.io/antoniandre/pen/MWKOYjW?editors=1010
(Check the console logs)

Everything seem to work fine unless I am missing something. Can you be more precise?

**Comment by messiahUA** [comment]
@antoniandre that's strange, my pen is working for me... anyways, your pen has everything the same except that all of the events are for the current month. For example change one of the events to start on 2018-12-03 and click on this event.

![image](https://user-images.githubusercontent.com/3277444/86134360-30b14f80-baf2-11ea-8eef-caa74719ed5b.png)

**Comment by antoniandre** [comment]
@messiahUA, ok I can see the bug too. Thanks for reporting, will let you know when fixed.

**Comment by antoniandre** [comment]
Hi @messiahUA, 
The bug is fixed in version 3.6.3, please reopen if you still see an issue.

Thanks for your contribution @Csandori!

**Comment by messiahUA** [comment]
@antoniandre thanks! will check it

You calendar is awesome!
