### ISSUE TITLE
Sync two vue-cal instances : how to change month ?

### ISSUE THREAD

**Issue by Jimmylet** [antoniandre/vue-cal-v4#309]
Hello !

First of all, thank you for this plugin. It's a great job! I left to use a competitor (very old) and I got here, I love it!

I particularly appreciate the possibility of synchronizing 2 calendars.

I managed to implement [the basic example](https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars).

In this example, the calendar is only synchronized when a day is selected. Is it possible to do this also when we change the month (by clicking on the arrows)?

Also, is it possible to synchronize the two together? If I change the day on the first, it changes on the second. And if I change the day on the second, does it change on the first?

Thanks again !

**Comment by antoniandre** [comment]
Hi @Jimmylet, Thanks for the feedback, I appreciate.

Yes you can fully sync 2 instances, even if I don't see a use case for it, here is a demo for you:
https://codepen.io/antoniandre/pen/ExPwGRm?editors=1010

Hope it helps!

**Comment by Jimmylet** [comment]
Thank you ! The use case would be purely "user experience".

My idea is to display a calendar in "week" view. And to navigate simply and quickly, a calendar in "month" view.

Maybe it's not super useful, I'm going to do some user tests to determine it.
