### ISSUE TITLE
Cannot read property 'set' of undefined 

### ISSUE THREAD

**Issue by ryanbottema** [antoniandre/vue-cal-v4#315]
Using vue-cal via script tag.  

`external_commonjs_vue_commonjs2_vue_root_Vue_default.a` is always undefined causing TypeErrors. Seems to happen only when trying to show multi-day events on month view:

       <vue-cal active-view="month"
                :events="events"
                :disable-views="disableViews"
                class="vuecal--blue-theme"
                style="height: 650px"
                today-button
                :on-event-click="onEventClick"
                :editable-events="false"
                :cell-click-hold="false"
                @cell-click="cellClick"
                :show-all-day-events="true"
                :events-on-month-view="true"
       />

Thanks

**Comment by ryanbottema** [comment]
Turns out it also happens with multiple events on same day when checking for overlapping events.

**Comment by antoniandre** [comment]
Hi @ryanbottema, I placed your code here: https://codepen.io/antoniandre/pen/rNxqrdX
But I can't see any error.

Please update the Codepen with the rest of your code to reproduce the error.

**Comment by ryanbottema** [comment]
@antoniandre Updated Codepen: [https://codepen.io/ryanbottema/pen/RwreBzj](https://codepen.io/ryanbottema/pen/RwreBzj).

Couple things;

- Forgot to mention I'm using requirejs, added that to the pen.
- There is another error which I had forgotten about which you'll see in the code pen that will have to be resolved before addressing the initial issue. I had temporarily worked around it by adding `if (this.view.outOfScopeEvents === undefined) this.view.outOfScopeEvents = []` to line 8078, ie:

        if (this.view.id === 'month') {
            var _events;
            if (this.view.outOfScopeEvents === undefined) this.view.outOfScopeEvents = [];
            (_events = events).push.apply(_events, _toConsumableArray(this.view.outOfScopeEvents));
        } // Only keep events in cell time range.

**Comment by antoniandre** [comment]
Seems to be working on the Codepen example. Closing this issue now.
