### ISSUE TITLE
event ending at midnight takes the whole next day

### ISSUE THREAD

**Issue by kkojot** [antoniandre/vue-cal-v4#318]
Hi,

the documentation says:

> You can set an event end at 24:00 or 00:00 (for the next midnight), but internally the date will be set at 23:59:59 so the date stays the same instead of natural behavior of taking the next day at 00:00:00.
When returned from emitted events, this event end will contain a date ending at 23:59:59.

so if I add an event which starts at `2020-07-15 21:00` and ends at `2020-07-16 00:00` I expect to display it to the end of the `2020-07-15` day. In the current version, it takes the whole next day also.

Reproduction link: https://codepen.io/kkojot/pen/jOWeJQX?editors=0011

**Comment by giulianimartini** [comment]
Hi @kkojot,

For now, I just set the time to `23:59:00` when it is `24:00:00` or `00:00:00`.

Of course, it's just a workaround for now.

**Comment by antoniandre** [comment]
Thanks for reporting @kkojot, I will fix this soon.
Thanks for your support @giulianimartini.

**Comment by antoniandre** [comment]
Hi @kkojot, 
This is now fixed in version 3.6.4 (make sure to hit the right version from your Codepen)
Please reopen if not solved!

https://antoniandre.github.io/vue-cal/#release-notes
