### ISSUE TITLE
Add feature to disable specific days

### ISSUE THREAD

**Issue by rafaelmranieri** [antoniandre/vue-cal-v4#324]
It would be very useful to be able to specify an array of days to become disabled on calendar rendering. As i noticed, it's only possible through the use of 'min-date' and 'max-date' attributes.

**Use case scenario:**

1. a calendar is presented to the user so she can select one day to book an appointment
2. the calendar should mark as disabled all the days specified in the array, which is, the ones that aren't meant to be working days, such as holidays etc
3. this way the user has a visual hint to know which days are possible to be selected and which ones are not

**Comment by giulianimartini** [comment]
Hi @rafaelmranieri,

I think there is no feature for this at this time (It's a good feature to be developed), but ...

Do the `special-hours` do the job for you?
Check it here: https://antoniandre.github.io/vue-cal/#ex--special-hours

If not, a workaround is the `background events` attribute.
Check it here: https://antoniandre.github.io/vue-cal/#ex--background-events

Hope it helps :D

**Comment by rafaelmranieri** [comment]
Hey there!
Thanks for the feedback.
But these two features, on my estimation, are not the right fit for the scenario I'm struggling with.

Anyways, let's see what I can do about it
Thanks again

**Comment by rafaelmranieri** [comment]
On second thought, maybe your suggestion about using the **background events** could do the trick for the moment
Thanks again :D

**Comment by giulianimartini** [comment]
Hi @rafaelmranieri,

Thanks for the feedback. 
Let me know if it works for your case.

**Comment by antoniandre** [comment]
Hi @rafaelmranieri,
This request makes sense, I am adding it to my to do list.

Thanks for your continuous support @giulianimartini!

**Comment by rafaelmranieri** [comment]
Wow, that's some good news @antoniandre!
It's gonna help a lot.

Can't wait to use it =)
Thank you.
Best regards.

**Comment by antoniandre** [comment]
Hi @rafaelmranieri,

This option is now published in version 3.7.0.
https://antoniandre.github.io/vue-cal/#ex--disable-days

Hope it helps.

**Comment by rafaelmranieri** [comment]
Hey @antoniandre 
That's exactly what I was looking for.
Thanks for adding this feature to your awesome component.

Take care
May the force be with you =)

**Comment by antoniandre** [comment]
Great! I am closing the issue then.
