### ISSUE TITLE
Date Navigation in Monthview is broken in IE

### ISSUE THREAD

**Issue by sanmaozhao** [antoniandre/vue-cal-v4#325]
1. use IE 11
2. goto sample website
3. https://antoniandre.github.io/vue-cal/#ex--basic
4. switch to Month view
5. click left or right arrows several times

got broken view
![image](https://user-images.githubusercontent.com/6970742/90227030-82b1f880-de46-11ea-9630-316269d8fa69.png)

like issue #176 , but i clearing the browser cache, and still not working.

Thanks!

**Comment by sanmaozhao** [comment]
When I click on the blank area on the right, the view becomes correct.

**Comment by antoniandre** [comment]
Hi @sanmaozhao, thanks for reporting this bug.

I admit this is a weird bug. But who uses and supports IE11 nowadays? lol
IE11 market share seems to be down under 1.3% lately https://gs.statcounter.com/browser-market-share
(So we should all stop supporting IE11 to make it count)

that being said, I found a solution to this problem but I let you add this in your own CSS:

```css
.vuecal__cells.month-view {height: 100%;}
```

Hope it helps! ;)

**Comment by antoniandre** [comment]
I am closing this issue as a solution is provided. Please reopen if not solved.

**Comment by sanmaozhao** [comment]
> I am closing this issue as a solution is provided. Please reopen if not solved.

It's working, thanks!
