### ISSUE TITLE
vue__cell border?

### ISSUE THREAD

**Issue by BerndtDavid** [antoniandre/vue-cal-v4#326]
First, thanks for the great work!

I have tried just about every style and cannot find where the border? around each cell can be removed.  

Also like to make each cell date content narrower to provide more horizontal space between each date.  See second image generated from another calendar component.

Using tailwind and Gridsome.

```
.vuecal__cell {
  box-shadow: none; 
  @apply rounded-full py-1 my-2 bg-jet-300 bg-opacity-10 text-jet-900 font-medium border-transparent;
}
```

![screen-shot](https://user-images.githubusercontent.com/32177667/91193084-ba316800-e6c4-11ea-9301-1d6fcacbff71.jpg)

![screen-shot-2](https://user-images.githubusercontent.com/32177667/91194816-7f303400-e6c6-11ea-979d-a219703efd6c.jpg)

**Comment by antoniandre** [comment]
Hi @BerndtDavid,

The border between cells is in `.vuecal__cell:before` as per this screenshot. 
so `.vuecal__cell:before {border: none;}` will remove it.
![image](https://user-images.githubusercontent.com/22971289/91370101-cf3b0200-e850-11ea-8a8d-0ea3f5edd5e2.png)

For the rest of the question you can apply some margin or padding on `.vuecal__cell` but not sure what you want.

Hope it helps. please close the issue if solved.

**Comment by BerndtDavid** [comment]
Thank you for the quick reply. Yes, that solved it.
