### ISSUE TITLE
Display dates in different colors depending on weekday (month view)

### ISSUE THREAD

**Issue by reina137** [antoniandre/vue-cal-v4#329]
Hi @antoniandre,

Thank you for the wonderful calendar component.

I was wondering if there's a way to display the calendar dates in different color, depending on weekday (red for Sundays, blue for Saturdays).
I've managed to achieve this for weekday headings, like in the image below.

<img width="960" alt="Screen Shot 2020-08-27 at 15 09 58" src="https://user-images.githubusercontent.com/47716062/91399348-ca8a4400-e878-11ea-998e-a882ab0e16ab.png">

`<template v-slot:weekday-heading="{ heading }">`
`  <span :class="{ 'txt-red' : heading.label == '日', 'txt-blue' : heading.label == '土' }">`
`  {{ heading.label }}`
`  </span>`
`</template>`

When I try to do the same thing with the cell-content slot, the cells just won't render.

`<template v-slot:cell-content="{ cell, heading }">`
`  <span class="vuecal__cell-date" :class="{ 'txt-red' : heading.label == '日', 'txt-blue' : heading.label == '土'}"> {{ cell.date }}</span>`
`</template>`

My Vuecal code:

`<vue-cal`
`locale="ja"`
`hide-view-selector`
`start-week-on-sunday="true"`
`active-view="month"`
`:events="eventsSelector" `
`:disable-views="['years', 'year', 'week', 'day']"`
`events-on-month-view="long" />`
`<template v-slot:weekday-heading="{ heading }">`
`<span :class="{ 'txt-red' : heading.label == '日', 'txt-blue' : heading.label == '土'}">{{ heading.label }}</span>`
`</template>`
`<template v-slot:cell-content="{ cell, heading }">`
`<span class="vuecal__cell-date" :class="{ 'txt-red' : heading.label == '日', 'txt-blue' : heading.label == '土'}">`
`{{ cell.date }}`
`</span>`
`</template>`
`</vue-cal>`

I would appreciate any help. Thank you in advance.

**Comment by antoniandre** [comment]
Hi @reina137,
Thanks for your feedback.
Yes this is definitely possible via CSS.

Look at the cell classes, the days of the week are added for this purpose:

![image](https://user-images.githubusercontent.com/22971289/93052361-58539500-f6a9-11ea-8fa3-5b69cf88b9a1.png)

So for instance, this rule will put all the weekend dates in red, as per screenshot. ;)

```css
.vuecal__cell--day6, .vuecal__cell--day7 {
    color: red;
}
```

Actually, you should also add the styling on the headers from CSS - easier and more performant:

```css
.vuecal--month-view .vuecal__heading:nth-child(6) .weekday-label,
.vuecal--month-view .vuecal__heading:nth-child(7) .weekday-label {color: red;}
```

Hope it helps.

**Comment by reina137** [comment]
Hi @antoniandre,

Thanks for your detailed answer! It totally worked for me.
These cell classes are very handy. 
Thank you for your help👍
