### ISSUE TITLE
Make separate .scss file

### ISSUE THREAD

**Issue by Paul-Todd** [antoniandre/vue-cal-v4#33]
Is there any reason the scss is embedded in the components? It would be nice to have a separate scss file that I can customize with the rest of the scss in my project.

**Comment by antoniandre** [comment]
Hi @Paul-Todd, I would be glad to allow sharing an scss file into the dist folder as well as the css currently shared.
If you have a guide or best practice for that please share!

**Comment by antoniandre** [comment]
Closed for inactivity.
If someone else needs this and can guide me I will do it. 
I could not find documentation about it.
