### ISSUE TITLE
Slot for a badge

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#330]
Hi @antoniandre,

is there a way to add a slot for a badge? I want to show when a booking was paid, like at the image below:

![Screenshot_20200906_151100_com android chrome~2](https://user-images.githubusercontent.com/12451362/92332367-e26d7f00-f053-11ea-9856-ae054178d770.jpg)

Thanks.

**Comment by antoniandre** [comment]
Hi @giulianimartini,

there are 2 ways to do this:
1. put this in the event content and do some CSS to align as you wish
2. use a custom event renderer (through the event slot) like in this example:
https://antoniandre.github.io/vue-cal/#ex--custom-event-rendering

Hope it helps.

**Comment by giulianimartini** [comment]
HI @antoniandre,

thank you.

I'll try those approaches and let you know if worked for me.

For now, I will close this issue.

Thanks again.
