### ISSUE TITLE
Load events on demand

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#331]
Hi @antoniandre,

is there a way to load events on demand?

I'm asking this because I don't want to load all events to my vue-cal all the time (the past events are not so important to be viewed). I just want to load events in a date range. For example, 1 month before the current date and 6 months after the current date.

This way we will gain in performance. Otherwise, the calendar will be full and slow. 

Thanks in advance.

**Comment by giulianimartini** [comment]
Note that I know I can fetch only the events in the specific date range, but I want to know if there's a way to do it only in vue-cal, even I fetch all events from server.

**Comment by antoniandre** [comment]
Hi @giulianimartini,

> Note that I know I can fetch only the events in the specific date range, but I want to know if there's a way to do it only in vue-cal, even I fetch all events from server.

That's right Vue Cal does not handle this: the data coming from the server is managed in your code outside of Vue Cal and you pass an array of events to Vue Cal, which will select only the events in view to display.

If you want to pre-filter the array of events coming from your backend, you could have another array of events, let's say `allEvents` and `filteredEvents` and only the `filteredEvents` would be passed to Vue Cal.

It's easy (and performant) to do this in a computed variable as Vue caches computed vars.

Something like that for instance:

```js
computed: {
    filteredEvents () {
        return this.allEvents.filter(event => event.start.getTime() >= new Date().getTime())
    }
}
```

This is just an example of pre-filtering all the events that are starting after the current time, you get the idea.

But if you want my opinion, I'd say you should not keep the other events around in the memory if you don't need them, so I would fetch the events in view on demand on each view change.
But I guess it depends on the speed of your server to deliver data and other parameters as well, so try the above and if it's faster for your scenario then voilà!

**Comment by giulianimartini** [comment]
Hi @antoniandre,

thank you.

Probably, I'll bring the events from the current date until 6 months ahead.
Otherwise, I would need to get the events of the current date each view change. I think this could be a little bit slow (maybe I can try this, since my server is from Amazon).

Thanks again.
