### ISSUE TITLE
Recurring Events

### ISSUE THREAD

**Issue by farrahdionisio** [antoniandre/vue-cal-v4#332]
Hi @antoniandre  
the weekdays recurring event is not working on the calendar. It's just repeating everyday instead of the specific days that I specified. Thank you

**Comment by giulianimartini** [comment]
Hi @farrahdionisio,

How are you doing it? Maybe a snippet of your code could help us to detect some inconsistency.

Just one question: which recurring events are you using? From vue-cal? 
I ask this because I think this feature is delayed and it isn't available right now.

I have developed my own solution using a PHP lib called _When_.

**Comment by farrahdionisio** [comment]
Hi @giulianimartini , 

I formatted my data like this, as per the docu: 
<img width="377" alt="Events___Appetiser_Apps" src="https://user-images.githubusercontent.com/70090364/92424033-ba962c80-f1b5-11ea-8e5d-ca6fc81f5a9b.png">

<img width="393" alt="CalendarEvent_vue_—_appetiser-apps-event" src="https://user-images.githubusercontent.com/70090364/92424181-2f696680-f1b6-11ea-801a-8f95e63e16b6.png">

<img width="485" alt="EventController_php_—_appetiser-apps-event" src="https://user-images.githubusercontent.com/70090364/92424211-4740ea80-f1b6-11ea-9376-5877445918cd.png">


I'm using the repeat then weekDays. Can I possibly customise it to achieve the recurring event? Thank you!

**Comment by giulianimartini** [comment]
Hi @farrahdionisio,

I think recurring events (repeat, weekdays and until) are not working yet.
This feature is delayed. You can check the documentation. Look for recurring events.

Besides that, note that you are passing `start` and `end` like a long range. In the documentation, you set `start` and `end` like one single day of difference (short) and then sets the `until` property to define the last date of the recurrence.

But as I said, I think this is not working yet ;)

**Comment by farrahdionisio** [comment]
Hi @giulianimartini, 

Alright thank you, I'll just wait for the feature to be released.

**Comment by antoniandre** [comment]
Thanks @giulianimartini for your help on this.

That's right @farrahdionisio, this feature is not ready yet, as per the documentation.
Please track its progress in this thread: #55.

Closing this issue now.
