### ISSUE TITLE
Year View Events

### ISSUE THREAD

**Issue by gathuku** [antoniandre/vue-cal-v4#333]
I need a little bit of assistance. I have a year view calender . The problem is am not sure how to pass montly events .
<img width="967" alt="Screen Shot 2020-09-08 at 3 43 54 PM" src="https://user-images.githubusercontent.com/26896865/92478473-dff15d80-f1ea-11ea-861c-a9c17eff6d1d.png">

Like i want to add an event for every month, How do i go about it?

```
        {
          start: 'January 2020',
          end: 'January 2020',
          title: 'Need to go shopping',
       },
        {
          start: 'February 2020',
          end: 'February 2020',
          title: 'Need to go shopping',
       },
    
```

**Comment by giulianimartini** [comment]
Hi @gathuku,

try passing the first day of each month for the `start` and `end` properties.
For example: For January, _2020-01-01 14:00_ (timestamp) or _2020-01-01_ (only date). For February, _2020-02-01_, and so on.

Hope it helps.

**Comment by gathuku** [comment]
@giulianimartini  thankyou but the option doen't work on year view. It only displays the events on first day of month when on month view.

**Comment by giulianimartini** [comment]
Oh, so you want one event for the entire month?
Set `start` as the first day of the month and `end` as the last one. So you will have only 1 event for the whole month.

I don't know how it will be shown on month view, but I think that's the only way. Maybe @antoniandre can guide you on this. 

Also, check [multiple day events](https://antoniandre.github.io/vue-cal/#ex--multiple-day-events) for more.

**Comment by gathuku** [comment]
@giulianimartini  Thankyou. The event is shown on every day on the month view when `start` is first day of month and `end` is last day of month, but not on the year view.

**Comment by giulianimartini** [comment]
Hi @gathuku,

I didn't get what you want. 
Do you want to show the events on year view? I think there's no way to do it. That's because you don't have a specific date to attach an event to be shown. 

What you can do is add custom events count like in https://antoniandre.github.io/vue-cal/#ex--custom-events-count

So you will have the number (count) of events in that month on year view. 

Hope it helps.

**Comment by gathuku** [comment]
@giulianimartini  Thankyou for the help. Am closing this.
