### ISSUE TITLE
DayView with hours-columns and minutes-rows

### ISSUE THREAD

**Issue by morrah** [antoniandre/vue-cal-v4#338]
Similar to a WeekView, where we have days-columns and hours-rows, would be awesome to have a DayView having hours-columns and minutes-rows for events with a high placement precision (60 rows x 1-24 columns).
And hideDayHours property for that view as hideWeekdays works for a WeekView.

**Comment by antoniandre** [comment]
Hi @morrah, thanks for your suggestion but I am sorry to say I will not add this feature in the codebase.
This would require a lot of extra code and refactoring of the library and is not a common need.
Adding this feature will penalize the other users in terms of library size increase and slight performance impact by adding new conditions. Sometimes I have to make that decision to keep the calendar slim and fast, hope it makes sense.

If you do need this feature you could fork the calendar and add the feature, but it will require a lot of work for that.
Cheers.
