### ISSUE TITLE
SplitDays options

### ISSUE THREAD

**Issue by nedovleonid** [antoniandre/vue-cal-v4#339]
Hi, @antoniandre 

From what I discovered, there is no option to tell in what days i have splitDays.
E.g for monday I would to have 3 columns and for tuesday only one (week view).

I think it would be a good idea to have this possibility.

**Comment by antoniandre** [comment]
Hi @nedovleonid,
Sorry for late reply and thanks for suggesting. 
No this is indeed not possible but I will not be adding this feature in a near future: it would require much more complexity in the codebase and this is admittedly an edge case. Sorry again 😐 I have to cut some features so it stays lean and performant! :) 
Hope it makes sense.
