### ISSUE TITLE
Start week on sunday

### ISSUE THREAD

**Issue by PauloKlixto** [antoniandre/vue-cal-v4#34]
Hello,
For my project I need for the week to start on sunday opposed to monday, and the documentation of this plugin doesn't say if it's possible.

**Comment by antoniandre** [comment]
Hi @PauloKlixto,

Currently vue-cal does not allow starting week from Sunday, but that is a feature I am adding to the to do list!

**Comment by girls-whocode** [comment]
Is there a possible way to look into modifying the module until the feature is added? I looked at the code, I see on line 2123, the Json string, although when digging into the code elsewhere, I see your calculations are based on Monday. Is there a simple fix that I am missing?

**Comment by antoniandre** [comment]
Hi @PauloKlixto, @jessicakennedy1028,

I have released a new version 1.34.0 that allows starting the week on Sunday with this option: `start-week-on-sunday` please refer to the API section https://antoniandre.github.io/vue-cal/#api.

@jessicakennedy1028, indeed all my calculations were based on starting on Monday.
I did a quick dev to help, I will do more tests tomorrow.

Hope it helps, 
let me know if you notice something unexpected!

**Comment by antoniandre** [comment]
Working example: https://codepen.io/antoniandre/pen/OdEgEq

**Comment by PauloKlixto** [comment]
@antoniandre 
It worked perfectly!
Thanks for to add this feature.

**Comment by Taeeon-kim** [comment]
> Hi @PauloKlixto, @jessicakennedy1028,
> 
> I have released a new version 1.34.0 that allows starting the week on Sunday with this option: `start-week-on-sunday` please refer to the API section https://antoniandre.github.io/vue-cal/#api.
> 
> @jessicakennedy1028, indeed all my calculations were based on starting on Monday. I did a quick dev to help, I will do more tests tomorrow.
> 
> Hope it helps, let me know if you notice something unexpected!

it's 2024, but still it isn't mentioned in an official document of Vuecal, I expect new functions should be noted in the official site

**Comment by antoniandre** [comment]
Hey @Taeeon-kim, It's written in the API section. It does not need more because the name of the prop is very descriptive.
I'm currently working on V5 and the prop remains the same. I'll do an interactive example to showcase most of the props in v5.
