### ISSUE TITLE
The width of some events seems miscaculated

### ISSUE THREAD

**Issue by hannory** [antoniandre/vue-cal-v4#347]
Hello, I'm very impressed your amazing scheduler.

I'm asking because an issue I haven't resolved myself.
I put 'vue-cal' scheduler on bootstrap-vue modal.
As you can see, the width of some events looks not proper.

![image](https://user-images.githubusercontent.com/56330250/97955360-5a082200-1de9-11eb-88f2-23a54dcf51b7.png)
07:31-07:36 apple, banana, berry should have 33% width each
![image](https://user-images.githubusercontent.com/56330250/97955599-e31f5900-1de9-11eb-8d66-e401da1aba05.png)
07:53-07:55 apple, banana, berry should have 33% width each

This is my code for vue-cal.
`<vue-cal small active-view="day" :disable-views="['years', 'year', 'month', 'week']" hide-weekends overlaps-per-time-step style="height: 640px" :events="events" :on-event-click="onEventClick" :time-from="2 * 60" :time-to="12 * 60" :time-step="1" />`

If I delete 'overlaps-per-time-step' option, the width looks more complex like below.
![image](https://user-images.githubusercontent.com/56330250/97955910-b586df80-1dea-11eb-9d2f-06c9dca23fee.png)

Can you give me any hint to make it better?

**Comment by hannory** [comment]
vue : 2.5.2
vue-cal : 3.8.1

**Comment by antoniandre** [comment]
Hi @hannory, thanks for your feedback.
Can you provide the events definition or ideally a reproduction link please.
That will allow me see the problem and investigate if needed.
Thanks!

**Comment by hannory** [comment]
HI @antoniandre, thanks for your concern.
I can reproduce the issue only with 3 events.
I tried to upload a whole test project on a repository, but failed with an unknown reason.
But I think you can reproduce with these codes.

html (template)
`<vue-cal id="vuecal" small active-view="day" :disable-views="['years', 'year', 'month', 'week']" hide-weekends style="height: 640px" :events="events" :on-event-click="clickOnEvent" :time-from="8 * 60" :time-to="23 * 60" :time-step="1" @view-change="logEvents('view-change', $event)" :time-cell-height="timeCellHeight" @ready="scrollToCurrentTime"/>`

script - export default - data - return
`selectedEvent: {},
      events: [
          {
              start: '2020-11-06 14:20',
              end: '2020-11-06 14:29',
              title: 'apple',
              class: 'apple'
          },
          {
              start: '2020-11-06 14:20',
              end: '2020-11-06 14:22',
              title: 'banana',
              class: 'banana'
          },
          {
              start: '2020-11-06 14:27',
              end: '2020-11-06 14:33',
              title: 'berry',
              class: 'berry'
          }
      ]`

script - methods
`logEvents: function(message, event) {
    },
    scrollToCurrentTime: function () {
    }`

style
`    .vuecal__event {
        cursor: pointer;
    }
    .vuecal__event-title {
        font-weight: 600;
    }
    .vuecal__event-time {
        font-size: 0.75em;
    }
    .vuecal__event.apple {background-color: rgba(164,230,210,.8);border: 1px solid rgb(72, 216, 173);color: #666666;overflow: visible;}
    .vuecal__event.banana {background-color: rgba(255,179,0,.6
    );border: 1px solid rgba(255,179,0);color: #666666;overflow: visible;}
    .vuecal__event.berry {background-color: hsla(0,100%,70%,.70);border: 1px solid hsla(0,100%,70%);color: #666666;overflow: visible;}`

capture
![image](https://user-images.githubusercontent.com/56330250/98350800-29c9b900-205f-11eb-900d-e672dc6dd346.png)

As you can see, the position and the width of the apple event box should be corrected.
Could you please examine it?

**Comment by antoniandre** [comment]
I see what you re talking about.
This is a known imperfection let's say. Here is the thread about it:
https://github.com/antoniandre/vue-cal/issues/150#issuecomment-517541340

So even if it looks obvious while looking where to best position the events (in this case berry should be on the left under banana and all the events should be 50% width for the best render), I haven't found a better algorithm.

I am quite concerned about performance, I don't want to overkill the display, but if you want have an idea and want to try your luck on refactoring this part of the calendar that would be awesome!

Let me know if you want to contribute, we can get in touch via email (my email is in the package.json file), otherwise I will close this issue. :)

**Comment by hannory** [comment]
Thank you for your reply and efforts about this project.
I understood. Currently, I don't have a better idea about the algorithm. If I come up with a good idea, I will contact you.

**Comment by antoniandre** [comment]
Thanks. Sounds good, I'll let you know also if I find a better way.
Closing the issue now!
