### ISSUE TITLE
Drag and drop event - control title

### ISSUE THREAD

**Issue by gsaada** [antoniandre/vue-cal-v4#349]
How can I set title for drag and drop created events

**Comment by antoniandre** [comment]
Hi @gsaada,

If you are talking about the drag creation:
You can have a look at the second part of the `#3` example in the documentation: https://antoniandre.github.io/vue-cal/#ex--other-event-creation-methods. It is explained how to provide a callback at for a drag creation.

So if you want to allow the user to edit the title, you can add a dialog on drag create callback exactly like in the example, or if you want to set the event title programmatically without user interaction, you can use the function `:on-event-create="onEventCreate"` and set the title in the function, like so:

```js
onEventCreation (event) {
    event.title = 'Event title'
}
```

**Comment by antoniandre** [comment]
Closing the issue due to inactivity. Please reopen if not solved!
