### ISSUE TITLE
Use <script> tag Calendar not working

### ISSUE THREAD

**Issue by slouchy** [antoniandre/vue-cal-v4#35]
It's my code

https://codepen.io/slouchy592/pen/xMbYbv

I via vue-cal with <script> tag, but there is no calendar.

How can I use vue-cal with <script> tag ?

thanks

**Comment by antoniandre** [comment]
Hi @slouchy,

To use vue-cal with script tag you need to define the component in your vue instance like this: 
https://codepen.io/antoniandre/pen/pGJWjL

```js
new Vue({
  components: { 'vue-cal': vuecal },
  el: '#container',
  data: {
    value: '',
  },
});
```

Thank you for noticing, I will update the documentation soon!

**Comment by slouchy** [comment]
Thank you very much!
