### ISSUE TITLE
周视图中能怎么在星期几 和 日期前添加月份呢

### ISSUE THREAD

**Issue by dadaqiao** [antoniandre/vue-cal-v4#351]
![image](https://user-images.githubusercontent.com/46733755/98905070-c1168c80-24f5-11eb-81c3-b1c9e5b53277.png)

**Comment by antoniandre** [comment]
Sorry @dadaqiao, please reopen in english, https://github.com/antoniandre/vue-cal/issues/345#issuecomment-716093094

Everybody should benefit from this issue discussion, and it's easy enough to paste a Google translation.
