### ISSUE TITLE
How to customize my own language locale

### ISSUE THREAD

**Issue by FuGangqiang** [antoniandre/vue-cal-v4#352]
```
<vue-cal :time="false" small active-view="year" locale="zh-cn" />
import VueCal from 'vue-cal'
import 'vue-cal/dist/i18n/zh-cn.js'
import 'vue-cal/dist/vuecal.css'
```

how can I use my custom `i18n/zh-cn.js`?
I want to change the content of `zh-cn.js`.

**Comment by antoniandre** [comment]
Hi @FuGangqiang,
This is not possible. 
But many slots are available to customize what should be customizable.
What do you want to change?

**Comment by FuGangqiang** [comment]
I want to change the weekday label,
for example:

`Monday` -> `First`

**Comment by antoniandre** [comment]
Hi @FuGangqiang,
This is now an option in version 3.9.0.
Check this demo: https://codepen.io/antoniandre/pen/rNLgBKo?editors=1010

Docs: https://antoniandre.github.io/vue-cal/#ex--internationalization > alternative.

Hope it helps.

**Comment by FuGangqiang** [comment]
thanks, this is what I want!
