### ISSUE TITLE
How to change the background color in a day in a fractional way?

### ISSUE THREAD

**Issue by alfonso2254** [antoniandre/vue-cal-v4#355]
Hi,
I love Vue-cal, however I need to select a time range in the morning and another in the afternoon of a day,
scenario:
The doctor sees his patients on Monday from 09:30 to 11:30 and from 13:30 to 16:30.

I can use special hours but when I use it this way
          {
          1: {from: 8.5 * 60, to: 11.5 * 60, class: 'open'},
          1: {from: 13.5 * 60, to: 16.5 * 60, class: 'open'},
          }
it only takes me the second element

Any way you can help me?

**Comment by antoniandre** [comment]
Hi @alfonso2254,

Thanks for your feedback.
I see. Currently the special hours only take 1 range per day of the week.

As an immediate workaround you can either: 
- use special hours from 8.5 to 16.5 and have a background event on all the lunches
- create 2 background events every day (one for the morning and 1 for the afternoon)
- have 2 synced Vue Cal instances, one for the morning and 1 for the afternoon, and use special hours in both

On my end, I will see if I can add multiple segments to the daily special hours to help you out, if it does not impact the performance too much. 
Will let you know. ;)

**Comment by antoniandre** [comment]
Hi @alfonso2254, this is now possible in version 3.10.0! https://antoniandre.github.io/vue-cal/#ex--special-hours
Hope it helps.

**Comment by antoniandre** [comment]
Closing this issue as the feature is released. Please reopen if not solved!
