### ISSUE TITLE
cell-content > "vuecal__no-event" with splits

### ISSUE THREAD

**Issue by DevDast** [antoniandre/vue-cal-v4#356]
Hi,
First of all, thank you for this wonderful component!
it must have been a huge job!
I am having difficulty changing the text of "vuecal__no-event" when the columns are slit

I put this in the component but splits disapear when I do that :(

`<template v-slot:cell-content="{ cell, view, events, goNarrower }">
    <span class="vuecal__no-event" v-if="!events.length">Aucun RDV</span>
</template>`

Is this a bug or is it coming from me ?

**Comment by antoniandre** [comment]
Hi @DevDast,
Thanks for your feedback, I appreciate it!

This is not supposed to happen, here is a Codepen demo with what you want I think.
https://codepen.io/antoniandre/pen/vYXBxmZ?editors=1010

By the way, if you only use the `cell-content` slot for the no event message, you can simply use the `no-event` slot instead.
`<template #no-event>Aucun RDV</template>`

Hope it helps, let me know if you have more questions.

**Comment by DevDast** [comment]
Thank you very much for your help, I learn more every day :)
Amazing component !
