### ISSUE TITLE
umd build broken?

### ISSUE THREAD

**Issue by manelclos** [antoniandre/vue-cal-v4#357]
Hi,

Build 3.9.0 works great, but anything after would just fail:
```
  <script src="https://unpkg.com/vue-cal@4.0.0"></script>
```
```
vue-cal@4.0.0:1 Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (vue-cal@4.0.0:1)
    at a (vue-cal@4.0.0:1)
    at 00ee (vue-cal@4.0.0:1)
    at vue-cal@4.0.0:1
    at vue-cal@4.0.0:1
    at vue-cal@4.0.0:1
```

See it here: https://codepen.io/manelclos/pen/WNGeeve

**Comment by antoniandre** [comment]
Hi @manelclos,
The build is not broken from version 4+ it's only for Vue 3, and not compatible with Vue 2.
Here is a demo with Vue 3 and latest Vue Cal 4.x: https://codepen.io/antoniandre/pen/vYXBxOg?editors=1010

Make sure to check the release notes when upgrading, especially when upgrading to a major version (Vue Cal 3 to 4)!
https://antoniandre.github.io/vue-cal/#release-notes

Hope it helps.
You can reopen the issue if not solved.
