### ISSUE TITLE
Week view without events section and "today" class in headings 

### ISSUE THREAD

**Issue by witpok** [antoniandre/vue-cal-v4#36]
Hi, thanks for this great lib, can you tell me if there is by any chance an option:
1) to hide (beside css-way) the event columns in week view? I need only the top section - the headings - rendered. 
2) In the same week view, I need to have "today" class on today's date to be able to style it. So the vuecal__heading should have today class too, while now only corresponding vuecal__cell underneath it has it.

Thanks!

**Comment by antoniandre** [comment]
Hi @witpok, 
Currently there is no option to hide the main content (other than CSS), I wouldn't suspect someone would ask for that haha.

I will add that option later today along with a class on days of the week headings.
Will let you know here.

**Comment by antoniandre** [comment]
Hi @witpok, 

New option hideBody is now available  in version 1.24.0 along with today's css class on weekdays headings. 
https://antoniandre.github.io/vue-cal/#release-notes

Hope it helps!

**Comment by witpok** [comment]
This is wonderful, thank you very much! Testing it right away!
