### ISSUE TITLE
is it possible to change the names of weekdays? such as Monday to Hello World?

### ISSUE THREAD

**Issue by MiguelCalleja** [antoniandre/vue-cal-v4#362]

**Comment by antoniandre** [comment]
Hi @MiguelCalleja,
Sorry for the late reply. This is possible if you provide your own locale. 
It's quite easy, look at this thread and answer: https://github.com/antoniandre/vue-cal/issues/352#issuecomment-730044329

Hope it helps!

Please reopen the issue if not solved.
