### ISSUE TITLE
Today button in the title slot changes active-view

### ISSUE THREAD

**Issue by kkojot** [antoniandre/vue-cal-v4#363]
**What I want to achieve:**
I want to have a _set today_ custom button near the title bar. 

**What I did to achieve that:**
I've tried to move the default one with CSS, but with no success. I've decided to put my custom button in the title slot, but it behaves unexpectedly. 

**Steps to reproduce the issue:**
Please open the codepen https://codepen.io/kkojot/pen/dypzBjV and change the current day with arrows. Then click the `set today` button placed near the title bar. You will see that the `active-view` is changed to week, which is not expected behavior. 
If you do the same with the `today default button` or `select today by REF` (which calls the same method as the `select today` button) the `active-view` is not changing.

**Expected solution:**
Well, maybe putting the `select today` button in the title slot is not the best idea, I think it should work fine. If you can provide me a CSS code of how to move the default button closer to the title, it will satisfy me too ;-)

**Comment by kkojot** [comment]
I think it acts like that because clicking the title takes to week view. Setting the `clickToNavigate` and `dblclickToNavigate` to false didn't solve the issue, so maybe the problem is somewhere there.

**Comment by antoniandre** [comment]
Hi @kkojot,
Thanks for your detailed explanation and reproduction link.
But it's a bit confusing what you want to achieve. So if I understand well, you want:
- to have a today button that takes you to today's date without changing the view from week view (so it should only navigate to the current week and select today's date).
- You also want to place this today button where you placed the "set today" button in your Codepen.

If that's the case, here is one way to do it using the default today button like in: https://antoniandre.github.io/vue-cal/#ex--adding-a-today-button. Add this CSS:

css

```css
.vuecal .vuecal__title {flex: 0;white-space: nowrap;}
.vuecal__arrow--prev {margin-right: auto;}
.vuecal__arrow--next {margin-left: auto;}
```

Another way to do it is to place a custom button like you did in the title slot, but with this click handler: `@click="selectedDate = new Date()"` just like the `another today button` from the same documentation example: https://antoniandre.github.io/vue-cal/#ex--adding-a-today-button

Hope it helps.

**Comment by kkojot** [comment]
Thanks @antoniandre, the provided css works and solves the issue. The second one is the same as I did, and it changes the `active-view`.
