### ISSUE TITLE
Calendar Height is not Responding

### ISSUE THREAD

**Issue by i-am-mgs** [antoniandre/vue-cal-v4#364]
Hi, I'm implementing this calendar on a site I'm working on and I'm having an issue with the height of the calendar.

The reason I need to fix the height on the container is that the content within each event in the calendar is too large for the height of the event meaning it is cutting out the content. Is there a workaround for this?

Here is the code I have for the calendar
```
<div class="sections-container" style="width: 1000px; height: 1000px;" id="VueRoot">
	<vue-cal
		ref="calendar"
		:events="events"
		style="width: 1000px; height: 1000px"
                :time-from="6.5 * 60"
		:time-to="22.5 * 60"
		:snap-to-time="15"
		:disable-views="['years', 'year', 'month', 'day']"
		hide-view-selector
		@view-change="getCalendarEvents()"
	/></vue-cal>
</div>
```

I am also setting the following CSS to style the calendar:

```
/* Calendar
---------------------------------------------*/

/* Calendar Theme */
.vuecal__title-bar {
	background-color: #062343;
	color: #fff;
}

.vuecal__arrow {
	color: #fff;
}

.vuecal__cell--selected {
	background-color: rgba(235, 235, 255, 0.5);
}

.vuecal__event {
	display: flex!important;
	flex-direction: column!important;
	justify-content: center !important;
}

/* Calendar Event: Classes */
.vuecal__event.class-event {
	background-color: rgba(255, 102, 102, 0.9);
	border: 1px solid rgb(233, 82, 82);
	color: #fff;
}

/* Calendar Event: Party Bookings */
.vuecal__event.party-booking-event {
	background-color: rgba(105, 157, 240, 0.9);
	border: 1px solid rgb(89, 147, 240);
	color: #fff;
}

/* Calendar Event: Holiday Clubs */
.vuecal__event.holiday-club-event {
	background-color: rgba(253, 156, 66, 0.9);
	border: 1px solid rgb(233, 136, 46);
	color: #fff;
}
/* Calendar Event: Gym Bookings */
.vuecal__event.gym-booking-event {
	background-color: rgba(163, 163, 163, 0.9);
	border: 1px solid rgb(138, 138, 138);
	color: #fff;
}
/* Calendar Event: Staff Holidays */
.vuecal__event.staff-holiday-event {
	background-color: rgba(191, 140, 243, 0.9);
	border: 1px solid rgb(166, 93, 238);
	color: #fff;
}
```

The image below is the problem I am experiencing so you can see why I want to change the height of the calendar.

![Screenshot 2020-12-22 at 16 46 12](https://user-images.githubusercontent.com/44160752/102912403-3ff7d100-4475-11eb-936f-8dc47c709a5c.png)

Thank you in advance, I hope you're well :)

**Comment by antoniandre** [comment]
Hi @discovery-mark,

If I understand well you want to increase the time slot height (increase the height between 11:30 and 12:30 for instance).
If that's what you are looking for you can use the `time-cell-height` option.

https://antoniandre.github.io/vue-cal/#ex--timeline-tweaking

**Comment by i-am-mgs** [comment]
@antoniandre 

Thank you for your response.

This has solved my issue :)
