### ISSUE TITLE
Bug with API disable-days

### ISSUE THREAD

**Issue by MarcoVdn** [antoniandre/vue-cal-v4#367]
I found a bug about the API written above. If you decide to disable the first day of whatever month automatically will be disabled not only the day but the entire month that you can see in the year view. 
Here below an example:
I decide to disabled the specific date: 1st April 2020  
![Screenshot_20201223_161702](https://user-images.githubusercontent.com/17857190/103011485-4e5bf080-453a-11eb-9340-4e9f91d0fa86.png)
Here the result: in the month view the 1st of April is disabled but in the year view is completed disabled April.
![Screenshot_20201223_161731](https://user-images.githubusercontent.com/17857190/103011521-5ddb3980-453a-11eb-95de-d414ce071cdb.png)
![Screenshot_20201223_161758](https://user-images.githubusercontent.com/17857190/103011552-6df31900-453a-11eb-9823-e7cceff1bc86.png)
This happen when you decide to disable the first day of whatever month but in the worst case, if you disable the 1st January will be disabled not only the day and entire month but also, in the years view, the entire year. As you can see in the picture below where it was disabled the 2020-01-01. 
![Screenshot_20201223_162213](https://user-images.githubusercontent.com/17857190/103011909-08535c80-453b-11eb-9e9a-a12308286463.png)

**Comment by antoniandre** [comment]
Thanks for reporting @MarcoVdn,
I'll release a patch soon.

**Comment by antoniandre** [comment]
Should now be fixed in Version 3.9.1.
Let me know if you see any related problem.
