### ISSUE TITLE
vue-cal is not compatible with vite v2.x

### ISSUE THREAD

**Issue by izadiegizabal** [antoniandre/vue-cal-v4#369]
## Description

It looks like `vue-cal` distributes a webpack-bundled dist file that attempts to `require('vue')` but Vue 3 no longer has default exports so it breaks when trying to use with Vite, the new recommended development tool for Vue 3, as Evan You pointed in the issue I opened there:

https://github.com/vitejs/vite/issues/1408#issuecomment-756312585

In vite v1.x, this could be worked around by adding `vue-cal` to `optimizeDeps.include` property in the `vite.config` file; but with v2.x, this doesn't work anymore and it gives the following error in the browser once vite finishes building:

`Uncaught SyntaxError: The requested module '/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=3.0.5' does not provide an export named 'default'`

I would be nice if `vue-cal` could be updated to be compatible with Vite since it seems to be the new default tool moving forward with Vue. Thank you!  

## Reproduction

I've created a small [repo](https://github.com/izadiegizabal/vite-optimizeDeps-issue) to see the issue. By running `npm run dev` the error message should appear in the browser.

## System Info

- `vue-cal` version: 4.2.0
- `vite` version: 2.0.0-beta.9
- Operating System: macOS 11.1 (Big Sur)
- Node version: 14.9.0
- Package manager (npm/yarn/pnpm) and version: npm 6.14.10

**Comment by izadiegizabal** [comment]
It looks like with the latest beta (`2.0.0-beta.66`) `vue-cal` is working again, but it still needs the Vite dep optimisation 😅

**Comment by lokkilok** [comment]
I've encountered the same, or similar, issue when forking the `next` branch of `vue-cal`. When I install `vue-cal` from the npm service (`npm install vue-cal@next`), building my app with vite works fine. But when I build `vue-cal` locally on my machine and then install with `npm ../../vue-cal` and then build with vite I get: 
```
error during build:
Error: 'default' is not exported by ../../vue-cal/dist/vuecal.common.js, imported by src/App.vue
```
BTW my vue-cal dist folder does not have an esm-bundler file, it has .common and .umd filles/bundles.

**Comment by izadiegizabal** [comment]
@lokkilok try adding that `vuecal.common.js` to  `optimizeDeps` in the vite config file, it helped in my case.

```
export default {
  plugins: [vue()],
  optimizeDeps: {
    include: ['vue-cal/dist/vuecal.common.js']
  }
};
```

More info: https://vitejs.dev/config/#optimizedeps-entries

**Comment by lokkilok** [comment]
@izadiegizabal Thanks for the tip! 
Alas, it doesn't seem to help. Note that earlier, when installing the official `vue-cal@next` from (the) npm (service), I did not need that entry in the `optimizeDeps.include` at all. But when I install a local build of `vue-cal` I cannot use it within vite.

@antoniandre do you do anything special when building the @next version of the npm package?

**Comment by antoniandre** [comment]
Hi folks, this thread is old and since the time Vue Cal is now supporting ES Modules, Vite and Vue 3. And the next branch has been merged to main which means Vue Cal's default is now the Vue 3 build.

https://stackblitz.com/edit/vuecal-vite?file=src%2FApp.vue

Please reopen if not solved.
