### ISSUE TITLE
Error: hasTouch is not defined on beforeDestroy  hook

### ISSUE THREAD

**Issue by akki-jat** [antoniandre/vue-cal-v4#37]
This error `hasTouch is not defined` is popping whenever vue-cal component is destroying.
I see you have fixed this problem in commit 88932ee60130c73623510662fc26e897658cfbb8.

So, I think it is still not updated in npm. Can you update it?

### Reproduction Link
[https://codesandbox.io/s/n9xwkpjp00](https://codesandbox.io/s/n9xwkpjp00) - just hit destroy button and see console.

**Comment by antoniandre** [comment]
Hi @akki-jat, 
Thanks for noticing and sorry I forgot to rebundle!
Now fixed in version 1.23.0 👌
