### ISSUE TITLE
Suggestion: Inline styles for events

### ISSUE THREAD

**Issue by donmb1** [antoniandre/vue-cal-v4#373]
I can see that the vue-cal philosophy is to separate functionality and design.
However, I'd find it a useful feature if one can also define inline styles for events, the same way we can define it for the `vue-cal` component. Background color would be a specific usecase:

```
{
      start: '2018-11-19 18:30',
      end: '2018-11-19 19:15',
      title: 'Dentist appointment',
      content: '<i class="v-icon material-icons">local_hospital</i>',
      class: 'health',
      split: 2,
      style: 'background-color: #00000'
}
```

All the best to you and keep on the great work.

**Comment by Csandori** [comment]
Hi!

You can do it with event slot. 
Check this:
https://jsfiddle.net/9a7ptq12/

**Comment by antoniandre** [comment]
Exactly @Csandori! 👍 

Thanks @donmb1 for the feedback! 
Here is yet another example to have different styles per events :)
https://codepen.io/antoniandre/pen/XwNdQz

Let us know if it helps.

**Comment by antoniandre** [comment]
Closing the issue due to inactivity.
Please reopen if not solved.
