### ISSUE TITLE
Delete popup shows without hold when prop time is false

### ISSUE THREAD

**Issue by akki-jat** [antoniandre/vue-cal-v4#38]
Hi,
when time prop is set to `false`, delete popup opens without hold

### Reproduction link
[https://codepen.io/akki-jat/pen/JxGdzg](https://codepen.io/akki-jat/pen/JxGdzg) - just click to edit

**Comment by antoniandre** [comment]
Hi @akki-jat, Thanks for the fix! 
In your codepen to get the latest version change the vue-cal external link to `https://unpkg.com/vue-cal@latest`
