### ISSUE TITLE
Selecting a disabled date

### ISSUE THREAD

**Issue by samyrataylor** [antoniandre/vue-cal-v4#384]
Hi Antoni,

When using disabled (min/max) dates they show as disabled, but you're still able to click them. The cell-focus event is triggered, it shows as selected. I believe it should not be able to be selected, thus cell-focus should not fire.

I think all that would be needed is checking when the cell is clicked, check if it's disabled.

Thanks

**Comment by antoniandre** [comment]
Hi @samueljtaylor, thanks for reporting and fixing.
I actually left it focusable thinking it's nice to still be able to highlight, but I understand that you could rely on the focus event not to be sent. So it makes sense, #385 is merged and released!

**Comment by motea927** [comment]
Has fixed this issue for vue 3 verison? I still occur this issue with vue-cal@next

**Comment by samyrataylor** [comment]
@motea927 @antoniandre 
When I submitted the PR it was only for vue-cal@master but I can submit a new one for vue-cal@next
