### ISSUE TITLE
[Feature Request] Show time when hover cell time

### ISSUE THREAD

**Issue by thanhchuongbmd** [antoniandre/vue-cal-v4#389]
How to show time when hover and click cell time in vue cal look like ? 
<img width="1142" alt="Screen Shot 2021-04-05 at 3 38 52 PM" src="https://user-images.githubusercontent.com/67777599/113555502-3873c680-9625-11eb-9d4d-649e09cce91f.png">

**Comment by vesper8** [comment]
I would this as well.. or having the ability to have a customizable "+" appear on the cell as you hover it.. @thanhchuongbmd did you figure out how to achieve any kind of hover effect on the cells?

**Comment by rubjo** [comment]
Best bet is probably to use a third-party tooltip library and set that up for every visible `. vuecal__event`.

**Comment by antoniandre** [comment]
Hi @thanhchuongbmd,

Thanks for the suggestion and sorry for the long delay.
This is now an option in the latest Vue Cal for Vue 3. 
You can style the time labels with CSS to hide everything and only show on hover if you prefer. :)

https://antoniandre.github.io/vue-cal/#ex--show-time-in-cells

<img width="847" alt="image" src="https://user-images.githubusercontent.com/22971289/187046434-75355296-cada-4d09-9ada-c5f07cfed77b.png">


Please reopen if not solved.
