### ISSUE TITLE
onEventClick not firing?

### ISSUE THREAD

**Issue by mikeerickson** [antoniandre/vue-cal-v4#391]
I am not sure if I am expecting something different, but when I add an `onEventClick` method, nothing occurs when selecting date (in Month view) or timeline item (in Day view).

```vue
<vue-cal ... @onEventClick="onEventClick" ... />
```

See the following pen

https://codepen.io/codedungeon/pen/zYNdjEo?editors=1010

Further, maybe not the case with many of your users, but the codepen examples which are using Pug are difficult to follow without any Pug experience :-)

**Comment by mikeerickson** [comment]
OK, with some trial and error, I have found that that actual event I am looking for is `cell-clicked`

```vue
<vue-cal ... @cell-clicked="onEventClick" ... />
```

As of writing, I am still not sure what the `onEventClick` event is used for?

**Comment by samyrataylor** [comment]
@mikeerickson I had an issue figuring that out too but rather than listening for the event you need to bind to `onEventClick`

If you change `@event-click="onEventClick"` to `:on-event-click="onEventClick"` in your pen example, it works. 

Hope this helps!

**Comment by mikeerickson** [comment]
@samueljtaylor  Yes, this does indeed work. And if I had looked at documentation closer, I would have seen this as well :-)   Curious why using a `bind` as opposed to `event` is curious?  

I  have seen this a couple other times in various Vue components I have used, but can't determine why this was done?  There has to be a logical reason

**Comment by samyrataylor** [comment]
@mikeerickson I'm glad that worked! In terms of reasoning behind using one over the other, I'm not sure. But I did find out that you can bind to `on-event-click`  or  listen for an `event-focus` event.

So if you prefer using events you can do either `:on-event-click="someFunction"` or `@event-focus="someFunction"` and it seems to work both ways. 

So far the only difference I've found is binding to `on-event-click` gives you access to the clicked event as well as the `MouseEvent` whereas listening to `event-focus` only gives you access to the event details.
