### ISSUE TITLE
Today button event?  :selected-date binding is not updated

### ISSUE THREAD

**Issue by mikeerickson** [antoniandre/vue-cal-v4#392]
Is there an event that is fired when the today button is clicked?

I have noticed that the :selected-date binding is **NOT** updated when the today button is clicked, thus I have no way of to determine when it has been clicked so that i can update the schedule.

```vue
<vue-cal today-button :selected-date="currentDate" ... />
```

If I click the `today` button, the `currentDate` value is not updated?

I realize I can create my own today button, but the current implementation is just fine provided I can get it to update the bound value (or there is an associated event)

**Comment by antoniandre** [comment]
Hi @mikeerickson, sorry for late reply.

If you want to keep your `currentDate` variable in sync, you should update it on `@view-change` and `@cell-focus`.
https://antoniandre.github.io/vue-cal/#ex--emitted-events

This will also work with the built-in today button.
Or like you say, you could use the today button slot to emit events and update the variable yourself. Up to you.

To simplify things, I have added a two-way binding on the `selected-date` on the Vue 3 build. So you will now be able to do `v-model:selected-date` if you use Vue 3. :)

Cheers.
