### ISSUE TITLE
[Feature Request] Add Divider between Time Slot

### ISSUE THREAD

**Issue by filippodicostanzo** [antoniandre/vue-cal-v4#395]
Is possible to have a divider bewtween two time slot with a custom title?

![image](https://user-images.githubusercontent.com/19286012/114685478-317a4180-9d12-11eb-8b8a-024a86bb8768.png)

For example is possible to have a empty space like a divider between 10.00 and 10.30 with a custom text or title?

Thank you for your excellent WORK!

**Comment by rubjo** [comment]
Probably best to implement by adding a (background) event and then style that the way you want?

**Comment by antoniandre** [comment]
Hi @filippodicostanzo,

Sorry for late reply. I agree with @rubjo. Or you could also use `special-hours` if that's always the same place every week.
You can even set text with a CSS pseudo element if there is not much business logic.

You probably moved on, but if not, please reopen with more details and a reproduction link. :)
