### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by andreykko** [antoniandre/vue-cal-v4#4]
Hi. first of all thanks for the useful library!

In the documentation, you have an import example `import { Vuecal } from 'vue-cal'`
But we need to use general import as `import Vuecal from 'vue-cal'`. 
Checked in the nuxt.js framework. If import like this `import { Vuecal } from 'vue-cal'` then Vuecal variable will be undefined.

**Comment by antoniandre** [comment]
Hi @andreykko,
Thank you for that! 
I corrected the typo.
