### ISSUE TITLE
All Day events in separate bar on week & day views

### ISSUE THREAD

**Issue by antoniandre** [antoniandre/vue-cal-v4#40]
As per the original request https://github.com/antoniandre/vue-cal/issues/21, 
the idea is to have all the "all day events" separated in a top bar like on this image:

<img width="859" alt="screenshot 2019-01-07 04 24 59" src="https://user-images.githubusercontent.com/22971289/51836226-eb647d80-2353-11e9-8442-d1895e1ecc23.png">

**Comment by ArjenSwBase** [comment]
Hey @antoniandre 

I am assuming this calendar project is a hobby/fun project for you, so I don't really wanna come across pushy. But in our project we would need this functionality in a week or so. I would appreciate it a lot if you would pick this up!

Thanks a lot for your hard work!

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, 
As you point it it is a side project and I do also have a full time job. 
I will start this feature soon this week. But if you don't want to risk to be late you should maybe consider starting this feature in a fork!

**Comment by antoniandre** [comment]
I'll do the base tonight and we will see how long it will take from there.

**Comment by ArjenSwBase** [comment]
I'll see if I can continue on your base when I have some time. I've tried earlier but couldn't figure it out thats why I opened an issue for it! ;)

Thanks!

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, 
It is well started and already showing up nicely! (you can try in the dedicated branch)

What is not done yet is:
- implement multiple days in this new area (events across multiple cells)
- check all the other features in this new top bar, and make sure it all works. I have noticed the delete feature is not working well

There is still a fair bit of work before releasing a stable version but if you don't need all that you will be able to fork and take shortcuts.

I will continue on that tomorrow

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, 
I have released a first stable version https://antoniandre.github.io/vue-cal/#ex--all-day-events.
Displaying multiple day events across multiple cells is not done yet. I will only start that next week.
But if you have multiple days to display, they will be split into daily segments and repeated on each day it needs to be.

This should already help you for your project. 👌

**Comment by ArjenSwBase** [comment]
Hi @antoniandre 

Amazing work! Thank you so much. I can indeed already use this for my project.

**Comment by antoniandre** [comment]
if anyone knows a (short length) translation for 'All day' text for the following languages: **de, es, hr, ka, nl, pl, pt-br, ru, sk, sv, zh-cn**, please contribute that file (in i18n/ folder) or write a comment here!

Thanks! 👍

**Comment by ArjenSwBase** [comment]
For Dutch(nl) it would be "Hele dag"

**Comment by davidgraeff** [comment]
German: "Ganztätig"

**Comment by antoniandre** [comment]
> German: "Ganztätig"

Is there a shorter word or multiple shorter words to fit it in small cell?
I don't want to truncate words but I can display on up to 3 lines.
Would "den ganzen Tag" be a correct translation as it fits on 3 lines? Ideally would be 1 or 2 lines.

![image](https://user-images.githubusercontent.com/22971289/53246458-e30a2300-3704-11e9-807b-a79e0f170cf5.png)

**Comment by davidgraeff** [comment]
"Den ganzen Tag" works but would be unusual in a calendar context. What you can do is split the suggested word: "Ganz- tätig" into two lines. But generally you might have that problem with other languages as well.

**Comment by ArjenSwBase** [comment]
You would have to ask yourself, is it really required to state that it is for all day events. If you take a look at google calendar, you will see that they don't state it, they just show your timezone. 

The calendar on mac does state it. But is it really necessary?

**Comment by antoniandre** [comment]
> "Den ganzen Tag" works but would be unusual in a calendar context. What you can do is split the suggested word: "Ganz- tätig" into two lines. But generally you might have that problem with other languages as well.

Thanks @davidgraeff, I will change that in next release then.



> You would have to ask yourself, is it really required to state that it is for all day events. If you take a look at google calendar, you will see that they don't state it, they just show your timezone.
> 
> The calendar on mac does state it. But is it really necessary?

Thanks @ArjenSwBase for your ideas and comparison to existing calendars. I know it might be a problem for all the languages but I want to offer the user the choice to have it or not. If you want to hide it, that is your call, but if you want to display it, it is there for you.

**Comment by litoxy** [comment]
zh-CN:"整天"

**Comment by antoniandre** [comment]
Closing this issue as feature is released.
This feature will be improved, see #107 and continue thread there.
