### ISSUE TITLE
The option to have the scroll position start somewhere else

### ISSUE THREAD

**Issue by ArjenSwBase** [antoniandre/vue-cal-v4#41]
Hello,

When I open a page with the calendar on it. The calendar starts at 0:00. but my first events are not until 09:00. So i would like to have the calendar scrolled down when first openend.

I know I could use the timeFrom option and set it to 07:00. But that would remove 00:00 - 06:59 and I would like to keep these cells shown.

Hope I made my issue clear. Found it hard to explain this one.

[An image to show the white space above the first events.](https://puu.sh/CEzm7/be4e45e584.png)

**Comment by antoniandre** [comment]
Hi @ArjenSwBase,
Sorry I won't add this feature as it would add too much complexity both code wise and UI wise.
Additionally It's not a big added value and for some other users it will be a problem it will not be working in all cases.

But if that could help you, I can return the array of events on current view on emitted events `ready` and `view-change`. From that you can filter, get the first date and do a scroll.

**Comment by ArjenSwBase** [comment]
Hi @antoniandre 

I understand that.

I think your solution will help. Could you implement that? Thanks!

**Comment by antoniandre** [comment]
Hi @ArjenSwBase, the events are now returned (https://antoniandre.github.io/vue-cal/#ex--emitted-events).
Hope it helps!
