### ISSUE TITLE
[BUG] Problem with display datepicker when use unpkg links

### ISSUE THREAD

**Issue by juanmarinelli** [antoniandre/vue-cal-v4#410]
Hello good day! I am using the links https://unpkg.com/vue-cal@3.10.1/ to use the library, since today I am having problems displaying the date-picker. I was not having any problem but today everything appears white, I fixed the styles but everything is fine.
If someone could help me, it is appreciated
![Captura de Pantalla 2021-06-02 a la(s) 12 27 39](https://user-images.githubusercontent.com/22064976/120509419-dc1bf180-c39e-11eb-9fb7-262ea6cb42f3.png)

	<vue-cal locale="es" 
    class="vuecal--date-picker "
    xsmall
       :selected-date="selectedDate"
    hide-view-selector
    :time="false"
    :transitions="false"
    active-view="month"
    :disable-views="['week','day']"
     :no-event-overlaps="true"
     @cell-click="selectedDate = $event"
    style="width: auto;height: 230px">
    </vue-cal>

**Comment by juanmarinelli** [comment]
here I found an example of the problem that is happening
 https://codepen.io/antoniandre/pen/jOOmxzo

**Comment by rubjo** [comment]
Can you please clarify what you mean or close the issue?
