### ISSUE TITLE
Simultaneous events in same hour

### ISSUE THREAD

**Issue by phpiando** [antoniandre/vue-cal-v4#411]
First, this lib is excellent! Thanks very much.

Second.. it's possible to improve my view with simultaneous events in the same hour? For example.. to date 01/06 exists 3 events to 1 pm but the title is all grouped.

How Can I improve this?
![Screenshot_28](https://user-images.githubusercontent.com/12565400/120521133-8100f380-c3cc-11eb-8d37-31717de1cc4c.png)

**Comment by ChaerilM** [comment]
make a single event and calls it a 'multiple events', then add on-click to open modal with details.
or watch `.vuecal__cell--has-splits` when it had, make that cell bigger while other cell smaller

**Comment by rubjo** [comment]
@over12 Please consider closing this issue if it was resolved.

**Comment by antoniandre** [comment]
@over12,

How do you want to display it? This is a logical display as the events are simultaneous but I agree it's not convenient to read.
If you want more readability, you should either:
- switch to day view
- set a `min-cell-width`
- set a `min-split-width`
- restyle it however you want via CSS

Closing the issue now
