### ISSUE TITLE
event delete function in template

### ISSUE THREAD

**Issue by ChaerilM** [antoniandre/vue-cal-v4#415]
so I'm trying to watch for modification and deletion but seems I called the wrong function, and docs do not seem to explain the correct way to do it. 
```Vue
//template

:on-event-click="onEventClick"
:on-event-create="onEventCreate"
@event-drag-create="onDragCreate"
// does not work
:on-event-title-change="onEventChanged"
:on-event-duration-change="onEventResized"
:on-event-delete="onEventDelete"

```

what should I watch in the template for `title-change`, `duration-change` and `delete` event

**Comment by vesper8** [comment]
To listen to the delete event use `@event-delete="yourMethod"`
