### ISSUE TITLE
fixed time on drag&drop

### ISSUE THREAD

**Issue by VadimCeretean** [antoniandre/vue-cal-v4#421]
![2021-07-17_09-57](https://user-images.githubusercontent.com/45070098/126028836-dd9fbec3-b93a-4a1c-bd85-69c89b83833c.png)
Is possible to change event date between two columns only for same time? 
If I want to change event from John to Tom, and time of event is 10:00 if John column, so I need on event dragging set the same time, and if dragged to a different time, the event should automatically insert the correct time

**Comment by crisclacerda** [comment]
I believe you should be able to acomplish this with the emited @event-drop callback
`onEventDrop ({ event, originalEvent, external })`  
Check if event start time is equal to originalEvent and if not change it...
