### ISSUE TITLE
editable events crossing days are not draggable, resizing them causes ui bugs

### ISSUE THREAD

**Issue by Spacarar** [antoniandre/vue-cal-v4#423]
I am using the calendar using the "week" view with editable events set to `{ title: true, drag: true, resize: true, delete: false, create: true }` and I noticed that if an event crosses midnight it becomes immobile.

here is a sample event body that I copied
```javascript
{
    "_eid": "25608_4",
    "start": "2021-07-30T04:14:00.000Z",
    "startTimeMinutes": 1334,
    "end": "2021-07-30T12:15:00.000Z",
    "endTimeMinutes": 375,
    "title": "",
    "content": "",
    "background": false,
    "allDay": false,
    "daysCount": 2
}
```

Further to this, if you resize the event so that it doesn't cross midnight anymore, the whole event gets misplaced outside of the calendar as shown below:

- load calendar: correctly rendered (bottom of calendar shown)
![Screen Shot 2021-07-28 at 4 20 25 PM](https://user-images.githubusercontent.com/24302366/127403751-0557311f-7be9-4c62-909e-cff6daf08702.png)

- load calendar: correctly rendered (top of calendar shown)
![Screen Shot 2021-07-28 at 4 20 31 PM](https://user-images.githubusercontent.com/24302366/127403748-028c878d-5c93-4bbf-aa26-2124f26d931f.png)

- resize event to no longer pass midnight and it jumps off the calendar
![Screen Shot 2021-07-28 at 4 20 45 PM](https://user-images.githubusercontent.com/24302366/127403744-4c3caeaa-63f7-4a59-b209-fd5b77711004.png)

**Comment by Spacarar** [comment]
Forked a codepen from the documentation that reproduces this bug here: https://codepen.io/Wolfwood_/pen/oNWJRGx

This is the same codepen from #425 and will demonstrate both of these 2 issues.

**Comment by antoniandre** [comment]
Hi @Spacarar,

Indeed drag and drop does not support multiple day events as written in the documentation.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/22971289/185784644-4863dd35-e692-4f51-997c-b430bfce47c6.png">

Also if you want to resize multiple day events horizontally, you need to add  the `resize-x` (x axis) option.
