### ISSUE TITLE
drag & drop only vertical or only horizontal

### ISSUE THREAD

**Issue by VadimCeretean** [antoniandre/vue-cal-v4#428]
Is it possible to prevent blocks from being dragged vertically or horizontally so that they cannot even be visually dragged? https://i.gyazo.com/5699cd2ac1f9244e32150abc9a6b17fd.mp4

**Comment by antoniandre** [comment]
Hi @VadimCeretean,
You can prevent draggability on certain events if that's what you're looking for.
https://antoniandre.github.io/vue-cal/#ex--edit-and-delete-events

Pease reopen if not solved.
