### ISSUE TITLE
Custom function when double clicked on event

### ISSUE THREAD

**Issue by ArjenSwBase** [antoniandre/vue-cal-v4#43]
Hello,

Currently if you double click on an event the view changes to the day view. What I would like to do is to overwrite this functionality and trigger a function. When an event is double clicked I would like to open a modal. So i would like something like "@event-double-click='doMethod'"

Thanks!

**Comment by antoniandre** [comment]
Hi @ArjenSwBase,
Agreed, allowing a callback / disabling navigation on event double-click is an obvious task that vue-cal should allow.

**Comment by onmotion** [comment]
Yes, it's wold be great if we had a week/day view event slot.
Now I can do modal through the **events-count-month-view** slot

```js
<template class="event-month-items" slot-scope="{ events }" slot="events-count-month-view">
        <div v-for="(event, i) in events" :key="i"
                             @dblclick.stop="() => {}"
                             @click="onEventClick(i, event, $event)"
                             class="event-month-item" :class="event.class"
                        >
                            <span class="event-month-item__title">{{ event.title }}</span>
        </div>
</template>

...
onEventClick(i, event, mouseEvent) {
                this.showModal = true
                this.$nextTick(() => {
                    this.currentEvent = this.calendarProps.events[i]
                })
            },
...
```

![2019-02-05_15-14-22](https://user-images.githubusercontent.com/12899080/52272959-75ff3b00-2959-11e9-8a29-ee1caa49c160.png)

![image](https://user-images.githubusercontent.com/12899080/52273071-ba8ad680-2959-11e9-86b1-41167314d614.png)

**Comment by antoniandre** [comment]
Smart solution @onmotion!
I'm glad you found a workaround, I'll start this dev soon.

**Comment by antoniandre** [comment]
Hi folks, This is now possible in version 1.29.0. 
Please have a look here: https://antoniandre.github.io/vue-cal/#ex--open-dialog-on-event-click

Hope it helps solving the issue.

**Comment by antoniandre** [comment]
@ArjenSwBase, @onmotion, tagging you in for notification 😉

**Comment by antoniandre** [comment]
@ArjenSwBase please review this and close if solved.

**Comment by ArjenSwBase** [comment]
Oh! Yes, this is good. Apologies for not closing this earlier.
