### ISSUE TITLE
[Question]  Selected day events

### ISSUE THREAD

**Issue by dennisbusk** [antoniandre/vue-cal-v4#433]
Hi.
Beautifull calendar and very well documentet.

I was wondering. 
Is possible to get all events @onDayClick

example:
clickedDay(date, eventsOnDate){}

Sorry for my crude writing

**Comment by Spacarar** [comment]
you can do this manually with the current version of the calendar.

on the calendar you can have `@cell-click="onDateClick"`

then
```javascript
onDateClick(dateString) {
	let date = new Date(dateString)
        // depending on what date libraries you may use this section may be simpler
	let eventsOnDay = this.events.filter(d => {
		let eventDate = new Date(d.start)
		return (
			eventDate.getFullYear() === date.getFullYear() &&
			eventDate.getMonth() === date.getMonth() && 
			eventDate.getDate() === date.getDate()
		)
	})

	// do something with eventsOnDay
}
```

**Comment by antoniandre** [comment]
Hi @DennisBusk,
@Spacarar solution is great - thanks for that.
Closing the issue now. please reopen if not solved.
