### ISSUE TITLE
"Could not find a declaration file for module 'vue-cal'."

### ISSUE THREAD

**Issue by JonHerbert** [antoniandre/vue-cal-v4#435]
I installed the vue-cal@next version, but am getting this error when importing in my main.js file.

> Could not find a declaration file for module 'vue-cal'. 'c:/Users/FiercePC/Documents/VueJS Projects/todo-together/node_modules/vue-cal/dist/vuecal.common.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/vue-cal` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-cal';`

Also getting this in devtools:

> runtime-core.esm-bundler.js?5c40:6873 [Vue warn]: A plugin must either be a function or an object with an "install" function.
> runtime-core.esm-bundler.js?5c40:6873 [Vue warn]: Failed to resolve component: vue-cal 
>   at <Calendar2> 
>   at <CalanderView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
>   at <RouterView> 
>   at <App>

in my main.js:

```
import VueCal from "vue-cal";
import "vue-cal/dist/vuecal.css";

createApp(App)
  .use(store)
  .use(router)
  .use(VueCal)
  .use(PrettyCheckbox)
  .mount("#app");
```

Then in my Calender2.vue component I'm just using one of the examples:

```
<vue-cal
      selected-date="2018-11-19"
      :time-from="9 * 60"
      :time-to="19 * 60"
      :events="events"
    >
      <template v-slot:event="{ event }">
        <div class="vuecal__event-title" v-html="event.title" />
        <!-- Or if your events are editable: -->
        <div
          class="vuecal__event-title vuecal__event-title--edit"
          contenteditable
          @blur="event.title = $event.target.innerHTML"
          v-html="event.title"
        />

        <small class="vuecal__event-time">
          <!-- Using Vue Cal injected Date prototypes -->
          <strong>Event start:</strong>
          <span>{{ event.start.formatTime("h O'clock") }}</span
          ><br />
          <strong>Event end:</strong>
          <span>{{ event.end.formatTime("h O'clock") }}</span>
        </small>
      </template>
    </vue-cal>
```

Can't get the calendar to show. Any ideas on what I'm doing wrong?
If anymore info is needed just let me know!

**Comment by rubjo** [comment]
Are you using the correct versions?

Please provide a minimal reproduction demonstrating the issue using CodePen, CodeSandbox or similar.

**Comment by ManuelTS** [comment]
Same here, just the install with `npm i vue-cal@next` then on the import, the module is not found.

**Comment by antoniandre** [comment]
Please provide a repro, the latest Vue 2 and Vue 3 builds should be working as expected.
Vue 3 build demo: https://stackblitz.com/edit/vuecal-vite-esm?file=src%2FApp.vue

Please reopen if not solved.

**Comment by gmedri** [comment]
I have this same error.

**Comment by Boltzmachine** [comment]
Same Issue

**Comment by 1ncredibleM1nd** [comment]
Same issue

**Comment by oracast** [comment]
Still actual. it happend when using TS
![image](https://github.com/antoniandre/vue-cal/assets/4595212/7ac016bd-f61d-42ac-9f37-c2cb61cfe87c)

**Comment by DevilGeek** [comment]
Same issue using typescript and vue-cal 4.10
