### ISSUE TITLE
Add functionality to Today Button

### ISSUE THREAD

**Issue by Darkade** [antoniandre/vue-cal-v4#438]
Hi! I'm showing and hiding the date picker with a `v-if="showCalendar"` I'm also using `@cell-click="dateChanged($event)"` to update the selected date and change `showCalendar=false;`

I would like to do something similar with the Today button, to set `showCalendar=false` when the user clicks the button. Is there a way to do it?

Thanks!

**Comment by BesartAbdurrahmani** [comment]
sure @Darkade there is a slot to customize as you want, also you and invoke a custom method.
ref: https://antoniandre.github.io/vue-cal/#ex--adding-a-today-button

```
<vue-cal
today-button
>

<template v-slot:today-button>
  <span @click="methodName">Today</span>
</template>

</vue-cal>

**Comment by antoniandre** [comment]
Thanks for reply @besart-rr.
Closing the issue now.
