### ISSUE TITLE
Translation for months

### ISSUE THREAD

**Issue by ilmi-j** [antoniandre/vue-cal-v4#442]
two months in albanian language are wrong translated.
GUSHTË should be GUSHT and
NËNDOR should be NËNTOR

![image](https://user-images.githubusercontent.com/87009302/140295189-2471aeb2-fc5e-49db-a485-c8de42df6bfe.png)

**Comment by Twoody** [comment]
I don't know if anyone speaks Albanian that is currently involved with this project. If there are different dialects or spellings, this would cause an issue for existing users. 

I am also unsure of how @antoniandre has handled the imports of existing supported languages.

**Comment by ilmi-j** [comment]
In every Albanian dialect August is Gusht and November is Nëntor. Also, you can easily check this on google if you search for "months of the year in albanian".

**Comment by BesartAbdurrahmani** [comment]
@ilmi-j Yeah you are right, I just commit the typo fix which will close this issue

cc: @antoniandre

**Comment by ilmi-j** [comment]
@besart-rr Thank you, I checked again your changes and looks there is no other mistake. 
I hope @antoniandre will merge it as soon as possible because I need it in my project!

Thank you in advance.
Best regards
