### ISSUE TITLE
[Question] How to remove outer border?

### ISSUE THREAD

**Issue by madbarron** [antoniandre/vue-cal-v4#444]
Hi,

I want to use the calendar with custom controls and a legend, so I want it to look integrated. I would like to remove the outer rectangular border of the calendar.

I can't find where the border is defined in CSS, either by looking in the source code or using the devtools inspector. Any guidance of what CSS I can overwrite would be much appreciated!

**Comment by Twoody** [comment]
Can you provide a screenshot of the border in question? A codepen or repo would also help.

**Comment by madbarron** [comment]
Here is a codepen of the stripped-down calendar that I am using: https://codepen.io/madbarron/pen/OJjEZmx

I would like to know what CSS I can add to remove the indicated outside borders (everything not connected to a time cell)
![image](https://user-images.githubusercontent.com/6498103/141011721-50955c6b-f664-434f-a4ba-d2d94811bdf4.png)

**Comment by Twoody** [comment]
Not entirely sure if this covers your bases but see attached image and `box-shadow`.

![Screen Shot 2021-11-09 at 7 24 40 PM](https://user-images.githubusercontent.com/5855700/141044375-2583770b-6f4f-4d59-9f22-f0f788538297.png)

For more styles, see: https://github.com/antoniandre/vue-cal/blob/master/src/vue-cal/styles.scss

I would recommend being mindful of bundling and any other injected classes as seen in the above image too.

**Comment by madbarron** [comment]
That works perfectly. Thanks!!

**Comment by Twoody** [comment]
I'm glad it helped, and thank you for closing the issue. Good luck with your project!
