### ISSUE TITLE
Dynamic cell width depending on event count

### ISSUE THREAD

**Issue by donmb1** [antoniandre/vue-cal-v4#446]
Hi there.
I'd like to realize dynamic cell width with `vue-cal` meaning the cells in the week-view should have different widths, depending on the event count.

Example:
1. property `min-cell-width` should apply by default, e.g. `150px` which works fine
2. if in a `cell` there are multiple events, I'd like to expand the cell width but currently the events are stacked next to each other. If I enable overlapping they're obviously overlapped but the min-cell width still applies and the events "share" the space of 150px which looks ugly

So my usecase is to expand the cell-width individually.

I found that there is a slot `cell-content` which I thought I could "expand" individually based on `events.length` but that is not working e.g. I am not deep enough into the css structure to overwrite the suitable selectors

Maybe someone here can help to solve this puzzle

Thank you

**Comment by antoniandre** [comment]
Hi @donmb1,
Would you be able to give a reproduction link or code please.
Please reopen once you have it if not solved :)
