### ISSUE TITLE
change view inside title slot

### ISSUE THREAD

**Issue by zyng** [antoniandre/vue-cal-v4#459]
Hey, I'm trying to change view (week-day) in the title slot.

https://codesandbox.io/s/vue-cal-example-with-btn-inside-title-slot-3lwhp (you need to refresh the browser inside codesandbox).

When I click buttons outside calendar it works fine. But after pressing the "day"  button in the title slot - it doesn't (the yellow "week" button works if I change view to "day").

Any Ideas?

Vue3, vue-cal 4.2.0

**Comment by lehoaibaokg** [comment]
Try using `@click.stop.prevent` instead of `@click`.
I think it should work.
[Event Handling](https://vuejs.org/guide/essentials/event-handling.html#event-modifiers)

**Comment by antoniandre** [comment]
Hi @zyng,

Sorry for late reply. 
@lehoaibaokg is right, just `.stop` is enough for your case.

So you should have:

```
<button class="btn btn-inside-title" @click.stop="activeView = 'week'">
      Week
</button>
<button class="btn btn-inside-title" @click.stop="activeView = 'day'">
      Day
</button>
```

Closing the issue as solved now.
