### ISSUE TITLE
Formatting Date Prototypes doesn't work for months

### ISSUE THREAD

**Issue by erdbom** [antoniandre/vue-cal-v4#462]
As seen in the screenshots from one of your codepens, the .format('MMMM') is not displaying anything
I think I am using it correctly according to your documentation. Is this a bug?

Thank you!

![Screen Shot 2022-01-20 at 4 13 30 PM](https://user-images.githubusercontent.com/68934602/150437091-d7c3c2f4-589f-42e2-a227-64453c20bcd7.png)
![Screen Shot 2022-01-20 at 4 13 12 PM](https://user-images.githubusercontent.com/68934602/150437092-3999cc82-92e0-4d11-88db-43f5e3034f97.png)

**Comment by rubjo** [comment]
Seems like a bug, yes.

Also seems odd to want to display the month names there :)

Would something like
`{{ heading.heading.date.toLocaleDateString(undefined, { month: 'long' }) }}`
or
`{{ heading.heading.date.toLocaleDateString(undefined, { weekday: 'short' }) }}`
work for you?

**Comment by antoniandre** [comment]
Hi @erdbom,
You probably moved on since the time, but I have checked the quoted Codepen and it seems to work with the latest Vue 2 build or latest Vue 3 build.
https://codepen.io/antoniandre/pen/oNgyYxN
It could have been related to a particular Vue cal build at some point.

Cheers!
