### ISSUE TITLE
Locating the logic which controls the start/end date of week view

### ISSUE THREAD

**Issue by HelloAlexPan** [antoniandre/vue-cal-v4#469]
Hey Antoni! My team is currently playing around with this awesome package.

We want to create a week view with only 5 as opposed to the 7-day default.

Vue-cal current supports the following behaviour
1. Show 5 days Monday - Friday
2. Click next
3. Vue cal updates to the proceeding Monday - Friday date

The behaviour we want to implement is:
1. Show 5 days (arbitrary, can be Monday - Friday, Tuesday - Saturday, etc.)
2. Click next
3. Vue cal updates from Monday - Friday to Saturday - Wednesday

Does anyone know where to find the logic to control the start/end date of the week view so we can do this?

**Comment by rubjo** [comment]
This isn't possible out of the box. To tinker with this, you would probably need to have a look at src/vue-cal/index.vue, line 513 onwards.

**Comment by antoniandre** [comment]
Thanks for suggestion and feedback @HelloAlexPan.
Thanks for answer @rubjo.

This is related to #316, please continue thread in there.
