### ISSUE TITLE
Date picker and day view

### ISSUE THREAD

**Issue by aznfish** [antoniandre/vue-cal-v4#47]
I've got two instances of the same vue-cal object and the data is the same. Is there a way to use one calendar as a date picker (Month only view) and the other as calendar (Week/Day only view), such that when selecting dates on one calendar, it will update the date position of the other calendar.

I'm not having much luck with listening for 'ready' and changing 'selectedDate:' 

Hope my query makes sense.

**Comment by antoniandre** [comment]
Hi @aznfish,

I have released version 1.32.0 which allows you to do what you are looking for.
Please have a look at this example: https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars

Hope it helps solving this issue!

**Comment by aznfish** [comment]
Hi antoniandre, thank you so much for turning around this feature so quickly. I took it one step further and sync'd it both ways, now the selectedDate is updated from either of the calendars and they both stay in sync. Cheers!

You're doing a great job mate, keep it up!

**Comment by antoniandre** [comment]
Thanks for your support @aznfish! 👍 

By the way, if you don't mind may be you can paste your syncing magic here for the next reader! :)

**Comment by aznfish** [comment]
Happy coding guys!

<vue-cal
    class="vuecal--blue-theme"
    xsmall
    :time="false"
    default-view="month"
    :clickToNavigate=true
    hide-view-selector
    :events="events"
    :disable-views="['years','year','week','day']"
    @day-focus="selectedDate = $event"
    :selected-date="selectedDate"
></vue-cal>

<vue-cal
    class="vuecal--blue-theme"
    default-view="day"
    :disable-views="['years','year','month']"
    hide-view-selector
    :clickToNavigate=false
    :events="events"
    @day-focus="selectedDate = $event"
    :selected-date="selectedDate"
></vue-cal>

data: () => ({
    selectedDate: null
})
