### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by joseimagina** [antoniandre/vue-cal-v4#472]
Hi,

First of all, thanks for your time, I really like your work is totally awesome.

I'm having a little trouble when I try to configure the locale for my calendar, let me show my code

<vue-cal
	style="height: 650px"
	ref="vuecal"
	locale="es"
	default-view="month"
	active-view="month"
	hide-view-selector
	v-bind:show-all-day-events="false"
	v-bind:events="events"
	:time-from="7 * 60"
	:time-step="30"
	@view-change="viewChanged($event)"
    @event-focus="eventFocus($event)">
</vue-cal>

	import VueCal from 'vue-cal';
	import 'vue-cal/dist/i18n/es.js';
	import 'vue-cal/dist/vuecal.css';
	
I followed the documentation and the configuration that I did in older projects that works, but in this last one I'm having the next message

GET http://domainproject.local/js/vuecal.common.i18n/es.js net::ERR_ABORTED 404 (Not Found)
app.js?id=28714ee6ca25c8043c31:81734 Uncaught (in promise) ChunkLoadError: Loading chunk 120 failed.
(error: http://domainproject.local/js/vuecal.common.i18n/es.js)
    at Object.__nested_webpack_require_199048__.f.j (app.js?id=28714ee6ca25c8043c31:81734:29)
    at app.js?id=28714ee6ca25c8043c31:81603:54
    at Array.reduce (<anonymous>)
    at __nested_webpack_require_199048__.e (app.js?id=28714ee6ca25c8043c31:81602:81)
    at Array.map (<anonymous>)
    at webpackAsyncContext (app.js?id=28714ee6ca25c8043c31:81373:34)
    at VueComponent.loadLocale (app.js?id=28714ee6ca25c8043c31:85195:48)
    at VueComponent.created (app.js?id=28714ee6ca25c8043c31:86095:10)
    at invokeWithErrorHandling (vendor.js:1883:57)
    at callHook (vendor.js:4250:7)

I'll be glad if you can help me.
Thanks a lot for your time :D

**Comment by rubjo** [comment]
> let me show my code

To get help, plase provide a minimal reproduction where your issue is demonstrated using CodeSandbox, CodePen or similar.

**Comment by vladfr** [comment]
@GHJose I've bumped into this issue. It's related to your webpack config, the translations are in json in the codebase, but are compiled to js by webpack, and somehow yours can't be done/found.

You can copy the en.json file from the repo and load it using 'import'. Then, provide it to the cal with the locale prop.
```
import en from "en.json";
<vue-cal :locale="en" >/
```

The vue-cal lib actually tries to load `en.js`, but you can actually provide an object to the `locale` prop. Turns out this is very cool because now you can also edit the locale!

**Comment by pimboden** [comment]
I wanted to use the calendar with nuxt.
I tried to  creat my own json files and import them. But it doesn't seam to work.
If I assgn the objet my Html looks like 

     <div column="" lang="[object Object]" class="vuecal__flex vuecal vuecal--week-view vuecal--[object Object] ..
     
 and my calendar get undefineds everywhere

![image](https://user-images.githubusercontent.com/22517784/165958988-2683050a-e17f-4e52-8f1c-6b422c6e6b03.png)

**Comment by antoniandre** [comment]
Hi @joseimagina,
Thanks for your feedback.
@rubjo & @vladfr are right. For us to help we need a reproduction example to analyze what is wrong in your build.

If you use Vue 3, I recommend to update your Vue Cal to the latest, which now handles modules by itself thanks to the new ESM build (so you don't need to import anymore). :)

Also check the examples on StackBlitz and Codepen, where you might find an answer.

- https://stackblitz.com/edit/vuecal-vite-esm
- https://codepen.io/antoniandre/pen/rNLgBKo

Please reopen with a repro if you still need help :)
