### ISSUE TITLE
Drag to create event over background event

### ISSUE THREAD

**Issue by LarisaTunjicAppliment** [antoniandre/vue-cal-v4#473]
Hello :)

How can I create background event that can be dragged over it to create a new event? I need to be able to start dragging from the middle of a background event. 

Thank you! :
![Screenshot_1](https://user-images.githubusercontent.com/102951200/161503686-6cc15ee0-c571-4c9f-8494-cb6b7f7a5b04.png)
)

**Comment by antoniandre** [comment]
Hi @LarisaTunjicAppliment,
This is very simple: in CSS add `pointer-events: none;` to all the background events.
Please reopen if not solved.
