### ISSUE TITLE
Undefined in Labels

### ISSUE THREAD

**Issue by pimboden** [antoniandre/vue-cal-v4#476]
I'm using this awesome control with nuxt.
I have to create my own Language files as schon below (I will change some texts there later).

After v3.10.1  I get a lot of "undefined" in the labels.

    <script>
     import VueCal from "vue-cal";
     import "vue-cal/dist/vuecal.css";
     import vueCal2055 from "./vueCal2055.json";
     import vueCal2057 from  "./vueCal2057.json";

     export default {
       name: "Calendar",
       components: {
          VueCal
       },
       data: () => ({
          events: [],
          cal2055 : vueCal2055,
          cal2057 : vueCal2057
      }),
     computed: {
        locale: function () {
          return this.$root.$i18n.locale == 2055 ? this.cal2055 : this.cal2057;
       },
     }
    </script>
    <template> 
      <vue-cal
        active-view="week"
        :locale="locale"
      ></vue-cal>
     </template>
    
 The calendar renders undefined everywhere

![image](https://user-images.githubusercontent.com/22517784/165958988-2683050a-e17f-4e52-8f1c-6b422c6e6b03.png)

If I debug the component though, it seems like the languages are getting loaded correctly, in the method "loadLocale"... all defaults are set correctly. 

My jsons:

    {
     "weekDays": ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
     "months": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", 
     "Dezember"],
     "years": "Jahre",
     "year": "Jahr",
     "month": "Monat",
     "week": "Woche",
     "day": "Tag",
     "today": "Heute",
     "noEvent": "Keine Events",
     "allDay": "Ganztägig",
     "deleteEvent": "Löschen",
     "createEvent": "Event erstellen",
     "dateFormat": "dddd D MMMM YYYY"
    }

Even though this is not my sample. I see the same issue on <a href="https://jsfiddle.net/qm5acdw7/" target="_blank">this fiddle</a>

**Comment by juanmarinelli** [comment]
hello ! were you able to solve this? it also shows me all the labels "undefined"

**Comment by pimboden** [comment]
@juanmarinelli  No. I downgraded to version 3.10.1. That version works.

**Comment by rynnliewdev** [comment]
I'm also having the similar issue when using it with Vue in Laravel Nova. 
Can somebody advise on this issue? Thanks!

package.json:

`   "devDependencies": {
        "cross-env": "^5.0.0",
        "laravel-mix": "^1.0",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "vue": "^2.6.12",
        "vue-cal": "^3.10.1"
    }`

**Comment by nbignu** [comment]
did anyone find a solution to this? having the same issue with @legacy vue 2.6.12 vue cal 3.10.5

**Comment by antoniandre** [comment]
Hi all, just by using the latest legacy versions of Vue and Vue Cal, the problem is fixed.
Here is the same Fiddle, with latest legacy versions from CDNs.

- https://jsfiddle.net/zbxwh94f/ 
- or on Codepen https://codepen.io/antoniandre/pen/pGJWjL
- or on Stackblitz with CLI: https://stackblitz.com/edit/vuecal-vue2?file=src%2FApp.vue

Note that the latest Vue Cal is for 3 only. It also displays the labels correctly.
