### ISSUE TITLE
Click on the title to go to a broader view

### ISSUE THREAD

**Issue by jordiribera** [antoniandre/vue-cal-v4#478]
Hello, first of all thank you for your work!
What I want to ask is whether it is possible to disable the click on the title to go to a broader view.

Thank you!

**Comment by antoniandre** [comment]
Hi @jordiribera, thanks for the feedback and sorry for the delay 🤷‍♂️ 
Yes and it's very easy. You just need to use the title slot to override with a div on which you prevent the click to bubble up.
In the slot the default title is provided as a parameter, so you can just reuse it as is.

```html
<template #title="{ title }">
      <div @click.stop>{{ title }}</div>
</template>
```
Here is the demo: https://codepen.io/antoniandre/pen/rNvOVJz

Please reopen if not solved.
