### ISSUE TITLE
Horizontal scroll bar visible during view change transition

### ISSUE THREAD

**Issue by johnfraney** [antoniandre/vue-cal-v4#48]
When changing between views (e.g. week to month), a horizontal scroll bar is visible during the transition. (I think the [-15px translateX](https://github.com/antoniandre/vue-cal/blob/master/src/components/vue-cal/index.vue#L1193) is the cause.)

Here's a gif showing this behaviour:

![vue-cal-horizontal-scroll-bar-on-view-change optimized](https://user-images.githubusercontent.com/1728528/52829909-ff72e380-30a4-11e9-940c-6586f4e6f363.gif)

I've got a quick fix for this I can put in a PR.

**Comment by antoniandre** [comment]
Hi @johnfraney, thanks for pointing it out! 
By the way which browser behaves like that? I could not reproduce on Chrome Safari and Firefox mac.

I am about to merge your change in, awesome :)

**Comment by johnfraney** [comment]
@antoniandre I was able to reproduce that on Firefox 66.0b7 and Chrome 72.0.3626.109, both running on Linux.
