### ISSUE TITLE
To hide class "vuecal__body" in day view

### ISSUE THREAD

**Issue by CodingSnorlax** [antoniandre/vue-cal-v4#485]
Hi, i have a question about how to hide "vuecal__body" in day view,
but still need to keep the "vuecal__header" part in day view,
and i code with composition api, can anyone help??

Thanks a lot!

**Comment by antoniandre** [comment]
Hi @CodingSnorlax 
As straightforward as .vuecal--day-view .vuecal__body {display: none}
Don't forget to inspect the CSS classes, all you need should be there.
