### ISSUE TITLE
dates with undefined 

### ISSUE THREAD

**Issue by phpiando** [antoniandre/vue-cal-v4#488]
I don't know why, but I'm using calendar in a "simple" way, and it returns dates as undefined..

Could anyone say why?

`  <vue-cal></vue-cal>`

![download](https://user-images.githubusercontent.com/12565400/182200306-47e8993f-477a-45e0-a7b6-92ab1a5501a6.png)

**Comment by antoniandre** [comment]
Please share a reproduction example to get help. Codepen or stackblitz. Thanks

**Comment by phpiando** [comment]
I found the problem.. I using the vue2 from cdn, but a problem with something in the version, I change to use for vue@legacy and the problem was solved.. 

I belive it's was just necessary the some talk.. hahah, 

Thanks

**Comment by alexsantm2019** [comment]
@over12 Can you tell me how to use vue@legacy? I have the same problem, I installed legacy version of vue-cal, but It did not work

**Comment by antoniandre** [comment]
You also need the latest legacy vue. Make sure you update it
