### ISSUE TITLE
Disable Weekends on Day view

### ISSUE THREAD

**Issue by eza** [antoniandre/vue-cal-v4#491]
If I disable the weekends I can still reach them on the Day view. Wouldn't it make more sense if it wasn't possible to add events in the day view (so disabled) on weekends day if the weekends are disabled?
Thanks

**Comment by eza** [comment]
If I disable the weekends I can still reach them on the Day view. Wouldn't it make more sense if it wasn't possible to add events in the day view (so disabled) on weekends day if the weekends are disabled?
Thanks

**Comment by antoniandre** [comment]
Hi @eza,
That's a fair point.
I have modified the codebase to prevent navigation to the hidden days listed in `hideWeekends` and `hideWeekdays`.
Released in version 4.6.0.

New behavior observable in: 
- https://antoniandre.github.io/vue-cal/#ex--basic
- https://antoniandre.github.io/vue-cal/#ex--hiding-particular-week-days

Please reopen if not solved. ;)

**Comment by eza** [comment]
will this be available for Vue2?

**Comment by antoniandre** [comment]
Available now in version 3.11.0 (`npm i vue-cal@legacy`)
