### ISSUE TITLE
Customize the header on calendar

### ISSUE THREAD

**Issue by thanhnguyen-saritasa** [antoniandre/vue-cal-v4#496]
Hi Guy,
I would like to custom something on the header section. 
I want to group the event by child category, like this demo:
https://ej2.syncfusion.com/vue/demos/#/bootstrap5/schedule/group-bychild.html

Is there a solution to implement that? Thank you a lot.

**Comment by antoniandre** [comment]
Hi @thanhnguyen-saritasa, this is not possible for the sub levels, but  you can check the day splits, which give you one level.
https://antoniandre.github.io/vue-cal/#ex--splitting-days
Cheers
