### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-cal'

### ISSUE THREAD

**Issue by similanklinsmith** [antoniandre/vue-cal-v4#498]
I installed the vue-cal version 4.4.0 to my project. I found some errors 

> Module not found: Error: Can't resolve 'vue-cal'

in my ConfirmedView.vue

```
import VueCal from "vue-cal";
import "vue-cal/dist/vuecal.css";
export default {
  name: "ConfirmedView",
  components: { VueCal },

```

Any ideas on what I'm doing wrong?

**Comment by antoniandre** [comment]
Hi @similanklinsmith,

Thanks for reporting. This is now fixed in the latest release 4.4.2.
