### ISSUE TITLE
Include visible but out-of-month dates in event payloads

### ISSUE THREAD

**Issue by johnfraney** [antoniandre/vue-cal-v4#50]
Is it possible to get a range of all visible dates in the month view in the `view-change` and `ready` events? When viewing February in the month view, for instance, the visible dates are January 28 - March 8th, but only February 1 - February 28 are in the event.

 [vue-simple-calendar](https://github.com/richardtallent/vue-simple-calendar) has these, for instance:

- `periodStart` / `periodEnd`: the active period (e.g., February 1 - February 28th when February is active)
- `displayFirstDate` / `displayLastDate`: all visible dates (e.g., January 28 - March 8th when February is active)

**Comment by antoniandre** [comment]
Hi @johnfraney,
I did not think about this before, this should definitely be possible.
I will look at it soon!

**Comment by johnfraney** [comment]
@antoniandre That's great. Thanks!

**Comment by antoniandre** [comment]
Hi @johnfraney,
The out of scope events are now showing up and returned in emitted events.
Please check the updated example: https://antoniandre.github.io/vue-cal/#ex--events-on-month-view, (and the release notes as always 😉 https://antoniandre.github.io/vue-cal/#ex--events-on-month-view)

Hope it helps!

**Comment by johnfraney** [comment]
@antoniandre I think we're getting close. It sounds like if I have a list of events from January - March, the recent change will show the out-of-scope events in the month view, which is great.

I listen to the `@ready` and `@view-change` component events to fetch the appropriate calendar events for the active view. I use the dates in that event payload to fetch events in a specific date range. That way I'm not fetching more data than I need.

Here's the current component event  payload when changing to a month view:

```json
{
  "view": "month",
  "startDate": "2019-02-01T04:00:00.000Z",
  "endDate": "2019-02-28T04:00:00.000Z",
  "events": []
}
```

I'm wondering if we could add the out-of-scope days to this event payload so I can ask my backend for events for all visible days:

```json
{
  "view": "month",
  "startDate": "2019-02-01T04:00:00.000Z",
  "endDate": "2019-02-28T04:00:00.000Z",
  "displayStartDate": "2019-01-28T04:00:00.000Z",
  "displayEndDate": "2019-03-08T04:00:00.000Z",
  "events": []
}
```

Do you think that would be possible?

**Comment by antoniandre** [comment]
@johnfraney,
Sure, it's already what I do internally. I will update the code soon to return it in payload.

**Comment by antoniandre** [comment]
@johnfraney,

This is now possible in version 1.37.2, please check the updated example: https://antoniandre.github.io/vue-cal/#ex--emitted-events

In this example, check the month view and get the first cell and last cell dates from `firstCellDate`, `lastCellDate`.

**Comment by johnfraney** [comment]
@antoniandre Thanks for the quick turn-around! That's exactly what I was looking for.
