### ISSUE TITLE
Importing Locales not working anymore in latest version

### ISSUE THREAD

**Issue by Scarwolf** [antoniandre/vue-cal-v4#500]
Just wanted to drop a quick heads up. It seems that beginning with version 4.8.0, it is not possible anymore to import locales using the known format anymore (at least not in a Vue SFC + Webpack env):

`import 'vue-cal/dist/i18n/fr.js';`

The dist/i18n folder doesn't provide {locale}.js files anymore, instead, it serves the following:
`{locale}.amd.js`, `{locale}.cjs.js` and `{locale}.es.js`

So you have to import one of these instead. Importing `fr.amd.js` instead of `fr.js` worked in my case.

**Comment by antoniandre** [comment]
Hi @Scarwolf,
Indeed, in the latest build you don't need to import the locale file separately. 
https://stackblitz.com/edit/vuecal-vite-tpjusd?file=src%2FApp.vue

it's also written in the documentation.
https://antoniandre.github.io/vue-cal/#ex--internationalization
