### ISSUE TITLE
Can't display hours split lines through day/week view

### ISSUE THREAD

**Issue by severinWsystem** [antoniandre/vue-cal-v4#504]
Hello ! first of all thanks for your amazing tool ! I really like it :)

I' posting because it's been some days that I'm searching where to find the option to display lines between hours to have a better and more precise sight on day/week timeline.

I can see on the component page that it's working, but when I import it to my project, I juste have column / day but without line between hours. I found that I have 1 cell / day all along, but I need to split and have 24 cells / day (one per hour) and have events superposing above.

Is there a param that I need to precise in my code to display it ? or a CSS class to call to add by my self the lines ? Do I have to use a css framework ? (I'm not using one for now (even if I had a look at Wave-ui which seems to be cool to import :p)

To illustrate my issue, there you can find what I'm having :

![Capture d’écran 2022-09-29 115856](https://user-images.githubusercontent.com/113424319/193003547-6f50b575-a9b6-427d-9989-ac506e240c92.png)

and I want to have something like that :

![Capture d’écran 2022-09-29 115923](https://user-images.githubusercontent.com/113424319/193003652-4a532714-c30f-4cba-bdf3-62c66e7fff10.png)

![Capture d’écran 2022-09-29 120926](https://user-images.githubusercontent.com/113424319/193004412-3599b7b9-1db3-43af-afe2-19cb56532aac.png)

do not pay attention of the number of days ;) just mind about lines.

PS: for my code, I just imported what is on your doc. I'm on Vue3+vite.
`<vue-cal
                v-model:active-view="activeView"
                :split-days="splitDays"
                :time-from="0 * 60"
                :time-to="24 * 60"
                :events="events"
                hide-view-selector >
            </vue-cal>`

Again, thanks for your huge work which is so powerfull and awesome ! :D

In waiting for a response :) Thanks !

**Comment by severinWsystem** [comment]
up ? :/
No one knows ?

**Comment by jrf6023** [comment]
I am seeing this same issue, and would love to hear a solution! 

Upon inspecting the rendered html, it seems that there is a cell-line class, but its got a width of 0 on my page. Not sure how to fix this, but here is the html element for each timestamp im seeing when this is served to the web: 

`<div class="vuecal__time-cell"/>`
`<span class="vuecal__time-cell-line/>"`
`<span class="vuecal__time-cell-label">01:00</span>`
`</div>`

![image](https://user-images.githubusercontent.com/55148273/205325036-bca17d9d-99a1-48be-af5c-2fec76718dc4.png)

**Comment by severinWsystem** [comment]
@jrf6023 Thanks! you were right, we just need to set vuecal__time-cell-line width to 100% of vuecal. idk why it was not set by default but it works for me :)
