### ISSUE TITLE
How can I display short events? They are not readable (height too small)

### ISSUE THREAD

**Issue by DNA-PC** [antoniandre/vue-cal-v4#537]
<img width="486" alt="image" src="https://github.com/antoniandre/vue-cal/assets/107790761/ae186223-f59f-4195-ab87-96809d3e8531">

Is there a way to make the event more readable anyhow? Because the time is too short (e.g: 5mn), it's not readable at all.

I was thinking there could be something that makes the event bigger when focused, I'm open to other ideas/workarounds.

**Comment by lehoaibaokg** [comment]
You can set the time step = 15 mins which means we have 4 time slots / hour. And the minimum event height will be a time slot if it's only 5 minutes.
![image](https://github.com/antoniandre/vue-cal/assets/31227917/5b2fc931-a57b-4fda-a40c-f4262aab928e)
Besides, you can implement event tooltips to display event information like event time and more.

**Comment by DNA-PC** [comment]
Thanks, it's useful.
