### ISSUE TITLE
All day events in month view

### ISSUE THREAD

**Issue by DuredhelFinceleb** [antoniandre/vue-cal-v4#54]
This is a great calendar component, clean, practical and easy to use! 

When using events-on-month-view and show-all-day-events, all day event do not appear on month view.
Is there a way around this?

**Comment by antoniandre** [comment]
Hi @DuredhelFinceleb,

Thanks for your feedback! 
You are right, that's a bug it will be fixed in next version.
Cheers.

**Comment by DuredhelFinceleb** [comment]
OK then I'll just wait for the next version then :smiley:

**Comment by antoniandre** [comment]
Hi @DuredhelFinceleb, this is now fixed in version 1.38.0, please refer to the updated example: https://antoniandre.github.io/vue-cal/#ex--all-day-events

Hope it helps solving the issue.

**Comment by DuredhelFinceleb** [comment]
Thanks a lot, it works ! :smiley:
You might want to have a look at #57 as I had that issue. I've solved it by modifying my vue module but I'm not sure this is they way to go as I'm too new into the node.js world (afaik my update will go away with the nuxt update?)

**Comment by antoniandre** [comment]
Great, closing this solved issue then.
Please follow up in #57 for your last request.
