### ISSUE TITLE
@event-change emitted when no change occured

### ISSUE THREAD

**Issue by DuredhelFinceleb** [antoniandre/vue-cal-v4#56]
With editable-events in use, when clicking into an event title and clicking out of it without changing it, 
@event-change is still emitted. I'm trying to find a way for my app to detect that no change in fact occurred.
I'd like to avoid maintaining a copy of the data just to check if the received event is actually different.
Is there a way around this?

**Comment by antoniandre** [comment]
Hi @DuredhelFinceleb, I understand your point.
Currently vue-cal triggers an event-change on title-blur or resizing end, it will also be triggered when dragging and dropping an event in the future.

Checking if a change really occurred means internally having a copy of the original data - as you want to avoid - and comparing before emitting event.
I mark this as a feature request and will have a closer look later after I finish more urgent tasks.

**Comment by DuredhelFinceleb** [comment]
Great. In the meantime, I'll use a copy of the original data and I'll adapt my code when the feature will be available

**Comment by antoniandre** [comment]
Hi @DuredhelFinceleb,
This is now fixed in version 1.40.3
