### ISSUE TITLE
This project is deprecated?

### ISSUE THREAD

**Issue by lucaspmarra** [antoniandre/vue-cal-v4#569]
Last update was 2 years ago, I come to check recurring events that have status 'coming soon' and no sight of release date.

Is this project deprecated and will not receive more updates?

**Comment by nivrith** [comment]
I have the same question

**Comment by nowocynEmfits** [comment]
@antoniandre can you give a statement?

**Comment by antoniandre** [comment]
The current latest public version of Vue Cal is to be used as is and is no longer maintained. The reason is that this codebase has retro-compatibility with Vue 2 that we don't need anymore.
**However, I'm currently working hard on a fresh V5 in a branch (Vue 3 only and composition API) 🚀**
