### ISSUE TITLE
overlapping events on month view

### ISSUE THREAD

**Issue by DuredhelFinceleb** [antoniandre/vue-cal-v4#58]
on month view when using events-on-month-view and you have overlapping events, they are not correctly displayed
no-event-overlaps has no effect on this issue

if you have this in the week (or day) view:
![image](https://user-images.githubusercontent.com/9292585/53485599-e8f66000-3a86-11e9-84da-28a479da25ba.png)

you get this in the month view
![image](https://user-images.githubusercontent.com/9292585/53485730-45597f80-3a87-11e9-81c1-4a7011c6020e.png)

**Comment by antoniandre** [comment]
Hi @DuredhelFinceleb, 
That's right there is something to fix, I'm on it.
Thanks for noticing.

**Comment by antoniandre** [comment]
Fixed in version 1.38.4.
Please note that if you still encounter the error #57, you probably have to upgrade your Vue version: https://github.com/vuejs/vue-hot-reload-api/issues/73
