### ISSUE TITLE
Alternative header layouts

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [antoniandre/vue-cal-v4#581]
First of all, sorry for my bad english.

I'm working in a scheduler app and I think that the default header layout is not optimized for good space usage.

![image](https://github.com/user-attachments/assets/3ee13e66-5920-4dad-8593-a83c808c846e)

I've made some changes that allow me to choose the header layout:
(Here i'm using the default test page)

### Default header *(not changed)* ###
![image](https://github.com/user-attachments/assets/2b54a2cc-7323-41fa-816e-9e73949074f6)

### Default header with title ###
```
<vue-cal
    v-model:selectedDate="selectedDate"
    class="ml2 mr1 vuecal--blue-theme"
    xsmall
    :events="events"
    editable-events
    cell-contextmenu
    today-button
    :time-from="7 * 60"
    :time-to="20 * 60"
    :special-hours="specialHours"
    :hide-view-selector="false"
    :cell-contextmenu="log"
  >
    <template #name>VueCal Test View</template>
  </vue-cal>
```

![image](https://github.com/user-attachments/assets/2e739b73-3e90-4b71-a8e6-02943c1bab62)

### Defaultt header - reordered ###
```
<vue-cal
    ...
    :header-options="{
      order: ['title-bar','menu','name'],
    }"
  >
    <template #name>VueCal Test View</template>
  </vue-cal>
```
![image](https://github.com/user-attachments/assets/17359d1b-5b8c-4b04-9f96-084cd999bd5f)

### Alternative header - title at center ###
```
<vue-cal
    ...
    :header-options="{
      type:'row',
      order: ['title-bar','name', 'menu'],
    }"
  >
    <template #name>VueCal Test View</template>
  </vue-cal>
```
![image](https://github.com/user-attachments/assets/a7b4f0fe-f61c-4a7f-a667-3f1215a735d7)

### Alternative header - title at left ###

```
<vue-cal
    ...
    :header-options="{
      type:'row',
      order: ['name', 'title-bar', 'menu'],
    }"
  >
    <template #name>VueCal Test View</template>
  </vue-cal>
```

![image](https://github.com/user-attachments/assets/5442477a-281d-4010-a612-b9b58a805c8d)

### Alternative header responsivity ###
When the width is equal or below 1024px, the alternative header will change its layout to default header in order not to break its responsivity.
(If you set the order of elements, the order will remain the same you set) 
![image](https://github.com/user-attachments/assets/d9253e90-bd78-4330-88aa-f9de185b4350)

I'm using these changes in my personal project:
![image](https://github.com/user-attachments/assets/30c50baf-91e9-479c-b5e9-edfa98255bea)

Please guys let me know what you think about these changes. If it's welcome, I can submit an PR.

**Comment by EdnaldoNeimeg** [comment]
@antoniandre

**Comment by antoniandre** [comment]
Hi @EdnaldoNeimeg,
Thanks, this is perfect to create a nice custom layout from outside of Vue Cal.
We will leave this here for reference for the next readers but since currently, you can have all the header controls customized easily outside of Vue Cal (like in this example: https://antoniandre.github.io/vue-cal-v4/#ex--external-controls), this should stay outside of Vue Cal. :)

Thanks for sharing your nice layout!

**Comment by EdnaldoNeimeg** [comment]
As I mentioned, the intention is to reduce the vertical space used.
External controls would achieve the opposite.

The image demonstrates a nice, clean, and compact layout without additional code.
That said, I’ll leave this matter here.

![image](https://github.com/user-attachments/assets/63e64ef8-b25e-46f6-93f4-411c98dc834a)

**Comment by antoniandre** [comment]
Hey @EdnaldoNeimeg!
I don't think you are aware you can already do this externally. Here's a demo for you.
https://codepen.io/antoniandre/pen/gbYwMWe

Cheers!
