### ISSUE TITLE
Hello, https://antoniandre.github.io/vue-cal/ Unable to open

### ISSUE THREAD

**Issue by fisher7757** [antoniandre/vue-cal-v4#593]
Hello, https://antoniandre.github.io/vue-cal/ Unable to open

**Comment by antoniandre** [comment]
Thanks @fisher7757, it's back online. 
Note that with the new Vue Cal coming at https://github.com/antoniandre/vue-cal, the current v4 documentation will be moved to the Vue Cal 4 repo within the next couple days, the new address will be https://antoniandre.github.io/vue-cal-v4. I will update that link everywhere.

Don't forget to like & share the new Vue Cal repo!
