### ISSUE TITLE
:on-event-click="onEventclick" is not working

### ISSUE THREAD

**Issue by gavinchua** [antoniandre/vue-cal-v4#61]
Project:
https://codesandbox.io/s/61kz580p6k

Events had been populated but the :on-event-click="onEventclick" is not working.

[Vue warn]: Property or method "onEventclick" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by antoniandre** [comment]
Hi @gavinchua,
I tried your example, and noticed the typo `onEventclick ` creating a mismatch with method name, you must have copy pasted from my documentation that has the same typo 😅
I am on the way to correct it!

**Comment by gavinchua** [comment]
Hi @antoniandre,
How could I have missed that typo. Thanks for the quick respond. It's all working good now.
You're awesome! 👍 
God blessed!!

**Comment by antoniandre** [comment]
Thanks for your enthusiasm @gavinchua! 😉
