### ISSUE TITLE
Hide Dates before than today

### ISSUE THREAD

**Issue by lherreranetlink** [antoniandre/vue-cal-v4#63]
Is there a way where **vue-cal** doesn't let the user  pick a date before than this moment? 
For example, Today's March 12th. 2019. I'd like the user wouldn't be able to pick 2018 as year or even February of the current year.

Thank you, I'd appreciate your answer.

**Comment by antoniandre** [comment]
Hi @lherreranetlink, 
There is currently no way to do that. But now that you raise the point this is a great feature to add and I will work on that soon.

**Comment by antoniandre** [comment]
Hi @lherreranetlink, 
I just released the min and max dates feature in version 1.54.0. 
Please refer to this example: https://antoniandre.github.io/vue-cal/#ex--min-max-dates

Hope it helps.
