### ISSUE TITLE
events that are pulled from axios not getting plotted

### ISSUE THREAD

**Issue by chokies** [antoniandre/vue-cal-v4#7]
Just checking if its not possible to plot events that are being pulled via ajax.

**Comment by antoniandre** [comment]
Hi @chokies,
Thanks for your question.
I just released version 1.3.6 to allow that, along with an example in the documentation (example 12).
Also do keep in mind that each time you modify the array of events outside of vue-cal, vue-cal will refresh and replace all the events with the new array (you may lose your changes if you edited events in vue-cal).

Hope it solves your problem!

**Comment by chokies** [comment]
im only using the calendar for read only purposes. also is it possible to display the events on the month view? and be able to remove the delete option

**Comment by antoniandre** [comment]
I am currently wrapping up the delete feature which will only be possible when the option editable-events is true. That will be in the next release this week.
The events are not visible in month view for now, but it's in the to do list to show an indicator.

**Comment by antoniandre** [comment]
The delete feature is now only available when the option editableEvents is set to true (disabled by default).

**Comment by chokies** [comment]
thank you!

**Comment by antoniandre** [comment]
Hi @chokies, 
I have released a new version with month view events indicators, not the whole event showing but it's already helping. Please have a look at the **# Month view with events indicators** example. 
https://antoniandre.github.io/vue-cal/#examples
