### ISSUE TITLE
Bug: startWeekOnSunday then change to following week breaks calendar

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/vue-cal-v4#71]
## Example Reproduction:

* https://jsfiddle.net/qu07c3st

## Steps to reproduce:

1. Enable `:startWeekOnSunday="true"`
1. Change the view to go to the next upcoming week

**Expected:**
* Days and events for the following week will be displayed accurately

**Actual:**
* Days shift over by one day.
* Clicking again shifts them over 7 days.
* The day of the week is now wrong (Today is Monday the 25th, but it will now display as Sunday the 25th).
* Events will be displayed on the wrong day

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt, thanks for reproduction link, I am fixing this asap.

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt, Fixed in version 1.44.1 (your link works now), sorry about that.
