### ISSUE TITLE
Feature Request: readonly attribute

### ISSUE THREAD

**Issue by aocneanu** [antoniandre/vue-cal-v4#72]
Events could have an individual `readonly` attribute.

When this attribute is set to `true` the delete button / edit title / resize should not be available.

**Comment by antoniandre** [comment]
Hi @aocneanu, That makes sense in some cases. I will add it to my list. Thanks.

**Comment by antoniandre** [comment]
Hi @aocneanu, @bernardZhao,
The v2 is out and it is now possible to override the global resizing / deleting ability for each event.
Refer to this example: https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events

Hope it helps.

**Comment by antoniandre** [comment]
same as #77.

**Comment by aocneanu** [comment]
Thanks alot, I'm on it!
