### ISSUE TITLE
Fix calendar height

### ISSUE THREAD

**Issue by Kirich11** [antoniandre/vue-cal-v4#74]
In day and week views the schedule is cut by the container height, which is supposed to be set to display year and month views correctly as said in the documentation.

The bug can be seen in the examples itself
![4](https://user-images.githubusercontent.com/18256217/54998738-ecc2c700-4fdf-11e9-82ab-ced6307d5717.png)

**Comment by Kirich11** [comment]
The actual workaround is to set not the height property for the container, but set the min-height for the calendar

https://jsfiddle.net/76hp053m/1/

Should be mentioned in the documentation and fix the examples, please)

**Comment by antoniandre** [comment]
Hi @Kirich11, I'm sorry but I don't understand the issue, maybe I cannot reproduce it.

Just to be on the same page, what is expected is that the timeline and content are scrollable vertically within the calendar body.
If that is not scrollable for you, can you please let me know your browser and OS.

**Comment by Kirich11** [comment]
Thanks for such quick reply!

Browsers:
- Google Chrome 73.0.3683.75 64 bit
- Mozilla Firefox 66.0.1 64 bit
OS: Ubuntu 18.04

The content inside the calendars is indeed not scrolllable. Doesn't it replicate in here for you: https://antoniandre.github.io/vue-cal/ ?
Or maybe I'm looking at an old version?

**Comment by antoniandre** [comment]
No, this is definitely scrollable on that page at this time, and probably for all the users not complaining haha.
Please check your browser cache in case, and also check this codepen example: https://codepen.io/antoniandre/pen/rPzWOJ, where you should be able to scroll until midnight.
Also make sure that you are hitting the latest version of vue-cal in unpkg from the javascript pane settings. when you click the link you should be on https://unpkg.com/vue-cal@1.43.1/dist/vuecal.umd.min.js

If still not showing well, I am curious to know why and will investigate.

**Comment by Kirich11** [comment]
This feels weird

I've recordered a video with the issue on your codepen example. Here you can see the issue
https://www.useloom.com/share/29f52cb99526450ab83bc577a11476c4

I've noticed that when I go from week view to months there appears  a scrollbar for a second.

**Comment by ghost** [comment]
Im having the same issue

**Comment by antoniandre** [comment]
@Kirich11, @AndreasHansson1,

Thanks for pointing this out, I have introduced a regression lately and it was still showing well on my machine, on Mac.
So fortunately you reported it.

Fixed in version 1.43.2, let me know if you still have an issue.

**Comment by Kirich11** [comment]
@antoniandre 
Just checked the codepen you provided (https://codepen.io/antoniandre/pen/rPzWOJ). Seems to be fixed!

Feel free to close this issue
