### ISSUE TITLE
Feature Request: Add slot on per cell month-view

### ISSUE THREAD

**Issue by ortuagustin** [antoniandre/vue-cal-v4#76]
Thank you for this great library

Currently, we can use `event-renderer` slot to customize the event display; but we cannot customize the cell, specifically, on the month view. My use case would be add a button, per cell, to add/edit events on the selected day (cell). The buttons would be toggled visible using day-focus events

Is there any chance to add a slot for the day (cell), on the month-view?

**Comment by antoniandre** [comment]
Hi @ortuagustin, thanks for feedback. 
I was initially not thinking about allowing cell customization as it adds a lot of complexity to use and would be easy to break the render.

But a compromise that would would probably suffice would be a free content slot before events and/or after events. I am adding it to my todo list 👌

**Comment by antoniandre** [comment]
Hi @ortuagustin,

I have added the ability to customize cells in version 1.46.0. Please refer to this example: https://antoniandre.github.io/vue-cal/#ex--custom-title-and-cells

Hope it helps!

**Comment by antoniandre** [comment]
Please have a look when you have time @ortuagustin, closing this issue for now. 
You can reopen if something is not right!
