### ISSUE TITLE
Separately enable either of features: delete / dragging the handle / editing title

### ISSUE THREAD

**Issue by pimvanderheijden** [antoniandre/vue-cal-v4#77]
Hi!

Really love the module so far.

I was wondering. The features delete / dragging the handle / editing title are currently these features are all controlled with one and the same variable, `editableEvents`. Will it be possible in the future to separately enable either of the features delete / dragging the handle / editing title?

**Comment by antoniandre** [comment]
Hi @MidnightP, thanks for feedback.
Definitely. If there are such use cases, then it should be possible.
I will do it soon 👌

**Comment by antoniandre** [comment]
Hi @MidnightP,

The v2 is out and it is now possible to override the global deletable / draggable individually per event.
Refer to this example https://antoniandre.github.io/vue-cal/#ex--edit-delete-create-events
Editing title stays global config.

Hope it helps.
