### ISSUE TITLE
Extremely long event

### ISSUE THREAD

**Issue by pimvanderheijden** [antoniandre/vue-cal-v4#78]
Hi

Still loving the module.

As a default event that is always in the background I wanted to display a background event with a huge duration. Let's start time 100 years ago and end time 100 years from now. I've noticed that doing this will crash the tab in my browser. Seems it has a hard time rendering.

I will try to find a way to add a `repeating-linear-gradient` to the original background, instead of using a huge default event in the background.

**Comment by antoniandre** [comment]
Hi @MidnightP,
I will have a look into this to see if we can improve the event segmenting performance-wise.
Do you mind creating a codepen for this with your style in there?

**Comment by pimvanderheijden** [comment]
```
const event = {
	start   : moment().subtract(100, "years").format(format),
	end     : moment().add(100, "years").format(format),
	title   : "Peak hour",
	class   : "peak",
	content : "<i class='fas fa-chart-line'></i>",
}
```

This is the problematic event object I used.

**Comment by antoniandre** [comment]
Hi @MidnightP, The V2 is out and this issue is resolved.
Now multiple-day events are calculated in view only.
Don't forget to check the release notes.

Hope it helps!
