### ISSUE TITLE
Disable intersecting events (feature request)

### ISSUE THREAD

**Issue by pimvanderheijden** [antoniandre/vue-cal-v4#80]
In addition to the `no-event-overlaps` option, it would be awesome to have the possibility of disabling intersecting events altogether. Is that an idea?

To be clear, I'd like to drag events and create new ones, but never allow any intersection between them. Not sure yet how this would behave but I'm sure it will very useful.

**Comment by antoniandre** [comment]
this is a feature that will come later, I shall update the todo list and put it after drag and drop.

**Comment by Aterr** [comment]
Hello.
Are there any updates on this feature ?

**Comment by antoniandre** [comment]
Duplicate of #398, please continue thread in there.
