### ISSUE TITLE
Always show delete option

### ISSUE THREAD

**Issue by pimvanderheijden** [antoniandre/vue-cal-v4#81]
Hi! 

Would it be an idea to always show a delete cross in top right / left of an event?

The mouse down approach for showing the delete button is cute but not obvious if you ask me.

Cheers!!

**Comment by antoniandre** [comment]
Hi @MidnightP, 
This is something you can do with a CSS rule.
When events are editable, the delete button is in the event HTML, with some style applied.
If you want to reposition it, just remove the default `transform: translateY(-110%)` property.
The delete button will still be clickable.
Hope it helps.
