### ISSUE TITLE
[Feature Request] Add onDateClick event

### ISSUE THREAD

**Issue by Kirich11** [antoniandre/vue-cal-v4#82]
Could it be possible to add a event that fires when date is clicked instead of day-focus?
That way it would be more convinient to build components logic around user interactions with the calendar.

 E.g. the user clicked a date, some modal has opened, user closed the modal, forgot smth, and clicks the same date to open the modal again, but because the date is already focused day-focus won't be fired again, thus the user has to focus another date and after that he can open the first modal

Or is it possible somehow and I'm missing something in the documentation?

**Comment by antoniandre** [comment]
Hi @Kirich11, 
That makes sense. I have added the emitted event `day-click` in version 1.45.0.
Please refer to the documentation: https://antoniandre.github.io/vue-cal/#ex--emitted-events

**Comment by Kirich11** [comment]
@antoniandre thank you very much!
awesome!
