### ISSUE TITLE
Publish releases on GitHub

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/vue-cal-v4#83]
Most npm packages will publish a release on both GitHub and `npm`. This is super helpful as it lets users see exactly when a release occurred so they know what code went out with that version (features/bug fixes).

I had a recent bug report that was fixed and a release occurred around the same time, but the bug fix wasn't mentioned in the `README.md`, so I had to find the closed, find the [code example](https://jsfiddle.net/Lxacyvu2/), check to see if it's using the latest release, update the fake data in the example to more easily reproduce the issue again, and then retest it to see if it's fixed.

This is unnecessarily cumbersome and would have been much easier to just look at the releases page and see the code changes in GitHub. Even if the bug fix isn't mentioned, I can still easily do a commit compare against the last release tag and see that the code changes that fix my bug are apparent in that release (or not).

**Example:**

* [Vue-Good-Table Releases page](https://github.com/xaksis/vue-good-table/releases)
* Release tag comparison: https://github.com/xaksis/vue-good-table/compare/v2.16.2...v2.16.3

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt, 

Thanks for letting me discover the releases feature on Github! 😅 
I was already tagging my work in NPM so I could easily recover all the past tags to push them on Github.

You can now find the history here: https://github.com/antoniandre/vue-cal/releases
and diffs: https://github.com/antoniandre/vue-cal/compare/v1.44.0...v1.46.0

I am not going to document the tags in Github though, as I have an up to date release notes in my documentation: https://antoniandre.github.io/vue-cal/#release-notes

Hope it helps!
