### ISSUE TITLE
Making a separate calendar view changer button.

### ISSUE THREAD

**Issue by kylecueters** [antoniandre/vue-cal-v4#86]
Is there a way I can make a separate button to change my calendar view? I removed the default view selector for customization purposes. Is there a way I can make it? Thanks.

**Comment by kylecueters** [comment]
Never mind I solved it using vue refs. Using the switchView method and passing a view string. For example.

```
<template>
  <vue-cal
              ref="calendar"
              :disable-views="['years', 'year', 'month']"
              :default-view="defaultView"
              :time-from="8 * 60"
              :time-to="(18 * 60) + 10"
              :time-step="10"
              :12Hour="true"
              :events="teeTimes"
              :hideViewSelector="true"
              @view-change="viewChanged('view-change', $event)"
 />
</template>

<script>
 methods: {
  changeView() {
   this.$refs.calendar.switchView('day')
  } 
 }
</script>
```

**Comment by antoniandre** [comment]
Very good @kylecueters. 👌 
I would have suggested the same. I will probably add such example in documentation soon.

**Comment by kylecueters** [comment]
Thanks @antoniandre! Great package anyway! 😃
