### ISSUE TITLE
Event time info not showing when event starts at midnight

### ISSUE THREAD

**Issue by nature-li** [antoniandre/vue-cal-v4#91]

**Comment by antoniandre** [comment]
Hi @nature-li, 
Please share your code and develop your question.
I don't know what you are talking about right now. 
___
Thank you for your explanation in next comment, I renamed the issue.

**Comment by nature-li** [comment]
Hi @antoniandre ,
Sorry for the unclear issue. I mean when I make time-from = 0,  time-to = 24 * 60, time-step=30, time=true. And I have 48 events every 30 minutes in a whole day.  In the week view I expect I can get 00:00 - 00:30 in the first row, 00:30 - 01:00 in the second row,  01:00-01:30 in the third row. **But the first row is empty**. From the second row on, it works like 00:30 - 01:00, 01:00 - 01:30 ...

**Comment by antoniandre** [comment]
Hi @nature-li, 
Thanks for reporting this bug.
I have fixed it in version 1.50.3
Here is a working codepen after fix with the initial same issue you reported.
https://codepen.io/antoniandre/pen/gyXdar?editors=1010

Hope it helps. Please close if solved.

**Comment by nature-li** [comment]
Hi @antoniandre,
I installed the 1.50.3 version and it works for me. Thank you fix the bug.
