### ISSUE TITLE
Split Vue Cal timeline in 2:  from 10 to 13 and from 14 to 17

### ISSUE THREAD

**Issue by webdeluxe** [antoniandre/vue-cal-v4#92]
Hi can you help me, Im using Vue cal. 
I need time from 10 to 13 and from 14 to 17. 
Is it possible ?

**Comment by antoniandre** [comment]
Hi @webdeluxe, 
Sorry but this is not possible and won't be in the future in a single event calendar.

But good news, what you can do is something like this https://codepen.io/antoniandre/pen/KYXjQq.
When it comes to interactions, if you need any, you will need to sync the 2 instances, like in this example https://antoniandre.github.io/vue-cal/#ex--sync-two-calendars

But what I recommend is that you display a line of background events like in this example: http://localhost:8081/#ex--background-events to materialize that this slot (13:00-14:00) is unavailable.

Hope it helps.

**Comment by antoniandre** [comment]
I have update the example adding syncing between 2 instances, but still recommend a line of background events.

**Comment by webdeluxe** [comment]
thx.
