### ISSUE TITLE
How to get selectedDate info for searching in db?

### ISSUE THREAD

**Issue by GeorgiNiagulov** [antoniandre/vue-cal-v4#93]
Hi @antoniandre,
thanks for this calendar. Sorry for my English.
 I need to get selected date and search with this date in db to get info from there.
 This is my code
```
  <vue-cal class="vuecal--blue-theme vuecal__bg" style="height: 300px" :time="false" locale="bg" small
                    dbl-click-to-navigate :disable-views="['week','day']" @day-focus="selectedDate = $event"
                    default-view="year" show-weekends></vue-cal>
                <vue-cal class="vuecal--blue-theme" style="height: 3000px" small :time="false" hide-view-selector
                    default-view="day" locale="bg" :disable-views="['years','year','month','week']"
                    :selected-date="selectedDate" >
                </vue-cal>
```
```
<script>
let calendar = new Vue({
    el: '#calendar',
    data: () => ({
        selectedDate: null
    }),
    components: {
        'vue-cal': vuecal
    },
    methods: {
        onEventClick(event, e) {
            this.selectedEvent = event
            this.showDialog = true

            // Prevent navigating to narrower view (default vue-cal behavior).
            e.stopPropagation()
        },
    
    },
})
</script>
```
Thanks for answer.

**Comment by antoniandre** [comment]
Hi @GeorgiNiagulov,
Thanks for your feedback.
This is how to fetch events for the current view: https://codepen.io/antoniandre/pen/rbpPab

You should use the `view-change` event for this as you always want all the events of the whole view.
The `view-change` event is emitted every time you change view, including previous and next arrows, title click, cell click, and view selector view click.

on view-change you just need to call the fetch events method:

```js
fetchEvents ({ startDate, endDate }) {
      // Do an axios call (for instance) here.
      console.log('Fetching events', { startDate, endDate })
}
```

**Comment by antoniandre** [comment]
Closing the issue for inactivity.

**Comment by juliaam** [comment]
> Hi @GeorgiNiagulov, Thanks for your feedback. This is how to fetch events for the current view: https://codepen.io/antoniandre/pen/rbpPab
> 
> You should use the `view-change` event for this as you always want all the events of the whole view. The `view-change` event is emitted every time you change view, including previous and next arrows, title click, cell click, and view selector view click.
> 
> on view-change you just need to call the fetch events method:
> 
> ```js
> fetchEvents ({ startDate, endDate }) {
>       // Do an axios call (for instance) here.
>       console.log('Fetching events', { startDate, endDate })
> }
> ```

god bless u
