### ISSUE TITLE
Hide the first full week of the next month

### ISSUE THREAD

**Issue by vks-financial-com** [antoniandre/vue-cal-v4#95]
I totally need to remove the last row in the month view, which is a full week of the next month, which is currently always visible. Any way to do it? I couldn't find any feasible workaround, as there are no real row elements in the dom-structure, so that they could get hidden by CSS.

**Comment by antoniandre** [comment]
Hi @vks-financial-com,

Unfortunately we don't want to remove that last row for the reason I explained here: https://github.com/antoniandre/vue-cal/issues/98
Some months have days on that row.

You should not remove that row neither, if you can navigate through dates and if your view is dynamic you should allow 6 possible rows.

**Comment by vks-financial-com** [comment]
No I mean the calendar should allow to disable the last row, if there are no days of the current month in that row. In my case it's just useless white space as I hide the content of all cells which do not belong to current month per CSS.

**Comment by antoniandre** [comment]
Hi @vks-financial-com,
Ok if you have reasons to do it no worries. 
To hide all the cells of next month it is as simple as that:

```css
.vuecal__cell:not(.out-of-scope) ~ .vuecal__cell.out-of-scope {display: none}
```

(Fully supported since IE9)
You don't even need to target month view since the `.out-of-scope` class only appears on month view.
