### ISSUE TITLE
BUG: @ready no longer returns evt.view ('month', 'week')

### ISSUE THREAD

**Issue by TheJaredWilcurt** [antoniandre/vue-cal-v4#99]
**Example:**

* https://jsfiddle.net/qavgc5jy/

That code works fine with Vue-Cal `v1.45.0`. At some point between `1.45.0` and `1.50.3` this broke.

**Comment by antoniandre** [comment]
Hi @TheJaredWilcurt,
Thanks for reporting, this is fixed in version 1.50.4
